src/Utilities/ComplianceBackend/ComplianceBackendAPI.js

We need to ensure the calls go authenticated.

Wait for getUser before making any API calls

---

package-lock.json
package.json
src/SmartComponents/Compliance/Compliance.js
src/SmartComponents/InventoryDetails/InventoryDetails.js
src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemPolicyCard/SystemPolicyCard.js
src/SmartComponents/SystemPolicyCards/SystemPolicyCards.js
src/SmartComponents/SystemRulesTable/SystemRulesTable.js
src/store/Reducers/SystemStore.js

:warning: Merging this will break the frontend in CI and QA until https://github.com/RedHatInsights/insights-chrome/pull/86 is merged (expected for next Monday Dec 17th)

System Details page

---

src/SmartComponents/SystemRulesTable/SystemRulesTable.js

https://redhat.invisionapp.com/share/V8PLHRR6FAY#/screens/336685941
This displays rule description and rationale under each row if you click on it.

Move rules to TreeView table

---

package-lock.json
package.json
src/SmartComponents/SystemsTable/SystemsTable.js

No UI changes yet, can be merged before https://github.com/RedHatInsights/insights-frontend-components/pull/168 and once that PR is merged and new version is applied to chrome inventory will get automatically pagination.

Pass pagination row to inventory so it can use pagination in future

---

config/base.webpack.plugins.js
package.json
src/entry-dev.js
src/entry.js

changes basename to `/insightsbeta/platform/compliance` when branch is master, qa-beta, or prod-beta

fixes beta deployments

---

package-lock.json
src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/store/Reducers/SystemStore.js

This covers the DataProvider for the multiple systems table. I should be adding this button to the Rules table shortly, so we can fix specific issues in multiple hosts.

Data Provider for InsightsRemediations

---

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/SmartComponents/SystemRulesTable/SystemRulesTable.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/store/Reducers/SystemStore.js

Add Remediations integration to Rules table

---

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.scss
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemPolicyCard/SystemPolicyCard.js
src/SmartComponents/SystemRulesTable/SystemRulesTable.js
src/SmartComponents/SystemsTable/SystemsTable.js

Buttons for systems table show up separated
Breadcrumbs are no longer misaligned.
System policy cards look more similar to the mockup ones.
Rules table uses the right font size.
Remediate with Ansible button has proper padding.

Various design fixes

---

src/Charts.scss
src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js
src/SmartComponents/PolicyDetails/PolicyDetails.js

Move to Patternfly donuts

---

.travis/custom_release.sh
README.md
package-lock.json
src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js
src/SmartComponents/CompliancePolicyDonut/CompliancePolicyDonut.js
src/SmartComponents/PolicyDetails/PolicyDetails.js

This also fixes a small problem in the donuts where the numbers could show stupidly large amount of decimals like 66.66666666666666666666666666666666 % compliant.

Support stable branch

---

src/SmartComponents/SystemsTable/SystemsTable.js

Filter items in inventory before matching compliance results

---

src/SmartComponents/PolicyDetails/PolicyDetails.js

This will only work when https://github.com/RedHatInsights/compliance-backend/pull/57 gets deployed

Only fetch hosts related with selected profile

---

package.json
src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js
src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

Make sure cards are the same height

---

package-lock.json
package.json
src/App.scss
src/Routes.js
src/index.html

Requires https://github.com/RedHatInsights/insights-chrome/pull/147

Update pf-next to 1.0.175

---

src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js
src/SmartComponents/SystemRulesTable/SystemRulesTable.js

Before this change, this.state.rows on the SystemRulesTable was not
updated until you clicked twice on it, hence the sort button would
appear buggy as you had to click twice on it to work.

Sort on first click

---

.babelrc
.eslintrc.yml
package-lock.json
package.json
src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/SystemsTable/SystemsTable.js

This enable the Remediate with Ansible button in the systems table,
where it loads all remediations available and tries to create a playbook
using that.

Support fixing all fixable remediations in a system

---

package-lock.json
package.json
src/SmartComponents/SystemDetails/SystemDetails.js
src/store/Reducers/SystemStore.js

Depends on https://github.com/RedHatInsights/insights-frontend-components/pull/341

Display link to failed rules

---

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

This aids front end test automation.

Fixes RHICOMPL-102: Add widget-id to policy cards

---

package-lock.json
package.json
src/App.scss
src/SmartComponents/ComplianceTabs/ComplianceTabs.js

Adapt tabs to pf4

---

README.md
config/base.webpack.plugins.js
config/dev.webpack.config.js
config/spandx.config.js
config/webpack.common.js
src/entry-dev.js
src/entry.js
src/index.html

You might gonna have to run `npm run build` if you see some errors with static files from `insights/plaform`

Update routing to match new version of cloud

---

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/constants.js

Follows https://github.com/RedHatInsights/compliance-backend/pull/84

Send requests to /api in cloud.redhat.com

---

src/SmartComponents/DownloadTableButton/DownloadTableButton.js

https://projects.engineering.redhat.com/browse/RHICOMPL-96
This icon may change in the future, but the tool tip should be mostly the same code.

Fixes RHICOMPL-96: Add a tooltip to the download icon

---

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

Before:
After:
Mockup:
https://redhat.invisionapp.com/share/V8PLHRR6FAY#/screens/336685939

Update card to match mockups

---

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

Towards https://projects.engineering.redhat.com/browse/RHICOMPL-123

Use pf-global--Color--200 color for External Policy

---

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

This is meant to fix the rest of the issues associated with [RHICOMPL-123](https://projects.engineering.redhat.com/browse/RHICOMPL-123).
Before:
After:

Fixes RHICOMPL-123: Fix UI issues to match mockup in policy card

---

src/SmartComponents/DownloadTableButton/DownloadTableButton.js
src/SmartComponents/SystemsTable/SystemsTable.js

Fixes RHICOMPL-106: Toolbar should not be nested in the Table

---

package-lock.json
package.json
src/SmartComponents/PolicyDetails/PolicyDetails.js

https://projects.engineering.redhat.com/browse/RHICOMPL-77
Requires https://github.com/RedHatInsights/insights-frontend-components/pull/363

Use linkifyjs to make links in policy detail description

---

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

Follows from [these comments](https://github.com/RedHatInsights/insights-frontend-components/pull/365#pullrequestreview-220877404)

Remove binds, pass policy to super in compliance policy card

---

src/SmartComponents/PolicyDetails/PolicyDetails.js
src/store/Reducers/SystemStore.js

This PR is meant to merge the current "score" and "compliant" columns into "Compliance score" as per https://redhat.invisionapp.com/share/V8PLHRR6FAY#/screens/336685940_Compliance_2
@katierik

RHICOMPL-125 - Fix Compliance Score column

---

package-lock.json
package.json
src/entry-dev.js
src/entry.js
src/store/Reducers/SystemStore.js

RHICOMPL-125 - Add relative time to 'last scanned' column

---

package-lock.json
package.json
src/Routes.js
src/SmartComponents/ComplianceImageStreams/ComplianceImageStreams.js
src/SmartComponents/ComplianceImageStreamsTable/ComplianceImageStreamsTable.js
src/SmartComponents/ComplianceTabs/ComplianceTabs.js
src/SmartComponents/ErrorPage/ErrorPage.js
src/SmartComponents/ImageStreamsWizard/AddOpenshiftConnection.js
src/SmartComponents/ImageStreamsWizard/ApplyPoliciesToImageStreams.js
src/SmartComponents/ImageStreamsWizard/ImageStreamEmptyState.js
src/SmartComponents/ImageStreamsWizard/ImageStreamsWizard.js
src/SmartComponents/ImageStreamsWizard/ReduxFormWrappers.js
src/SmartComponents/ImageStreamsWizard/SelectPolicy.js
src/SmartComponents/ImageStreamsWizard/Wizard.js
src/SmartComponents/ImageStreamsWizard/validate.js
src/SmartComponents/ImageStreamsWizard/wizard.scss
src/Utilities/ComplianceBackend/ComplianceBackendAPI.js
src/store/index.js

We may have this in beta, step by step, and only promote to stable by cherrypicking, thoughts @akofink? This will be a very large change if I have to include everything at once:
@katierik

Openshift scanning first wizard step

---

src/SmartComponents/SystemsComplianceFilter/SystemsComplianceFilter.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/constants.js

Requires https://github.com/RedHatInsights/compliance-backend/pull/104#pullrequestreview-225109332 to work

Compliance and Compliance Score Filter

---

src/App.js
src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/Utilities/Dispatcher.js
src/store/index.js

Display notification after Remediation is created

---

package-lock.json
package.json
src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js

RHICOMPL-188 - Copy oscap command to clipboard

---

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js

RHICOMPL-197 - Move 'more details' to middle of card

---

src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js
src/store/Reducers/SystemStore.js

RHICOMPL-215 - Papercut: Display compliance score on systems table

---

src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js
src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js
src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/SetThresholdDropdown/UpdateProfileThreshold.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/store/Reducers/SystemStore.js

Do NOT merge before https://github.com/RedHatInsights/compliance-backend/pull/171 please :smiley:

 GraphQL rename to camelCase convention 

---

package.json

This should allow our builder to build compliance frontend every night with the newest patternfly packages

Add a nightly build script

---

package-lock.json
package.json
src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js

This also includes adaptions to ensure the new GraphQL API works with the remediate with Ansible button.

RHICOMPL-133 - Update notifications when a new remediation is created

---

src/SmartComponents/SystemsTable/SystemsTable.js

RHICOMPL 231 - Search in systems table

---

package-lock.json
package.json
src/App.scss
src/SmartComponents/EditPolicy/BusinessObjectiveField.js
src/SmartComponents/ReduxFormWrappers/ReduxFormWrappers.js

In addition to the main change, I'm using a version of react-select here that's meant to be integrated with pf4, and updating the react-core.

RHICOMPL-250 - Select business objective should not show vertical scroll

---

src/SmartComponents/EditPolicy/BusinessObjectiveField.js
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/UpdateProfile.js

RHICOMPL 251 - Create business objective automatically

---

src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js

To reproduce:
Upload 2 policies for 1 system, and look at the total displayed by the systems table.

Systems table counts systems, not profiles

---

package-lock.json
package.json

According to https://codecov.io/gh/RedHatInsights/compliance-frontend - it'll show up as soon as this is merged and we upload some results.

Enable codecov

---

package.json

`.travis.yml` has `travis:verify` configured, so `coverage` should be there.

Correct travis:verify task

---

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js

This little thing will save us the API call to remediations API every time we hit the remediation button to fix a system (so this works on PolicyDetails or SystemDetails).

Use remediationAvailable to avoid remediations API call

---

package-lock.json
package.json
src/SmartComponents/EditPolicy/BusinessObjectiveField.js
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/UpdateProfile.js

RHICOMPL-376 - Fix reusing BusinessObjective

---

src/SmartComponents/PolicyDetails/PolicyDetails.js

There is no guarantee (read: backend model validation) that policy descriptions exist.

Handle null policy description in PolicyDetails

---

src/App.scss
src/SmartComponents/CompliancePolicies/CompliancePolicies.js
src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap
src/SmartComponents/ComplianceReports/ComplianceReports.js
src/SmartComponents/ComplianceReports/__snapshots__/ComplianceReports.test.js.snap
src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap

:warning: Mutual dependency with https://github.com/RedHatInsights/cloud-services-config/pull/106
:warning: To be merged ONLY after https://github.com/RedHatInsights/compliance-frontend/pull/197

Enable tabs if stable, vertnav if beta

---

src/SmartComponents/BusinessObjectiveField/BusinessObjectiveField.js

Creating policies introduced a new reduxform name.
This corrects the BO field to refer to the new one.

Fix business objectives field

---

src/SmartComponents/BusinessObjectiveField/BusinessObjectiveField.js
src/SmartComponents/BusinessObjectiveField/BusinessObjectiveField.test.js
src/SmartComponents/BusinessObjectiveField/__snapshots__/BusinessObjectiveField.test.js.snap
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/ProfileThresholdField/ProfileThresholdField.js
src/SmartComponents/ProfileThresholdField/ProfileThresholdField.test.js
src/SmartComponents/ProfileThresholdField/__snapshots__/ProfileThresholdField.test.js.snap

This PR fixes the problem of repeated titles on the EditPolicy modal.

Do not display title twice on Threshold/BO fields

---

src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/store/Reducers/SystemStore.js

Instead of letting the inventory think "loaded" is `true` when it's requesting just `[]`, this PR makes sure the GraphQL request has finished before setting `loaded` to `true`.

Poor man's solution to SystemsTable loading state

---

src/SmartComponents/CompliancePolicies/CompliancePolicies.js
src/SmartComponents/PoliciesTable/PoliciesTable.js
src/SmartComponents/PoliciesTable/PoliciesTable.test.js
src/SmartComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/SmartComponents/PoliciesTable/fixtures.js

Adding system count to the table, to match https://marvelapp.com/c2bcd9h/screen/62294966 a bit more.

Add system count to Policies table

---

src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/DeletePolicy.test.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
src/SmartComponents/PoliciesTable/PoliciesTable.js
src/SmartComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/Utilities/graphql/mutations.js

Needs https://github.com/RedHatInsights/compliance-backend/pull/303 to work

Delete policy action on PoliciesTable

---

package-lock.json
package.json
src/PresentationalComponents/ReduxFormWrappers/__snapshots__/ReduxFormWrappers.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap

Bumping @patternfly/react-core to 3.134.2

---

src/SmartComponents/PoliciesTable/PoliciesTable.js
src/SmartComponents/PoliciesTable/PoliciesTable.test.js

Resolve link to policy results correctly if not in page 1

---

src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/store/Reducers/SystemStore.js

Before:
After:
Note this is going straight to QA

[QA] Reload systems table when identical items are sent twice

---

src/SmartComponents/SystemsTable/SystemsTable.js

[CI] Refresh inventory manually if identical items are sent twice

---

src/PresentationalComponents/CheckboxGroup/CheckboxGroup.js
src/PresentationalComponents/CheckboxGroup/CheckboxGroup.test.js
src/PresentationalComponents/CheckboxGroup/__snapshots__/CheckboxGroup.test.js.snap
src/PresentationalComponents/ReduxFormWrappers/ReduxFormWrappers.js
src/PresentationalComponents/ReduxFormWrappers/ReduxFormWrappers.test.js
src/PresentationalComponents/ReduxFormWrappers/__snapshots__/ReduxFormWrappers.test.js.snap
src/PresentationalComponents/index.js
src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.js
src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.test.js
src/SmartComponents/AssignPoliciesModal/SubmitPoliciesButton.js
src/SmartComponents/AssignPoliciesModal/SubmitPoliciesButton.test.js
src/SmartComponents/AssignPoliciesModal/__snapshots__/AssignPoliciesModal.test.js.snap
src/SmartComponents/AssignPoliciesModal/__snapshots__/SubmitPoliciesButton.test.js.snap
src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap
src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/DeletePolicy.test.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/SmartComponents/index.js
src/Utilities/graphql/mutations.js

This is just a draft for now to show how to add actions to the current systems table in case it's useful until I finish it.

RHICOMPL-292 - Assign policies to UI

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/store/Reducers/SystemStore.js
src/store/Reducers/SystemStore.test.js

allSystems=true for host-policy wizard
allSystems=false for systems tab (aka reports by system)

Add bool allSystems option for SystemsTable

---

src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/Utilities/ChipBuilder.js
src/Utilities/ChipBuilder.test.js
src/Utilities/FilterBuilder.js
src/Utilities/FilterBuilder.test.js
src/Utilities/FilterConfigBuilder.js
src/Utilities/FilterConfigBuilder.test.js
src/Utilities/__snapshots__/ChipBuilder.test.js.snap
src/Utilities/__snapshots__/FilterBuilder.test.js.snap
src/Utilities/__snapshots__/FilterConfigBuilder.test.js.snap
src/constants.js

Introduces a "ChipBuilder" service to help with generating chips in `SystemsTable`.
It also rewrites `FilterBuilder` to a proper service class.
Both are available via the filter configuration in `SystemsTable` and make use of the configuration to do their thing.

Extract chip building from SystemsTable

---

src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.js
src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.test.js
src/SmartComponents/AssignPoliciesModal/SubmitPoliciesButton.js
src/SmartComponents/AssignPoliciesModal/__snapshots__/AssignPoliciesModal.test.js.snap

Requires https://github.com/RedHatInsights/compliance-backend/pull/330

Create host if not exists on host-profile association

---

src/PresentationalComponents/ReportTabs/ReportTabs.js
src/PresentationalComponents/ReportTabs/__snapshots__/ReportTabs.test.js.snap

Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-503

s/By systems/By system/ in navigation tab

---

src/SmartComponents/CreatePolicy/EditPolicyRules.js
src/SmartComponents/CreatePolicy/EditPolicyRules.test.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyRules.test.js.snap

:warning:  Requires https://github.com/RedHatInsights/frontend-components/pull/392 to work
Still in draft until the frontend-components part is merged

 RHICOMPL-502 - Save list of selected rules to tailor

---

src/PresentationalComponents/ErrorPage/ErrorPage.js
src/PresentationalComponents/ErrorPage/__snapshots__/ErrorPage.test.js.snap

Changes based on feedback from UX (aka. @katierik). Icon subject to change.

Minor changes and polish ErrorPage

---

src/SmartComponents/SystemsTable/SystemsTable.js

Changes suggested by @karelhala to fix filters stanard for the inventory table.

Update onRefresh to return options to inventory

---

src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/CreatePolicy.test.js

Clear wizard values when closing it

---

src/App.scss
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap

Style OS selection buttons

---

src/SmartComponents/EditPolicy/UpdateProfileButton.js

When the function doesn't resolve by default it, for some reason gets lost... 🤷‍♂

Resolve handleBusinessObjective by default

---

src/SmartComponents/CompliancePolicies/CompliancePolicies.js
src/SmartComponents/PoliciesTable/PoliciesTable.js
src/SmartComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/SmartComponents/PoliciesTable/fixtures.js

Requires https://github.com/RedHatInsights/compliance-backend/pull/388

RHICOMPL-548 - Show SSG version in Policies table

---

src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap

RHICOMPL-571 - Show tooltip close to threshold icon

---

package-lock.json
package.json
src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.js
src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.test.js
src/SmartComponents/AssignPoliciesModal/__snapshots__/AssignPoliciesModal.test.js.snap
src/Utilities/InventoryApi.js
src/constants.js

For a host which has system_profile empty:
For a host that actually has the os_release in system_profile:

RHICOMPL-575 - AssignPoliciesModal only lists policies matching OS

---

src/SmartComponents/PolicyDetails/PolicyRulesTab.js

Add warning about ssg version rules

---

src/PresentationalComponents/ComplianceScore/ComplianceScore.js
src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap

RHICOMPL-523 - Compliance score icon should be -200 dark

---

src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap

RHICOMPL-590 - Add spacing in Delete Policy modal

---

src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js

RHICOMPL-526 - Show -- if BO is missing

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap
src/store/Reducers/SystemStore.js
src/store/Reducers/__snapshots__/SystemStore.test.js.snap

This matches the mocks more accurately :smile:

RHICOMPL-528 - All systems table papercuts

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap

:warning: There's some error when rendering the test currently

RHICOMPL-589 - Add tooltip to show SSG version on wizard

---

src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js

Link is only meant to be used for links within react-router-dom

Fix link pointing to external URL docs

---

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap
src/SmartComponents/CreatePolicy/fixtures.js

RHICOMPL-614 - Add missing details to Review page

---

src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/constants.js

We aren't showing compliance status and score at the moment, therefore we also will remove the filters for them for now.

RHICOMPL-603 - Make compliant filter optional

---

src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap

and make sure it is still enabled when items are selected

RHICOMPL-578 - Determine if export is disable with entity count

---

src/PresentationalComponents/CompliancePoliciesEmptyState/CompliancePoliciesEmptyState.js
src/PresentationalComponents/CompliancePoliciesEmptyState/__snapshots__/CompliancePoliciesEmptyState.test.js.snap

The Button variant='link' from Patternfly just styles the text, but it needs an anchor tag to actually link to somewhere.

Add link within EmptyState OpenSCAP Button

---

src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/PolicyDetails.test.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap

RHICOMPL-612 - Update PolicyDetails to match mock

---

src/store/Reducers/SystemStore.js
src/store/Reducers/__snapshots__/SystemStore.test.js.snap

RHICOMPL-524 - Overflow policies column with Tooltip

---

src/PresentationalComponents/ReportCard/PolicyPopover.js

RHICOMPL-522 - Show labels inline popover

---

config/spandx.config.js

Update non-beta section to insights

---

src/PresentationalComponents/ErrorPage/ErrorPage.js
src/PresentationalComponents/ErrorPage/ErrorPage.test.js
src/PresentationalComponents/ErrorPage/__snapshots__/ErrorPage.test.js.snap
src/SmartComponents/CompliancePolicies/CompliancePolicies.js
src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap
src/SmartComponents/Reports/Reports.js
src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap

Requires https://github.com/RedHatInsights/frontend-components/pull/510 to be merged and released and for us to bump the FC version in this repo.

Use NotAuthorized component to handle 403s

---

src/SmartComponents/BusinessObjectiveField/BusinessObjectiveField.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.test.js
src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap
src/SmartComponents/EditPolicy/UpdateProfileButton.js
src/SmartComponents/EditPolicy/UpdateProfileButton.test.js
src/Utilities/businessObjectiveMutation.js
src/Utilities/businessObjectiveMutation.test.js

RHICOMPL-614 - Add BusinessObjective to Policy details

---

src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap

RHICOMPL-579 - Responsive delete report button

---

src/SmartComponents/Reports/Reports.js
src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap

Mocks in https://marvelapp.com/c2bcd9h/screen/68517160 show the title should be Compliance Reports even in an empty state

Update title to Compliance Reports page

---

src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.js
src/SmartComponents/CompliancePolicies/CompliancePolicies.js

This **must be deployed** before the backend changes in https://github.com/RedHatInsights/compliance-backend/pull/497 are deployed.

Update profile queries to include canonical = false

---

src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap

RHICOMPL-581 - Edit policy button responsiveness

---

src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.js
src/SmartComponents/AssignPoliciesModal/__snapshots__/AssignPoliciesModal.test.js.snap
src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
src/SmartComponents/DeleteReport/DeleteReport.js
src/SmartComponents/DeleteReport/__snapshots__/DeleteReport.test.js.snap
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap

Restores small modals like the delete or edit dialogues.

Correct modal variant for PF4

---

README.md

Added some notes to the README that are worth mentioning.

Add some coding notes to README

---

docker-compose.yml

@bastilian whoops, forgot to fix this one in the previous PR

s/npm ci/npm i/ for local chrome

---

src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.test.js
src/SmartComponents/AssignPoliciesModal/SubmitPoliciesButton.test.js
src/SmartComponents/CreatePolicy/EditPolicyRules.test.js
src/SmartComponents/SystemsTable/SystemsTable.test.js

Small (test) fixes to reduce the amount of warnings shown.

Minor fixes for tests

---

config/base.webpack.config.js
config/base.webpack.plugins.js

Caching is very strong on production and can require clearing the
browser cache. This should mitigate the issue.

[RHICOMPL-831] Enable filename hashing

---

src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/validate.js
src/SmartComponents/CreatePolicy/validate.test.js
src/SmartComponents/ProfileThresholdField/ProfileThresholdField.js
src/SmartComponents/ProfileThresholdField/__snapshots__/ProfileThresholdField.test.js.snap

* Adds validation for rules to be selected
* Fixes compliance threshold validation

[RHICOMPL-832] Improve validation for "Create Policy"

---

src/App.js

https://projects.engineering.redhat.com/browse/RHICOMPL-897

[RHICOMPL-897] Hide global filter on all compliance screens

---

package-lock.json
package.json

See https://github.com/RedHatInsights/frontend-components/pull/737 for changes included in this bump

[RHICOMPL-777] Bump frontend-components-inventory-compliance

---

src/SmartComponents/SystemsTable/SystemsTable.js

The message should not be dismissable.

[RHICOMPL-977] Remove possibility to dismiss message about systems

---

src/entry-dev.js
src/entry.js

* Remove unnecessary `getUser` call
* use `getBaseName` from frontend components utils

Clean up entry files

---

package-lock.json
package.json

chore(deps): Update inventory-compliance to 2.2.9

---

src/App.scss
src/SmartComponents/Reports/Reports.js

feat(RHICOMPL-1059): Add notice on external report deprecation

---

src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetails.test.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/__fixtures__/systems.js
src/constants.js
src/store/Reducers/SystemStore.js
src/store/Reducers/__snapshots__/SystemStore.test.js.snap

feat(RHICOMPL-684): Add SSG version to report details systems

---

src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportCard/ReportCard.js
src/PresentationalComponents/ReportCard/ReportCard.test.js
src/PresentationalComponents/ReportCard/__snapshots__/ReportCard.test.js.snap
src/PresentationalComponents/ReportsTable/Cells.js
src/PresentationalComponents/ReportsTable/Cells.test.js
src/PresentationalComponents/ReportsTable/Filters.js
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/Filters.test.js.snap
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetails.test.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/Reports/Reports.js
src/SmartComponents/Reports/Reports.test.js
src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap
src/__fixtures__/policies.js
src/store/Reducers/SystemStore.js

Requires https://github.com/RedHatInsights/compliance-backend/pull/662

feat(scoring): RHICOMPL-1085 report accurate scores for a policy

---

src/constants.js

fix(SystemsTable): RHICOMPL-1131 filter by policy

---

package-lock.json
package.json

chore(deps): bump @redhat-cloud-services/frontend-components-inventory-compliance from 2.2.11 to 2.2.12

---

src/Routes.js
src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/EditPolicy.test.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/PolicyDetails.test.js
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetails.test.js
src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemDetails/SystemDetails.test.js
src/Utilities/Router.js
src/Utilities/hooks/useDocumentTitle.js
src/constants.js
src/index.html

Implements support for route titles and sets consistent titles for each route.

feat(Routes): RHICOMPL-830 - Implement consistent title

---

src/App.scss
src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js

This updates the policy details on the report details page to align more with the mockups:

fix(ReportDetails): RHICOMPL-913 -Update policy details

---

package-lock.json
package.json

The latest release causes issues with the remediations button.

fix(deps): Downgrade inventory-compliance

---

src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap

fix(ReportsTable): Adjust column widths

---

config/setupTests.js
package-lock.json
package.json
src/PresentationalComponents/CheckboxGroup/CheckboxGroup.js
src/PresentationalComponents/PoliciesTable/PoliciesTable.test.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportCardGrid/ResportsCardGrid.test.js
src/PresentationalComponents/ReportCardGrid/__snapshots__/ResportsCardGrid.test.js.snap
src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js
src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.test.js
src/PresentationalComponents/ReportDetailsDescription/__snapshots__/ReportDetailsDescription.test.js.snap
src/PresentationalComponents/ReportsTable/Cells.js
src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js
src/PresentationalComponents/UnsupportedSSGVersion/__snapshots__/UnsupportedSSGVersion.test.js.snap
src/Routes.js
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.test.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/ReportDetails.test.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/Utilities/Router.test.js
src/Utilities/__snapshots__/Router.test.js.snap

This address all errors mentioned in RHICOMPL-1172, except ```Failed prop type: Invalid prop `filterConfig.items[2].filterValues` supplied to `PrimaryToolbar` ```.

RHICOMPL-1172 - Test fixes

---

src/PresentationalComponents/OperatingSystemBadge/OperatingSystemBadge.js
src/PresentationalComponents/PoliciesTable/PoliciesTable.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportsTable/Cells.js
src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap
src/PresentationalComponents/index.js

fix(PoliciesTable): RHICOMPL-1274 - Use common OSBadge

---

babel.config.js
config/dev.webpack.config.js
package-lock.json
package.json

- transform FEC imports to use ESM build
- update webpack config and disable hashes in dev build
cc @bastilian

Improve build performance

---

.github/pull_request_template.md

feat(FedRamp): RHICOMPL-1265 add secure coding checklist

---

src/__fixtures__/systems.js
src/store/Reducers/__snapshots__/SystemStore.test.js.snap

chore(FedRamp): RHICOMPL-1223 Remove any PII

---

src/SmartComponents/SystemsTable/InventoryTable.js

fix(Cyndi): RHICOMPL-1400 update systems shown message

---

src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/ReportDetails/ReportDetails.js
src/constants.js

feat(InventoryTable): RHICOMPL-1226 - Enable new Inventory as default

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js

Cyndi provides all inventory systems with the compliance systems API.
We'd like to only show compliance systems, those with compliance reports
or associated to a compliance policy.

feat(ComplianceSystems): RHICOMPL-1396 default filter

---

package-lock.json
package.json
src/App.js

- update webpack config to use a stable release
- removes effect that causes infinite loops
cc @bastilian @karelhala

Fix infinite loop

---

src/App.scss
src/SmartComponents/Reports/Reports.js

Drops external policy deprecation banner.
Reverts 96bfddbb0ba7004733649ade04e57b0ae5810875

refactor(Reports): RHICOMPL-1298 drop deprecation banner

---

src/SmartComponents/EditPolicy/EditPolicy.js

https://github.com/RedHatInsights/compliance-frontend/pull/977/files Introduced this issue.

fix(EditPolicy): Watching these dependencies causes unwanted rerender

---

README.md
sonar-project.properties

feat(sonarqube): RHICOMPL-1260 add initial sonar config

---

src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js

Both business objective (new) and compliance threshold tooltips are
updated based on the mocks:
https://marvelapp.com/prototype/6bdbgig/screen/76759096

feat(PolicyDetails): RHICOMPL-960 Update tooltips

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js

Show the OS information for systems when creating a new policy.

feat(CreatePolicy): RHICOMPL-1453 Show OS info

---

src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/EditPolicy.test.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap

When editing a policy, only show systems with a corresponding OS major
version to the policy benchmark

feat(EditPolicy): RHICOMPL-1421 Filter systems by OS major

---

src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/constants.js

fix(ReportDetails): RHICOMPL-1460 -  Request OS version for remediations

---

package-lock.json
package.json
src/SmartComponents/CreatePolicy/EditPolicyRules.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyRules.test.js.snap
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/PolicyRulesTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap

Requires https://github.com/RedHatInsights/frontend-components/pull/1022

fix(compliance): RHICOMPL-1488 Rules table header

---

src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/CreatePolicy/validate.js
src/SmartComponents/CreatePolicy/validate.test.js

Swaps Rules and Systems steps, to start with Systems first.
Updated wording on the Systems steps according to mocks.

feat(CreatePolicy): RHICOMPL-1354 reorder steps 

---

src/PresentationalComponents/TabbedRules/TabbedRules.js
src/PresentationalComponents/TabbedRules/TabbedRules.test.js
src/PresentationalComponents/TabbedRules/__snapshots__/TabbedRules.test.js.snap
src/PresentationalComponents/index.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap

Created presentational component `TabbedRules` out of `PolicyMultiversionRules`

refactor: RHICOMPL-1355 presentational TabbedRules from PolicyMultiversionRules

---

src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap

Basically the same as https://github.com/RedHatInsights/compliance-frontend/pull/1048, just on a different page

fix(Reports): RHICOMPL-1530 changed ssg version field key

---

src/App.scss
src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap

feat(DeletePolicy): RHICOMPL-1452 warns users of deleted reports

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap

feat(CreatePolicy): RHICOMPL-1545 do not display SSG version

---

src/PresentationalComponents/TabbedRules/OsVersionText.js
src/PresentationalComponents/TabbedRules/ProfileTabContent.js
src/PresentationalComponents/TabbedRules/TabbedRules.js
src/PresentationalComponents/TabbedRules/TabbedRules.test.js
src/PresentationalComponents/TabbedRules/__snapshots__/TabbedRules.test.js.snap
src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/CreatePolicy/EditPolicyRules.js
src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/EditPolicy.test.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
src/Utilities/graphql/mutations.js
src/Utilities/hooks/api/useCollection.js
src/Utilities/hooks/api/useCollection.test.js

Continuation of https://github.com/RedHatInsights/compliance-frontend/pull/1075. Very WIP.

Editable tabbed rules

---

src/SmartComponents/CreatePolicy/EditPolicyDetails.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.test.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap

Rebase COMP-E-133 with master

---

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap

Updated the review page in the create policy wizard accordin the 133 mockup. It's displaying the number of systems for each OS minor version separately, sorted in a descending order.

feature(CreatePolicy): RHICOMPL-1552 update review page with OSvers

---

package-lock.json
package.json
src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap

Cherry pick master

---

src/SmartComponents/CreatePolicy/FinishedCreatePolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/FinishedCreatePolicy.test.js.snap

fix(FinishedCreatePolicy test): RHICOMPL-1620

---

package-lock.json
package.json
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportCardGrid/__snapshots__/ResportsCardGrid.test.js.snap
src/PresentationalComponents/ReportDetailsDescription/__snapshots__/ReportDetailsDescription.test.js.snap
src/PresentationalComponents/ReportsTable/__snapshots__/Filters.test.js.snap
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/PresentationalComponents/TabbedRules/ProfileTabContent.js
src/PresentationalComponents/TabbedRules/__snapshots__/TabbedRules.test.js.snap
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.test.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
src/__fixtures__/policies.js
src/store/Reducers/SystemStore.js
src/store/Reducers/SystemStore.test.js

Refactors the Profile Details rules tab and adds an "Edit rules" button that opens the modal on the right tab.

feat(PolicyDetails): RHICOMPL-1532 edit rules button 

---

src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
src/constants.js

feat(multiversionTabs): RHICOMPL-1226 enabled by default

---

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
src/store/Reducers/SystemStore.js
src/store/Reducers/SystemStore.test.js

fix: RHICOMPL-1622 rules tab order: asc -> desc

---

package-lock.json
package.json

fix(deps): RHICOMPL-744 pulling-in emptystate component changes

---

src/SmartComponents/EditPolicy/EditPolicyRulesTab.js

Scenario: Existing policy with some tabs but no systems
Before: Rules tab was empty
Now: Rules tab shows the existing rule set with 0 systems

fix(EditPolicy): RHICOMPL-1623 With no systems, with profiles

---

src/PresentationalComponents/TabbedRules/ProfileTabContent.js

This enables the remediationAvailableFilter on rules tables within the
create policy wizard, edit policy modal, and policy details view.

fix(TabbedRules): RHICOMPL-1549 enable remediationAvailableFilter

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js

When selecting a different OS major version, the selected systems should be cleared from the state.

fix(PolicyCreate): RHICOMPL-1632 clear systems upon OS major change

---

src/SmartComponents/EditPolicy/EditPolicy.js

The rationale is that even-though the `SELECT_ENTITIES` is called to
select the systems, the `selectedEntities` variable stays undefined.
This probably due to the lack of `state.entities.selectedEntities`
within the redux, which is probably filled out only when the Systems are
drawn.

fix(PolicyEdit): RHICOMPL-1650 empty policy rules on initial load

---

src/SmartComponents/EditPolicy/EditPolicy.js

Following up on some outstanding comments on https://github.com/RedHatInsights/compliance-frontend/pull/1110

refactor(EditPolicy): RHICOMPL-1356 PR follow up

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js

There was still a way to have the systems selected after an OS major change, see the Jira for the details.

fix(PolicyCreate): RHICOMPL-1636 empty systems in form state

---

src/PresentationalComponents/ProfileTypeSelect/ProfileTypeSelect.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap

Adjusting the first step of the wizard according the mockup.

fix(PolicyCreate): RHICOMPL-1654 updated empty state for OS major

---

src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap

fix(PolicySystemsTab): RHICOMPL-1659 add the OS version column

---

src/PresentationalComponents/ErrorPage/ErrorPage.js
src/PresentationalComponents/ErrorPage/__snapshots__/ErrorPage.test.js.snap

fix(ErrorPage): RHICOMPL-1660 change error icon color to red

---

src/App.scss
src/PresentationalComponents/TabbedRules/ProfileTabContent.js
src/PresentationalComponents/TabbedRules/TabbedRules.js
src/PresentationalComponents/TabbedRules/__snapshots__/TabbedRules.test.js.snap
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js

See https://www.patternfly.org/v4/guidelines/spacers/

feat(CreatePolicy): RHICOMPL-1671 Update text and formatting

---

package-lock.json
package.json

Pulls in https://github.com/RedHatInsights/frontend-components/pull/1068

chore(deps): RHICOMPL-1658 update fc inventory-compliance

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js

fix(CreatePolicy): RHICOMPL-1674 bold for RHEL version

---

src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/EditPolicy/usePolicy.js

* Clear the "This usually takes a minute or two." message after the
policy is created.
* Awaits assignment of all rules, sequentially (can be improved).
* Updates the progress.
* Adds error handling.
* Any errors on the Edit modal are absorbed and not shown (needs a general improvement).
Note for reviewers: changes are separated by commits.
Successful creation:
Error during the policy creation:
Progress (with deliberate slowness):
https://user-images.githubusercontent.com/7695766/114585652-2973c080-9c84-11eb-95d8-444842fa6cfd.mp4

fix(CreatePolicy): RHICOMPL-1676 finish, progress and error reporting

---

src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/CreatePolicy/validate.js

feat(CreatePolicy): RHICOMPL-1630 Empty state for missing policy type

---

src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap

Clicking on the "I understand this will delete..." label did not checked the checkbox -- missing id.

fix(DeletePolicy): check checkbox via label

---

src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap

fix(EditPolicy): RHICOMPL-1637 adjusted modal dimensions

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap

fix(PolicyCreate): RHICOMPL-1661 add missing tooltip

---

package-lock.json
package.json
src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap
src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
src/SmartComponents/EditPolicy/EditPolicySystemsTab.test.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
src/SmartComponents/SystemsTable/constants.js
src/SmartComponents/SystemsTable/hooks.js
src/Utilities/hooks/api/useCollection.js
src/__fixtures__/benchmarks_rules.js
src/constants.js

This adds a filter to the policy wizard and edit for the OS minor versions grouped by major version:
**Note:** This requires https://github.com/RedHatInsights/frontend-components/pull/1073 to support the grouped filter

feat(InventoryTable): Implement OS Major & Minor version filter

---

package-lock.json
package.json
src/App.scss

Fix to be used with RedHatInsights/frontend-components#1075.
This would likely need a global PF fix.
Here is it in action:

fix(Modal): RHICOMPL-1652 fix sticky headers within a modal

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap

refactor: Move components out of parent function body

---

src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap

fix(EditPolicy): RHICOMPL-1678 RHICOMPL-1679 cancel button link

---

src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js

Production does not seems to like the combination of parenthesis and
numbers.  It replaces them with quotes which are acceptable by scoped
search.

fix(benchmarks): RHICOMPL-1715 requests forbidden in prod

---

src/PresentationalComponents/OperatingSystemBadge/OperatingSystemsBadge.test.js
src/PresentationalComponents/OperatingSystemBadge/__snapshots__/OperatingSystemsBadge.test.js.snap
src/SmartComponents/CreatePolicy/EditPolicyDetails.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.test.js
src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/CreatePolicy/FinishedCreatePolicy.test.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap
src/SmartComponents/CreatePolicy/__snapshots__/FinishedCreatePolicy.test.js.snap
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.test.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyRulesTab.test.js.snap

A few low hanging fruits to slightly increase our coverage.

chore: Increase Test coverage

---

src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/EditPolicy.test.js
src/SmartComponents/EditPolicy/EditPolicyForm.js
src/SmartComponents/EditPolicy/EditPolicyForm.test.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap

Adds error handling to Edit Policy and refactoring.

fix(EditPolicy): RHICOMPL-1696 add error handling 

---

config/dev.webpack.config.js
src/bootstrap-dev.js

build: enable logger in development

---

src/SmartComponents/EditPolicy/EditPolicyRulesTab.js

Fixes showing just the error state if there is some, and hides other
already loaded data.

fix(EditPolicy): RHICOMPL-1727 error state

---

src/SmartComponents/PolicyDetails/PolicyRulesTab.js

fix(PolicyDetails): minor typo s/rule/rules/

---

src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetails.test.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap

Adds the OS minor version filter to the report details: 

fix(ReportDetails): RHICOMPL-1476 - Add OS minor version filter

---

src/SmartComponents/PolicyDetails/PolicyRulesTab.js

chore(PolicyRulesTab): RHICOMPL-1758 - Update rule editing alert message

---

src/PresentationalComponents/PolicyPopover/PolicyPopover.js
src/PresentationalComponents/PolicyPopover/__snapshots__/PolicyPopover.test.js.snap

Policies are no longer SSG version specific.

fix(Reports): RHICOMPL-1757 remove policy SSG version

---

config/spandx.config.js

This help (at least a little) with the "Error loading component" issues.

feat(spandx): Disable goodguy by default

---

src/Mutations/hooks/usePolicyMutation.js
src/Mutations/hooks/usePolicyMutation.test.js

fix(usePolicy): RHICOMPL-1786 reseting Business Unit

---

src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js

fix(CreatePolicy): RHICOMPL-1787 show SSG version in Rules step

---

src/PresentationalComponents/PolicyBusinessObjectiveTooltip/PolicyBusinessObjectiveTooltip.js
src/PresentationalComponents/PolicyBusinessObjectiveTooltip/PolicyBusinessObjectiveTooltip.test.js
src/PresentationalComponents/PolicyBusinessObjectiveTooltip/__snapshots__/PolicyBusinessObjectiveTooltip.test.js.snap
src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js
src/PresentationalComponents/PolicyThresholdTooltip/PolicyThresholdTooltip.js
src/PresentationalComponents/PolicyThresholdTooltip/PolicyThresholdTooltip.test.js
src/PresentationalComponents/PolicyThresholdTooltip/__snapshots__/PolicyThresholdTooltip.test.js.snap
src/PresentationalComponents/ProfileThresholdField/ProfileThresholdField.js
src/PresentationalComponents/ProfileThresholdField/ProfileThresholdField.test.js
src/PresentationalComponents/ProfileThresholdField/__snapshots__/ProfileThresholdField.test.js.snap
src/PresentationalComponents/index.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap
src/SmartComponents/EditPolicy/EditPolicyDetailsTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyDetailsTab.test.js.snap

Create new tooltip components for business objective and compliance threshold; use the new components in all three places, create policy wizard, edit policy wizard, and policy details.
This addresses RHICOMPL-1701 and RHICOMPL-1804.

feat(EditPolicy): RHICOMPL-1701 Add BO and threshold tooltips

---

README.md

chore(README): RHICOMPL-1619 added codeclimate badge

---

package-lock.json
package.json
src/PresentationalComponents/SupportedSSGVersionsLink/__snapshots__/SupportedSSGVersionsLink.test.js.snap

chore(deps): RHICOMPL-1844 bump frontend-components-inventory-compliance

---

package-lock.json
package.json

chore(deps): RHICOMPL-744 bump frontend-components-inventory-compliance

---

src/SmartComponents/SystemsTable/Cells.js
src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/hooks.js
src/Utilities/__snapshots__/ruleHelpers.test.js.snap
src/Utilities/ruleHelpers.js
src/Utilities/ruleHelpers.test.js

First this fixes the data that are passed to `selectedSystems` state variable. Previously it appended tabe row data instead of the original entity data.
Mainly this fixes Remediation button on Systems Table (e.g. on Report Details page). This is done by passing preprocessed data (esp. `supported`) from `selectedSystems` into the remediation button.

fix(Inventory): RHICOMPL-1839 remediation of supported systems 

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js

after the Rules step was already drawn.
Fixes:
```
TypeError: prevSelection is null
additionalSelection ruleSelection.js:18
profilesWithRulesToSelection ruleSelection.js:17
EditPolicyProfilesRules EditPolicyProfilesRules.js:154
React 6
react_devtools_backend.js:2560:23
```

fix(CreatePolicy): RHICOMPL-1864 crash on type re-selection

---

src/PresentationalComponents/PoliciesTable/PoliciesTable.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js
src/PresentationalComponents/ReportsEmptyState/ReportsEmptyState.js
src/PresentationalComponents/ReportsEmptyState/__snapshots__/ReportsEmptyState.test.js.snap
src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/PolicyDetails/EditRulesButtonToolbarItem.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/PolicyRulesTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap

Add OUIDs to components #2

---

src/PresentationalComponents/ProfileTypeSelect/ProfileTypeSelect.js
src/PresentationalComponents/ProfileTypeSelect/ProfileTypeSelect.test.js
src/PresentationalComponents/ProfileTypeSelect/__snapshots__/ProfileTypeSelect.test.js.snap

feat(ProfileSelect): RHICOMPL-1310 - Set eye-catching color for "In use" Label

---

package.json

fix(coverage): Exclude fixtures in subdirectories

---

src/PresentationalComponents/ComplianceScore/ComplianceScore.js
src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap
src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js
src/PresentationalComponents/UnsupportedSSGVersion/__snapshots__/UnsupportedSSGVersion.test.js.snap

(With mocked data) Before:
After:

fix(ReportDetails): Correct icon alignments

---

src/PresentationalComponents/ComplianceScore/ComplianceScore.js
src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/Columns.js
src/SmartComponents/SystemsTable/__snapshots__/Cells.test.js.snap

Before:
https://user-images.githubusercontent.com/7757/120731730-7c2f6300-c4e4-11eb-8602-01d2cced75c5.mp4
After:
https://user-images.githubusercontent.com/7757/120731755-881b2500-c4e4-11eb-933a-b646f7904d9b.mp4

fix(SystemsTable): RHICOMPL-1799 - Improve responsiveness

---

src/Utilities/hooks/useFilterConfig.js

The filter string should only be attempted if no array is set.

fix(FilterConfig): Only call buildFilterString without array

---

src/App.scss

The gap this was adjusting is not needed anymore.
Styles in Patternfly have been fixed.
Before:
After:

fix(RulesTable): Remove patternfly style adjustments

---

src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/EditPolicy/EditPolicy.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/hooks.test.js.snap
src/SmartComponents/EditPolicy/hooks.js
src/SmartComponents/EditPolicy/hooks.test.js
src/Utilities/Dispatcher.js

This adds notifications for creating and updating policies:

fix(Policies): RHICOMPL-1818- Add notifications for policy actions

---

src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterBuilder.test.js
src/Utilities/hooks/useTableTools/FilterConfigBuilder/__snapshots__/FilterBuilder.test.js.snap
src/constants.js

- Adjust ranges to include all float values on boundaries
- Add parenthesis for or'd score filter terms
- Add some snapshot tests covering the filter config constant

fix: RHICOMPL-2095 Correct compliance score filter

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/RulesTable.test.js
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/PolicyRulesTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap

Fixes showing "Edit Rules" button on Policy details page, Rules tab.

fix(RulesTable): RHICOMPL-2042 custom dedicatedAction Edit Rules

---

src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
src/SmartComponents/SystemsTable/constants.js
src/SmartComponents/SystemsTable/hooks.js
src/SmartComponents/SystemsTable/hooks.test.js
src/Utilities/hooks/useTableTools/__snapshots__/useBulkSelect.test.js.snap
src/Utilities/hooks/useTableTools/useBulkSelect.js
src/Utilities/hooks/useTableTools/useBulkSelect.test.js
src/Utilities/hooks/useTableTools/useTableTools.js
src/store/Reducers/SystemStore.js

**Note:**
This is the best we can do for now and there is still a chance for odd behaviour. I tried a few approaches, but until we are able to make a selection without having to load and/or process additional data for the select callbacks this will be hard to resolve. We need additional data for some callbacks, for example to validate/make the rule selection. 
For “Select All” it will in most cases always need to query more information and stall the selection process until the requests are all done and it can pass on the full system objects to the callback.
For now I believe this is fine to introduce a “Select All” and create a follow up task to start and look into optimising it, step by step.
The first step would be to make the callbacks not depend on more information than the ID and …

fix(SystemsTable): RHICOMPL-734 - Use proper bulk select

---

src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/constants.js

fix(GraphQL): RHICOMPL-2100 include tags in the systems GQL

---

.env.example

See https://github.com/RedHatInsights/insights-proxy/pull/44

devel: Add USE_CLOUD to the .env example

---

src/SmartComponents/PolicyDetails/PolicyRulesTab.js

This fixes issues the policy details rules tab when the policy has no system and setting the minor OS version failed.

fix(PolicyRulesTab): RHICOMPL-2042 - Fix dedicated action for legacy rules tab

---

.env.example
README.md
config/dev.webpack.config.js
config/devserver.config.js
package-lock.json
package.json

Just a cleanup of the webpack (useProxy) configuration to also enable our `.env` for it as well.

chore: Cleanup webpack configuration

---

package-lock.json
package.json
src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.test.js
src/PresentationalComponents/ComplianceRemediationButton/__snapshots__/ComplianceRemediationButton.test.js.snap

This adds an OUIA id for the compliance button to allow target it better in tests.
Note: This requires https://github.com/RedHatInsights/frontend-components/pull/1241

feat(RemediationsButton): RHICOMPL-2052 - Pass OUIA id for button

---

src/SmartComponents/Reports/Reports.js

fix(Reports): RHICOMPL-2111 Do not request external policies

---

src/SmartComponents/SystemsTable/hooks.js

This adds an onError callback for fetching systems and sets the notification when failing while selecting.

fix(SystemsTable): RHICOMPL-2098 - Handle errors when selecting

---

config/spandx.config.js

:scissors: :toilet: :fire: :penguin: :tada: :panda_face:

fix(proxy): RHICOMPL-2166 clean up legacy spandx routes

---

src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js

fix(Remediate): RHICOMPL-2161 s/content_profile_// in issue_id

---

src/PresentationalComponents/PoliciesTable/PoliciesTable.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap

Enables sticky headers for all tables:
https://user-images.githubusercontent.com/7757/129997058-7ee672f8-6af4-49fe-9502-0ba90c123508.mp4

feat(Tables): RHICOMPL-1628 - Enable sticky headers for all

---

package-lock.json
package.json
src/Utilities/hooks/useTableTools/Components/__snapshots__/TableToolsTable.test.js.snap

https://github.com/RedHatInsights/compliance-frontend/pull/1326 with update snapshot.

chore: bump @redhat-cloud-services/frontend-components from 3.3.9 to 3.3.13

---

src/Mutations/hooks/usePolicy.js
src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeleteReport/DeleteReport.js
src/SmartComponents/EditPolicy/hooks.js
src/SmartComponents/EditPolicy/hooks.test.js
src/SmartComponents/SystemsTable/hooks.js
src/SmartComponents/SystemsTable/hooks.test.js

fix(Notifications): RHICOMPL-1877 - Add missing & update existing notifications

---

README.md

chore(readme): Update to mention useProxy and minor corecctions

---

src/SmartComponents/SystemDetails/ComplianceDetail.js
src/Utilities/hooks/useTableTools/useTableSort.js
src/Utilities/hooks/useTableTools/useTableSort.test.js

This fixes the initial sorting and allows sorting to work correctly again.

fix(SystemsDetails): RHICOMPL-2181 - Set initial sortBy correctly

---

src/Utilities/hooks/useTableTools/__snapshots__/useExpandable.test.js.snap
src/Utilities/hooks/useTableTools/useExpandable.js

fix(useExpandable): RHICOMPL-1555 - Set fullwidth as default

---

package-lock.json
package.json
src/Utilities/helpers.js
src/Utilities/helpers.test.js

Tabs in policies are now sorted naturally based on OS version

fix(PoliciesOSTabs): RHICOMPL-1834 OS version tabs sorting

---

src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/constants.js
src/SmartComponents/SystemsTable/hooks.js

This fixes issues with selecting and exporting when filtered by tags as described in RHICOMPL-2098.

fix(SystemsTable): RHICOMPL-2101 - Pass tags to export & select requests

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/Columns.js
src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
src/SmartComponents/SystemsTable/constants.js
src/SmartComponents/SystemsTable/hooks.js

This makes use of the recently added timestamps to add the "Last seen" column and removes the details link on the "Systems" page.

feat(SystemsTable): RHICOMPL-921 - Add "Last seen" inventory column

---

src/PresentationalComponents/SupportedSSGVersionsLink/SupportedSSGVersionsLink.js
src/PresentationalComponents/SupportedSSGVersionsLink/__snapshots__/SupportedSSGVersionsLink.test.js.snap
src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.js
src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.test.js
src/PresentationalComponents/SystemPolicyCard/UnsupportedSSGVersion.js
src/PresentationalComponents/SystemPolicyCard/__snapshots__/SystemPolicyCard.test.js.snap
src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js
src/constants.js

This fixes issues with unsupported policies and adds a test for it as well. 

fix(SystemPolicyCard): RHICOMPL-2215 - Restore UsupportedSSGVersion component

---

src/SmartComponents/SystemDetails/ComplianceDetail.js

Allow custom router in compliance system detail

---

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js
src/PresentationalComponents/ComplianceEmptyState/__snapshots__/ComplianceEmptyState.test.js.snap

fix(EmptyStateView): RHICOMPL-2300 - Fix external link

---

src/PresentationalComponents/ProfileTypeSelect/ProfileTypeSelect.js
src/PresentationalComponents/ProfileTypeSelect/__snapshots__/ProfileTypeSelect.test.js.snap
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap

wrapped profile selection in Radio button to enable selection when the title is clicked as well

fix(ProfileTypeSelect): RHICOMPL-1106 radio button title click selection

---

package-lock.json

`npm install` kept adding this line for me :thinking:

chore(lockfile): Add package name into the lockfile

---

src/SmartComponents/SystemsTable/constants.js

The wizard requires OS major and minor version to function.
This extends the minimal query which is used for systems not visible to provide this information when they are selected.

fix(SystemsTable): RHICOMPL-2322 - Query more information for min. systems

---

src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportDetailsDescription/__snapshots__/ReportDetailsDescription.test.js.snap
src/PresentationalComponents/ReportsTable/__snapshots__/Filters.test.js.snap
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/PresentationalComponents/TabSwitcher/TabSwitcher.js
src/PresentationalComponents/TabbedRules/TabbedRules.js
src/PresentationalComponents/TabbedRules/__snapshots__/TabbedRules.test.js.snap
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/EditPolicy/EditPolicyForm.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyRulesTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
src/__fixtures__/policies.js

feat(EditRules): RHICOMPL-2364 - OUIA IDs to EditRulesViews

---

src/App.scss

Fixing the vertical and horizontal alignment of the tags icon on the Systems table.

fix: RHICOMPL-2171 - Align tags icon on system table row

---

package.json
src/PresentationalComponents/ReportsTable/ReportsTable.test.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap

https://github.com/RedHatInsights/compliance-frontend/pull/1430 introduced outdated snapshots and tests due to enabling the PDF feature.

chore(tests): Update snapshots and failing tests

---

src/PresentationalComponents/RulesTable/Columns.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyRulesTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
src/Utilities/hooks/useTableTools/useExport.js
src/Utilities/hooks/useTableTools/useTableTools.js

feat(TableTools): RHICOMPL-2407 - Integrate useExport hook

---

package-lock.json
package.json

chore(deps): Upgrade jest to v27

---

src/SmartComponents/SystemsTable/InventoryTable.js
src/SmartComponents/SystemsTable/InventoryTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
src/SmartComponents/SystemsTable/hooks.js
src/constants.js

chore(SystemsTable): RHICOMPL-2411 - Remove and cleanup "tags" feature flag

---

src/PresentationalComponents/ReportsTable/Columns.js
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/Utilities/hooks/useTableTools/useExport.js

Adds export to the reports table.
It also inctroduces changes to the `useExportWithItems` hook in order to allow custom columns for the export. 
*How to test?*
1. Visit the reports page
2. Export CSV/JSON. \o/ tada!

feat(ReportsTable): RHICOMPL-1662 - Enable export

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/SystemsTable.test.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/SmartComponents/index.js

Long overdue renaming, to reduce the FEC vs. compliance "Inventory Table" confusion.

chore(SystemsTable): Rename InventoryTable component

---

src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/CreatePolicy/CreatePolicy.test.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap

fix(CreatePolicy): RHICOMPL-2332 - Reset form when canceling/closing

---

src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/SmartComponents/SystemsTable/hooks.js
src/Utilities/hooks/useTableTools/useExport.js
src/Utilities/hooks/useTableTools/useExport.test.js
src/constants.js

This moves the notifications we already had for the systems table export to all tables.
1. Open any page containing a systems, rules or reports table and try to export.
2. Verify that there is a notification for a pending, succeeded and failed export.

feat(Tables): RHICOMPL-2431 - Add notifications to every export

---

src/SmartComponents/CompliancePolicies/CompliancePolicies.js
src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap

fix(SCAP Policies): RHICOMPL-2449 Fix Create new Policy OUIA ID

---

src/PresentationalComponents/LoadingPoliciesTable/__snapshots__/LoadingPoliciesTable.test.js.snap
src/PresentationalComponents/PoliciesTable/Columns.js
src/PresentationalComponents/PoliciesTable/PoliciesTable.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap

Adds export functions to the policies table columns to enable export.
1. Visit the SCAP Policies page
2. Export the full set of polices
3. Add a random filter to limit the set of polices and export
4. Select specific policies and export

feat(PoliciesTable): RHICOMPL-2336 - Enable CSV/JSON export

---

src/PresentationalComponents/ReportsTable/Columns.js
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/constants.js

This reverts the changes for the PDF feature flag and disables it by default.

chore(Reports): RHICOMPL-2456 - Revert "Remove PDF feature flag" 

---

src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/PresentationalComponents/RemediationCell/RemediationCell.js
src/PresentationalComponents/RemediationCell/RemediationCell.test.js
src/PresentationalComponents/RemediationCell/__snapshots__/RemediationCell.test.js.snap
src/PresentationalComponents/RulesTable/Cells.js
src/PresentationalComponents/RulesTable/Columns.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyRulesTab.test.js.snap
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/PolicyRulesTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap

This changes the "Ansible" column to be named "Remediation" and more user friendly column values.
Before:
After: 

feat(RulesTable): RHICOMPL-2083 - Update Ansible column to "Remediate"

---

src/PresentationalComponents/RulesTable/RulesTable.js

This fixes issues selecting rules with reports on systems that have multiple policies with overlapping rules:
*Before:*
https://user-images.githubusercontent.com/7757/141508764-9eb724cc-68b0-4b04-a39f-d71e5be08076.mp4
*After:*
https://user-images.githubusercontent.com/7757/141508800-17eb527d-1a04-4fb1-9449-57297ece80f6.mp4

fix(RulesTable): RHICOMPL-2469 - Prefix policy id to identify rules

---

src/PresentationalComponents/RulesTable/Cells.js
src/PresentationalComponents/RulesTable/Columns.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicyRulesTab.test.js.snap
src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/PolicyRulesTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap

fix(RulesTable): RHICOMPL-2083 Fix Remediation column typo

---

src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/constants.js

feat: RHICOMPL-2460 - Enable PDF reports by default

---

src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap

This reduces the padding at the bottom of the inventory details.
Before: 
After:
(The additional 5px are from the line-height of the last line)

fix(SystemDetails): RHICOMPL-1824 - Remove unnecessary break

---

src/SmartComponents/SystemDetails/compliance.scss

fix(SytemDetails): RHICOMPL-1825 - Properly style compliant state

---

src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap

feat(Policy details): OUIA ID rules tabs

---

src/SmartComponents/SystemDetails/ComplianceDetail.js
src/SmartComponents/SystemDetails/EmptyState.js
src/SmartComponents/SystemDetails/NoPoliciesState.js
src/SmartComponents/SystemDetails/NoPoliciesState.test.js
src/SmartComponents/SystemDetails/NoReportsState.js
src/SmartComponents/SystemDetails/NoReportsState.test.js
src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemDetails/__snapshots__/NoPoliciesState.test.js.snap
src/SmartComponents/SystemDetails/__snapshots__/NoReportsState.test.js.snap
src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap

This changes the empty state in the "Compliance" tab in the **Inventory** application to show the platform "NotConnected" component. The behaviour for the empty state in the **Compliance** applications remains the same and will show if the system is not assigned to any policy or if it is assigned, but not reporting.
**Before:**
**After:**
1. Register a system and/via upload(ing) a report
2. Verify on the SystemDetails in Compliance and Inventory that the policy and rule results are properly shown
3. Delete the report for the system
4. Verify on the SystemDetails in Compliance and Inventory that it shows the "No report" state
5. Remove the system from the policy
6. ~Verify on the SystemDetails in Compliance that it show the "No policy assigned" state~
7. Verify in the …

feat(SystemsDetails): RHICOMPL-1916 - Show "NotConnected" when no data available

---

src/PresentationalComponents/RulesTable/Filters.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/SystemPolicyCard/SystemPolicyCard.js
src/PresentationalComponents/SystemPolicyCard/UnsupportedSSGVersion.js
src/PresentationalComponents/SystemPolicyCard/__snapshots__/SystemPolicyCard.test.js.snap
src/PresentationalComponents/SystemPolicyCards/SystemPolicyCards.js
src/PresentationalComponents/SystemPolicyCards/__snapshots__/SystemPolicyCards.test.js.snap
src/SmartComponents/SystemDetails/ComplianceDetail.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/Utilities/hooks/useTableTools/Components/__snapshots__/TableToolsTable.test.js.snap
src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterConfigBuilder.js
src/Utilities/hooks/useTableTools/FilterConfigBuilder/__snapshots__/FilterConfigBuilder.test.js.snap
src/Utilities/hooks/useTableTools/__snapshots__/useFilterConfig.test.js.snap
src/Utilities/hooks/useTableTools/helper.js
src/Utilities/hooks/useTableTools/useFilterConfig.js

https://user-images.githubusercontent.com/7757/145012668-957d020c-577f-47cf-b4d6-6973d9efcb6d.mp4

feat(ComplianceDetails): RHICOMPL-1136 - Implement policy card filtering

---

src/Utilities/hooks/useTableTools/useTableTools.js

Fix issues with sorting on rules tables that use the "selected filter", like the create policy wizard and the edit policy modal.

fix(TableTools): RHICOMPL-2592 - Don't filter items for sorting

---

src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
src/SmartComponents/SystemDetails/ComplianceDetail.js

This fixes issues with loosing the selection when filtering by policy card on the SystemDetails page.

fix(RulesTable): RHICOMPL-2596 - Preserve selection for remediations

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/Columns.js

This enables sorting for the remaining columns we currently can sort systems by.

feat(SystemsTable): RHICOMPL-1670 - Enable sorting for supported columns

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/SystemsTable/Columns.js

change(Systems Table): RHICOMPL-2164 move OS into separate column

---

src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/SmartComponents/SystemsTable/hooks.js

fix(SystemsTable): RHICOMPL-2608 - Disable default OS inventory filter

---

src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js

fix(ReportDetails): RHICOMPL-2548 - Use host hosts with results to calculate non-compliant

---

src/PresentationalComponents/RulesTable/Filters.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/RulesTable.test.js
src/PresentationalComponents/TabbedRules/ProfileTabContent.js
src/SmartComponents/SystemDetails/ComplianceDetail.js

fix(RulesTable): RHICOMPL-1816 - Fix filter by Ansible remediation

---

src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js
src/PresentationalComponents/UnsupportedSSGVersion/__snapshots__/UnsupportedSSGVersion.test.js.snap

fix(ReportDetails): RHICOMPL-1797 - Fix tooltip icon color

---

src/PresentationalComponents/InUseProfileLabel/InUseProfileLabel.js
src/PresentationalComponents/ProfileTypeSelect/ProfileTypeSelect.js
src/PresentationalComponents/RulesTable/RuleDetailsRow.js
src/PresentationalComponents/RulesTable/RuleDetailsRow.test.js
src/PresentationalComponents/index.js
src/SmartComponents/CreatePolicy/Components/PolicyTypeDetailsRow.js
src/SmartComponents/CreatePolicy/Components/PolicyTypeTable.js
src/SmartComponents/CreatePolicy/Components/PolicyTypeTooltip.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.js
src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap
src/Utilities/hooks/useTableTools/__snapshots__/useExpandable.test.js.snap
src/Utilities/hooks/useTableTools/useExpandable.js
src/Utilities/hooks/useTableTools/useTableSort.js

This updates the policy type selection in the "Create Policy" wizard to also include the "Supported minor versions":
**Before:**
**After:**
1. Open the "Create Policy" wizard on the "SCAP Policies" page
2. Verify that it is in fact a table now and it works as other tables
3. Verify that selecting any policy works
4. Verify that it sets the values properly, by completing the wizard

feat(CreatePolicy): RHICOMPL-2590 - Use Table for policy type selection

---

src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js
src/Utilities/hooks/useTableTools/Components/ColumnManager.js

fix(ColumnManagerModal): Add missing OUIA IDs 

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/Columns.js

This also fixes the last column to not truncate its text.

fix(SystemsTable): Fix column prop handling for inventory columns

---

src/SmartComponents/CreatePolicy/EditPolicyDetails.test.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js
src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/__fixtures__/benchmarks_rules.js

This fixes an issue in the policy wizard and 

fix(CreatePolicy): RHICOMPL-2590 - No need to parse JSON anymore

---

.env.example
config/dev.webpack.config.js

Cloud was decommissioned months ago, therefore the environment variable
can be removed

chore(devtools): Remove obsolete environment variable

---

src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
src/SmartComponents/ReportDownload/Components/ExportPDFForm.js
src/SmartComponents/ReportDownload/Components/__snapshots__/ExportPDFForm.test.js.snap
src/SmartComponents/ReportDownload/hooks/__snapshots__/useExportSettings.test.js.snap
src/SmartComponents/ReportDownload/hooks/__snapshots__/useQueryExportData.test.js.snap
src/constants.js

This includes the wording change from the review Jira, as well as enabling systems not reporting by default.

feat(Reports): RHICOMPL-2604 - Enable showing systems not reporting by default

---

.travis.yml
Dockerfile

chore: Bump used node to version 16

---

src/SmartComponents/SystemDetails/ComplianceDetail.js
src/SmartComponents/SystemDetails/EmptyState.js

fix(ComplianceDetails): RHICOMPL-2727 - Show not connected state when no insights_id

---

src/SmartComponents/SystemDetails/ComplianceDetail.js
src/SmartComponents/SystemDetails/EmptyState.js
src/SmartComponents/SystemsTable/hooks.js

Fields in GraphQL need to be queried with camelCase.

fix(SystemDetails): RHICOMPL-2779 - Properly query insightsId

---

src/SmartComponents/CreatePolicy/Components/PolicyTypeTable.js
src/Utilities/hooks/useTableTools/Components/NoResultsTable.js
src/Utilities/hooks/useTableTools/useRadioSelect.js
src/Utilities/hooks/useTableTools/useRadioSelect.test.js
src/Utilities/hooks/useTableTools/useTableTools.js

fix(PolicyTypeTable): RHICOMPL-2784 remove radio from empty table

---

src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemDetails/ComplianceDetail.js
src/SmartComponents/SystemsTable/constants.js

feat(RemediationsButton): RHICOMPL-1735 - Order rules by precedence

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js

When changing the policy, after already assigning systems, it is possible to assign further systems, including systems not matching any version of the policy.
This clears the systems when changing the policy to prevent this issue.

fix(CreatePolicy): RHICOMPL-2829 - Clear systems when changing policy

---

src/PresentationalComponents/NoResultsTable/NoResultsTable.js
src/PresentationalComponents/PoliciesTable/PoliciesTable.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/Utilities/hooks/useTableTools/Components/NoResultsTable.js
src/Utilities/hooks/useTableTools/useActionResolver.js
src/Utilities/hooks/useTableTools/useActionResolver.test.js
src/Utilities/hooks/useTableTools/useTableTools.js

fix(PoliciesTable): RHICOMPL-2784 remove kebab from empty table

---

src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js
src/SmartComponents/ReportDownload/Components/ReportPDF.js
src/SmartComponents/ReportDownload/Components/ReportPDF/ComplianceChart.js
src/SmartComponents/ReportDownload/hooks/__snapshots__/useQueryExportData.test.js.snap
src/SmartComponents/ReportDownload/hooks/useQueryExportData.js
src/Utilities/TextHelper.js

This updates the chart calculations to be based on the total number of hosts:

fix(Reports): RHICOMPL-2854 - Correct percentage calculations

---

src/SmartComponents/ReportDownload/Components/ReportPDF.js

fix(PDFReports): RHICOMPL-2639 - Define OS version

---

package-lock.json

chore(deps): RHICOMPL-2879 update follow-redirects to 1.14.9

---

src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js

fix(ReportDetail): RHICOMPL-2906 remove overall compliance score text

---

.github/CODEOWNERS

dev(CODEOWNERS): set interact team as a global codeowner

---

src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/SmartComponents/SystemsTable/constants.js
src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterBuilder.test.js
src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterConfigBuilder.test.js
src/Utilities/hooks/useTableTools/FilterConfigBuilder/__snapshots__/FilterConfigBuilder.test.js.snap
src/Utilities/hooks/useTableTools/__fixtures__/filters.js
src/constants.js

This implements a SSG version filter for systems on the report details page:

feat(SystemsTable): RHICOMPL-1798 - Add SSG version filter for systems

---

src/PresentationalComponents/PolicyPopover/PolicyPopover.js
src/PresentationalComponents/PolicyPopover/__snapshots__/PolicyPopover.test.js.snap

fix(PolicyPopover): RHICOMPL-1793 fix style for link

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/SystemsTable/constants.js

Created a reduced query for the systems page with only those fields that are necessary. Should make the loading of these systems way faster.

perf(ComplianceSystems): RHICOMPL-2426 query less data on systems page

---

src/Utilities/hooks/useTableTools/useRowsBuilder.js

fix(ReportsTable): RHICOMPL-1795 fix empty reports state

---

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js
src/PresentationalComponents/ComplianceEmptyState/__snapshots__/ComplianceEmptyState.test.js.snap
src/PresentationalComponents/SupportedSSGVersionsLink/__snapshots__/SupportedSSGVersionsLink.test.js.snap
src/constants.js

updates the version in links to docs so they resolve

docs: update urls

---

src/PresentationalComponents/BackgroundLink/BackgroundLink.js
src/PresentationalComponents/BackgroundLink/BackgroundLink.test.js
src/PresentationalComponents/BackgroundLink/__snapshots__/BackgroundLink.test.js.snap
src/PresentationalComponents/BreadcrumbLinkItem/BreadcrumbLinkItem.js
src/PresentationalComponents/LinkWithPermission/LinkWithPermission.js
src/PresentationalComponents/LinkWithPermission/LinkWithPermission.test.js
src/PresentationalComponents/LinkWithPermission/__snapshots__/LinkWithPermission.test.js.snap
src/PresentationalComponents/PoliciesTable/Columns.js
src/PresentationalComponents/PolicyPopover/PolicyPopover.js
src/PresentationalComponents/PolicyPopover/__snapshots__/PolicyPopover.test.js.snap
src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js
src/PresentationalComponents/ReportsTable/Cells.js
src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap
src/PresentationalComponents/WithPermission/WithPermission.js
src/PresentationalComponents/WithPermission/WithPermission.test.js
src/PresentationalComponents/WithPermission/__snapshots__/WithPermission.test.js.snap
src/PresentationalComponents/index.js
src/Routes.js
src/Utilities/Router.js
src/Utilities/__snapshots__/Router.test.js.snap
src/Utilities/hooks/api/utils/ApiClient.test.js
src/constants.js

This reverts commit 4e07fc72628cdccf5802b7471dc91516023e2600.

feat(Router): RHICOMPL-2696 - Add RBAC permissions for routes

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js
src/SmartComponents/SystemsTable/constants.js

* Renamed `GET_SYSTEMS_ONLY` to `GET_SYSTEMS_WITH_POLICIES` 
* Replaced `GET_SYSTEMS` in profile details page with `GET_SYSTEMS_WITH_POLICIES`
* Renamed `GET_SYSTEMS` to `GET_SYSTEMS_WITH_REPORTS`
* Replaced `GET_SYSTEMS_WITHOUT_FAILED_RULES` with `GET_SYSTEMS_WITH_POLICIES`
* Deleted the obsolete `GET_SYSTEMS_WITHOUT_FAILED_RULES`

perf(GraphQL): RHICOMPL-2426 reduce the queries for systems resources

---

src/PresentationalComponents/PoliciesTable/PoliciesTable.js
src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
src/Utilities/hooks/useTableTools/Components/NoResultsTable.js
src/Utilities/hooks/useTableTools/useRowsBuilder.js

Fix for some broken tables introduced in the previous PR (#1648)

fix(EmptyStates): RHICOMPL-1795 fix empty states in tables

---

src/SmartComponents/ReportDownload/Components/ReportPDF/ComplianceChart.js

change(ReportPDF): RHICOMPL-2936 change PDF report chart color scheme

---

src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js
src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js

fix(ThresholdDescription): RHICOMPL-2836 description of threshold

---

src/SmartComponents/ReportDetails/Components/ReportChart.test.js
src/SmartComponents/ReportDetails/Components/__snapshots__/ReportChart.test.js.snap
src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js

fix(ReportDetails): RHICOMPL-2743 conditionally hide unsupported legend

---

src/constants.js

Operating Systems are now sorted in **descending** order
**Before:**
**After:**

fix(constants): RHICOMPL-2749 - OS Filter sorting

---

build_deploy.sh

ci(clowder) RHCLOUD-19387 add build_deploy.sh

---

deployment_template.yaml

fix(Clowder): uncapitalize some values

---

src/SmartComponents/SystemsTable/hooks.js

fix(SystemsTable): RHICOMPL-2429 fix tag filtering by value

---

src/PresentationalComponents/PoliciesTable/hooks/useActionResolvers.js

This will make the row actions in the policies table work properly again.

fix(PoliciesTable): RHICOMPL-2943 - Pass down url properly

---

src/PresentationalComponents/MultiSegmentBar/MultiSegmentBar.js
src/PresentationalComponents/MultiSegmentBar/MultiSegmentBar.test.js
src/PresentationalComponents/MultiSegmentBar/__snapshots__/MultiSegmentBar.test.js.snap
src/PresentationalComponents/ReportStatusBar/ReportStatusBar.js
src/PresentationalComponents/ReportStatusBar/ReportStatusBar.test.js
src/PresentationalComponents/ReportStatusBar/__snapshots__/ReportStatusBar.test.js.snap
src/PresentationalComponents/ReportsTable/Cells.js
src/PresentationalComponents/ReportsTable/ReportsTable.test.js
src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap
src/PresentationalComponents/index.js

Change progress bar in ReportsTable to show unsupported and non reporting systems

feat(ReportsTable): RHICOMPL-2838 show nonreporting systems

---

.github/workflows/sync.yml

This PR aims to achieve two things on push to `master` events:
- Automatically merge changes from `master` to `qa-beta` (only FF)
- Automatically create PR from `master` to `qa-stabe` 

ci(autosync): RHICOMPL-3157 add branch sync and pr creation for stage

---

package-lock.json

chore(deps): RHICOMPL-3156 update terser to its latest version

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js

It is being requested a few lines above already, totally unnecessary.

perf(CreatePolicy): RHICOMPL-3194 do not request os major twice

---

src/SmartComponents/ReportDownload/Components/ReportPDF/SystemsTable.js
src/SmartComponents/ReportDownload/constants.js

The same data is preloaded on a lower level, therefore it's more efficient to query it there. Should reduce the number of allocations significantly.
```
Completed 200 OK in 1483ms (Views: 0.7ms | ActiveRecord: 1264.1ms | Allocations: 151263)
Completed 200 OK in 1421ms (Views: 0.5ms | ActiveRecord: 1255.3ms | Allocations: 71637)
```
Tested by comparing two PDFs from the old and the new codebase and the results were identical.

perf(ReportPDF): RHICOMPL-3214 make querying failed rules more efficient

---

src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap
src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/constants.js

Adjusting the queries for https://github.com/RedHatInsights/compliance-backend/pull/1437 to improve performance. These two should be merged together.

perf(GQL): RHICOMPL-3242 request tags and osVersions faster

---

deployment_template.yaml

updates the `navItems` field in the CRD to match https://github.com/RedHatInsights/cloud-services-config/blob/ci-beta/chrome/rhel-navigation.json#L102

fix(Clowder): RHCLOUD-20284 update navItems in deploy template

---

src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/Utilities/hooks/useTableTools/FilterConfigBuilder/__snapshots__/FilterBuilder.test.js.snap
src/constants.js

Two new Compliance filters for the Reports table

feat(ReportsTable): new compliance filters

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
src/SmartComponents/CreatePolicy/EditPolicyDetails.js

As we discussed with @bastilian @mkholjuraev and @Fewwy that this is not necessary here anymore.

perf(GQL): drop the complianceThreshold from CreateSCAPPolicy

---

src/SmartComponents/PolicyDetails/EditSystemsButtonToolbarItem.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.test.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
src/SmartComponents/SystemsTable/SystemsTable.js

Added edit systems button
After clicking on it the edit systems window appears

feat(PolicyDetails): Added edit systems button

---

src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js

resolves https://issues.redhat.com/browse/RHICOMPL-2981

fix(useDonutChart): RHICOMPL-2981 - Correct report chart colors

---

src/Utilities/helpers.js

fix(Remediation): RHICOMPL-3303 fix unavailable button

---

src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetails.test.js
src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap

- Revert back changes related to policy type as it's needed

fix(GQL): RHICOMPL-3201 fix GQL queries

---

package.json

This turns around the order of executing the tasks for a CI run, since it can hide test results.

fix(ci): Run linting and build testing after actual tests

---

src/SmartComponents/PolicyDetails/PolicyRulesTab.js

Resolves: https://issues.redhat.com/browse/RHICOMPL-3298.
returns bechmark and rules fields into the GQL of the PolicyDetails component to fix the broken policy rules tab. 

fix(RHICOMPL-3298) return benchmark and rules into PolicyDetail GQL

---

src/Utilities/helpers.js

fix(GraphQL): RHICOMPL-3371 Remove unnecessary lastScanned field

---

src/Mutations/graphql/mutations.js
src/Mutations/hooks/usePolicy.js
src/Mutations/hooks/usePolicy.test.js
src/Mutations/hooks/useTailorProfile.js
src/Mutations/hooks/useTailorProfile.test.js

Should not affect anything, just a semantical change for now.

feat(tailoring): RHICOMPL-3433 swap associateRules to tailorProfile

---

src/Mutations/graphql/mutations.js
src/Mutations/hooks/useAssociateRules.js
src/Mutations/hooks/useAssociateRules.test.js
src/Mutations/hooks/usePolicy.js
src/Mutations/hooks/usePolicy.test.js

This reverts commit 42741e06b9404b1efc079c731c54464dedb7868c.

revert(tailoring): RHICOMPL-3433 swap associateRules to tailorProfile

---

src/Utilities/helpers.js

fix(SystemsTable): RHICOMPL-3469 - Restore OS info for Name column

---

src/App.scss
src/SmartComponents/DeletePolicy/DeletePolicy.js
src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
src/SmartComponents/DeleteReport/DeleteReport.js
src/SmartComponents/DeleteReport/__snapshots__/DeleteReport.test.js.snap

fix(ReportDeleteModal): RHICOMPL-3161 - Add Triangle icon

---

src/PresentationalComponents/RulesTable/Columns.js
src/PresentationalComponents/RulesTable/Filters.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/RulesTable/RulesTable.test.js
src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap

fix(RulesTable): RHICOMPL-3164 - Rename 'passed' filter and column

---

.github/workflows/sync.yml

Updating versions to latest.
Fixes:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. 
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

chore(ci): bump package versions for sync branches

---

src/SmartComponents/CreatePolicy/Components/PolicyTypeTable.js

After fix empty state is shown correctly

fix(PolicyTypeTable): RHICOMPL-3153 - Fix policy type search

---

package-lock.json
package.json
src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
src/PresentationalComponents/ComplianceRemediationButton/RemediationButton.js
src/PresentationalComponents/ComplianceRemediationButton/components/FallBackButton.js
src/PresentationalComponents/ComplianceRemediationButton/constants.js
src/PresentationalComponents/ComplianceRemediationButton/helpers.js
src/PresentationalComponents/ComplianceRemediationButton/hooks.js
src/PresentationalComponents/ComplianceScore/ComplianceScore.js
src/PresentationalComponents/ComplianceScore/ComplianceScore.test.js
src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/ReportDownload/hooks/useQueryExportData.js
src/SmartComponents/SystemsTable/Cells.js
src/SmartComponents/SystemsTable/Columns.js
src/SmartComponents/SystemsTable/SystemsTable.js
src/SmartComponents/SystemsTable/__snapshots__/Cells.test.js.snap
src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
src/SmartComponents/SystemsTable/hooks.js
src/Utilities/helpers.js
src/Utilities/hooks/usePromiseQueue.js
src/__fixtures__/systems.js

This implements a queue to fetch paginated data sets. It is limited to 2 concurrent requests/promises to stay below request thresholds of CDN and the platform.
It changes the fetching of data for the following actions:
* Fetching issue ids for remediations (on the ReportDetails)
* "Select All" on all SystemsTables
* Export on all SystemsTables
How to test:
1) Get an account with big reports (>500 hosts per report recommended)( my account (you know which) has one report this big)
2) Perform all of the above actions
3) Pay special attention to "Edit Policy" and the "Create Policy" wizard

feat: Implement queued fetching

---

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap

fix(ReviewCreatedPolicy): RHICOMPL-3172 - Number of systems in labels

---

src/SmartComponents/ReportDetails/Components/ChartLegend.js
src/SmartComponents/ReportDetails/Components/__snapshots__/ReportChart.test.js.snap

fix(ReportDetailsLegend): RHICOMPL-3160 - Tooltips misalignment legends

---

src/SmartComponents/InventoryDetails/InventoryDetails.js
src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap

Fixes by passing inventory id to Inventory detail wrapper component.
Please run this PR against local Inventory app with the latest master branch

fix(ESSNTL-4429): pass inventory id to Inventory component

---

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js
src/PresentationalComponents/ComplianceEmptyState/__snapshots__/ComplianceEmptyState.test.js.snap
src/PresentationalComponents/SupportedSSGVersionsLink/__snapshots__/SupportedSSGVersionsLink.test.js.snap
src/constants.js

fix(DocLinks): Use updated doc references

---

src/App.js

This fixes issues causing the `Cannot read properties of undefined (reading 'pathname')` error. 

fix: Use useLocation instead of routerParams decorator

---

src/App.js

Fixes issues with navigating between pages via the chrome. 

fix(App): Use useChrome hook and router history

---

src/SmartComponents/SystemDetails/ComplianceDetail.js

Fixes the loading issues of the Compliance tab in the Inventory application.
These systems may not have any reports yet. 

fix(SystemDetails): ESSNTL-4493 - Only conditionally call id

---

src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/Columns.js

fix(SystemsTable): RHICOMPL-3641 - Provide proper export for failed rules

---

src/SmartComponents/ReportDetails/Components/__snapshots__/ReportChart.test.js.snap
src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js

fix(Reports): RHICOMPL-3662 - Fix issues with 0 system reports

---

config/dev.webpack.config.js
package-lock.json
package.json
src/SmartComponents/SystemsTable/SystemsTable.js
src/Utilities/Router.js

chore(RHIF-218): Update /beta to /preview

---

config/dev.webpack.config.js

fix(webpack): Match BETA env var properly

---

src/Routes.js

As in accordance to these mocks, this PR adds zero state to compliance,  https://docs.google.com/document/d/1FGuzbL2jyRmn_coYD5Z_o3d0MhOf1vQDT46NQvsfPyA/edit#heading=h.1hvxoje16w3i  https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/qbe9Ol2#Inspect   https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/prototype/a/AEF47CA9-8F00-40FC-B39B-3B989D3F83FD  

feat(RHIN-830): Add Zero State to Compliance

---

src/PresentationalComponents/RulesTable/helpers.js
src/SmartComponents/PolicyRules/PolicyRules.js

When rule groups are enabled the ruleTree should be available as well. 
See Jira for testing instructions. 

fix(PolicyRules): RHICOMPL-3716 - Request rule groups for default ruleset

---

src/SmartComponents/CompliancePolicies/CompliancePolicies.js
src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap
src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap
src/SmartComponents/PolicyDetails/PolicyDetails.js
src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
src/SmartComponents/ReportDetails/ReportDetails.js
src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js
src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/Reports/Reports.js
src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap
src/SmartComponents/SystemDetails/SystemDetails.js
src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap

chore: Replace deprecated Main component

---

src/PresentationalComponents/SupportedSSGVersionsLink/__snapshots__/SupportedSSGVersionsLink.test.js.snap
src/constants.js

Fixing non-working link to point on Supported SSGs article

fix(Doc): RHICOMPL-3781 - Fix unsupported doc link

---

pr_check.sh

This change is going to fix issues with old inventory image. Instead of updating images manually for stage inventory we will use prod ref where we have latest images.

fix(CI): Use prod ref when running pr_check

---

src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
src/SmartComponents/SystemsTable/Columns.js

Since backend work has been done some time ago, we can enable column filters (by score and by number of failed rules) for system tables

feat(SystemsTable): Enable column sorting by score & failed rules

---

package-lock.json
package.json

Jira link: [RHINENG-1722](https://issues.redhat.com/browse/RHINENG-1722)
Bug fix: https://github.com/RedHatInsights/frontend-components/pull/1903

chore: Update FEC to fix issue with Not Connected empty state

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js

This changes the wording for operating system to be something more specific:

fix(CreatePolicy): RHINENG-1919 - Update wording for OS

---

config/prod.webpack.config.js

As a part of containerized deployments, we need to build beta and stable code distinctly. This PR makes sure this is the case.

chore(RHINENG-506): introduce beta/stable check on prod webpack

---

src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
src/SmartComponents/CreatePolicy/__snapshots__/FinishedCreatePolicy.test.js.snap

Minor fix of printing full error message
Before:
After:

fix(RHINENG-1917): Fix FinishedCreatePolicy error message

---

src/SmartComponents/SystemDetails/ComplianceDetail.js

fix(ComplianceDetail): RHINENG-2710 sort policy tabs

---

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js

Updates the doc links with new 1-latest subpath

chore(RHINENG-7106): update doc links with 1-latest

---

config/helpers.js
package-lock.json
package.json

Installs Axios version 1.6.8 as a direct dependency. Before this, Axios was not installed, and probably the app was using Axios instance from a shared context or some peer dependency.

chore(RHINENG-8630): install axios version ^1.6.8

---

src/Modules/ComplianceDetails.js

1. Log in as org admin
2. go to inventory and open a systems which is not assigned to any compliance policy
3. go to compliance tab
4. the Create new policy button should be enabled

fix(ComplianceDetails): RHINENG-8348 fix perms in inventory

---

README.md
config/helpers.js
fec.config.js

Restores `LOCAL_APIS` functionality for `fec`

fix(fec): Restore local API routes proxying

---

src/PresentationalComponents/ProfileThresholdField/ProfileThresholdField.js
src/SmartComponents/SystemsTable/Cells.test.js

fix(RHINENG-10331): Threshold input width fix

---

src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.js
src/SmartComponents/SystemsTable/Cells.test.js

Removed duplicated info + added color for check button as it was before
Before:
After:

fix(RHINENG-10328): Remove duplicated Policy info

---

src/PresentationalComponents/InlineEdit/InlineEdit.js
src/SmartComponents/SystemsTable/Cells.test.js

fix(RHINENG-10327): Fix inline value edit buttons for rules

---

.travis.yml
config/cypress.webpack.config.js
package.json

fix(CI): Upload reports after each run

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-10139

chore(deps): Update braces package to resolve a CVE

---

.gitignore

fix(gitignore): Add .cache/ to gitignore

---

.travis.yml
package.json

Unset chrome as default browser in CI

fix(Cypress): add chrome to travis

---

src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.js
src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.test.js
src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/index.js
src/Frameworks/AsyncTableTools/components/TableStateProvider/TableStateProvider.js
src/Frameworks/AsyncTableTools/components/TableStateProvider/index.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/index.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/rowsBuilder.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.test.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useItems.js
src/Frameworks/AsyncTableTools/hooks/usePagination/index.js
src/Frameworks/AsyncTableTools/hooks/usePagination/usePagination.js
src/Frameworks/AsyncTableTools/hooks/usePagination/usePagination.test.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/index.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/reducer.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/useSelectionManager.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/useSelectionManager.test.js
src/Frameworks/AsyncTableTools/hooks/useTableState/index.js
src/Frameworks/AsyncTableTools/hooks/useTableState/useTableState.js
src/Frameworks/AsyncTableTools/hooks/useTableState/useTableState.test.js
src/Frameworks/AsyncTableTools/utils/testHelpers.js
src/PresentationalComponents/ComplianceTable/ComplianceTable.js
src/PresentationalComponents/ComplianceTable/ComplianceTable.test.js
src/PresentationalComponents/ComplianceTable/serialisers.js
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/index.js
src/SmartComponents/Reports/Reports.js
src/constants.js

This PR introduces the basics to start developing the Async Table implementation.
**AsyncTableTools**
These are the basic building blocks for the async table(s).
**usePaginate hook**
This hook has only been added as an example (commit) of what changes introducing a hook should require.
**ComplianceTable**
This will be a common table component that we will use to migrate tables to the async table implementation. We will use this as well to prepare compliance specific options/props for our tables.
This component uses the `ENABLE_ASYNC_TABLE_HOOKS` const in `src/constants.js` to enable the new Async implementation or the current TableToolsTable component. 
Try testing the Reports table with `ENABLE_ASYNC_TABLE_HOOKS` set to true or false.
- …

feat(AsyncTableTools): RHINENG-11605 - Introduce AsyncTableTools

---

src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/filterChipHelpers.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/filterChipHelpers.test.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/filterConfigHelpers.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/filterTypeHelpers.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/helpers.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/index.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/useEventHandlers.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/useFilterConfig.js
src/Frameworks/AsyncTableTools/hooks/useFilterConfig/useFilterConfig.test.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/reducer.js
src/PresentationalComponents/ComplianceTable/ComplianceTable.js
src/PresentationalComponents/ComplianceTable/serialisers.js
src/PresentationalComponents/ComplianceTable/serialisers.test.js
src/PresentationalComponents/ReportsTable/Filters.js
src/SmartComponents/Reports/Reports.js
src/Utilities/TestWrapper.js
src/Utilities/hooks/useTableTools/__fixtures__/filters.js
src/Utilities/hooks/useTableTools/__snapshots__/useFilterConfig.test.js.snap
src/constants.js

This PR adds the filtering feature the async table implementation and provides serialisation and example configuration for Compliance for it.
It also adds some minor improvements to ease development and debugging of the async table, most notably it allows enabling/disabling the async table via a localStorage entry. This is to make it easier to enable it, and will avoid situations where the `constants.js` file could be accidentally committed.
1) Open the Reports page
2) Verify that the ReportsTable is still using the current `TableToolsTable` without any change and without a 'insights:compliance:asynctables' localStorage entry.
3) Add a localStorage entry with the key 'insights:compliance:asynctables' and the value "true"
4) Reload the Reports page
5) Verify that now the …

feat(AsyncTableTools): RHINENG-11642 - Add useFilterConfig hook

---

package-lock.json
package.json

CVE-2021-21353 - See also https://github.com/RedHatInsights/compliance-frontend/security/dependabot/60

chore(deps): Bump pug to address CVE

---

src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.js
src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.test.js
src/Frameworks/AsyncTableTools/hooks/usePagination/usePagination.js
src/PresentationalComponents/ComplianceTable/serialisers.js

feat(RHINENG-11636): Update pagination hook and serializer

---

src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/rowsBuilder.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useExpandable/helpers.js
src/Frameworks/AsyncTableTools/hooks/useExpandable/index.js
src/Frameworks/AsyncTableTools/hooks/useExpandable/useExpandable.js
src/Frameworks/AsyncTableTools/hooks/useExpandable/useExpandable.test.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/reducer.js

Implements async useExpandable hook. There is a known [issue](https://redhat-internal.slack.com/archives/C05494LH96F/p1722853892200309) related to useSelectionManager hook, I am working on a fix.

feat(RHINENG-11641): implement async useExpandable hook

---

cypress/support/component.js

https://issues.redhat.com/browse/RHINENG-10340

fix(Cypress): Use Cypress config compatible with React 18

---

src/PresentationalComponents/PoliciesTable/Columns.js
src/SmartComponents/CompliancePolicies/CompliancePolicies.cy.js

While making factory tests for policies, I noticed the business objective sorting is wrong.
When business objective is empty it's `null`. Javascript would assume it's a string value `null`. This breaks the sorting.
~~According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description), Javascript sorts the values by UTF-16 code.~~
~~So this fix replaces the null value with the last UTF-16 character.~~
Empty business objectives will now be ahead of named ones.
1. Open `CompliancePolicies.js`
2. Use this code:
```js
let { error, loading, refetch } = useQuery(QUERY);
useEffect(() => {
refetch();
}, [location, refetch]);
let policies;
const data = {
profiles: {
edges: [
{
node: {
id: 'asd',
name: 'policy 1',
description: 'desc',
refId: …
```

fix(PoliciesTable): business objective sorting

---

package-lock.json

https://issues.redhat.com/browse/RHINENG-10144

 chore(deps): Update micromatch to fix a CVE 

---

package-lock.json
package.json
src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/helpers.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/helpers.test.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useColumnManager/helper.js
src/Frameworks/AsyncTableTools/hooks/useColumnManager/index.js
src/Frameworks/AsyncTableTools/hooks/useColumnManager/useColumnManager.js
src/Frameworks/AsyncTableTools/hooks/useColumnManager/useColumnManager.test.js
src/PresentationalComponents/WithPermission/__snapshots__/WithPermission.test.js.snap

This adds a hook for managing columns using the `ColumnManagementModal` component provided by the [react-component-groups](https://github.com/patternfly/react-component-groups/tree/main) package.
1) Enable the "async table" via the localStorage featureflag
2) Open the Reports page
3) Check the "actions menu" in the toolbar is shown
4) Open the "Manage Columns" modal via the actions menu
5) Select and deselect columns
6) Verify the columns are properly hidden/shown in the table itself when applying. 

feat(AsyncTableTools): RHINENG-11640 - Add useColumnManager

---

src/Utilities/dataSerialiser.js
src/Utilities/dataSerialiser.test.js

Added tests
New functionality for nested input object which might be handy later:
```js
const obj = {
policy: {
title: "my title"
}
};
const dataMap = {
"policy.title": "policy.name"
}
const res = dataSerialiser(obj, dataMap);
//{
//  policy: {
//     name: "my title"
//  }
//}
```

feat(DataSerialiser): nested input functionality + tests

---

src/PresentationalComponents/ReportsTable/Cells.test.js
src/PresentationalComponents/ReportsTable/ReportsTable.test.js
src/SmartComponents/ReportDetails/Components/ReportChart.test.js
src/SmartComponents/ReportDetails/Components/__snapshots__/ReportChart.test.js.snap
src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js
src/SmartComponents/ReportDetails/Components/hooks/useLegendData.js
src/SmartComponents/ReportDetails/constants.js
src/SmartComponents/Reports/Reports.cy.js

Fixes chart not showing never reported systems
**Before**:
**After**:

fix(ReportCharts): fix chart data & chart legend

---

.tekton/compliance-frontend-push.yaml

fix(CI): do not run unit tests upon merge in konflux

---

build_deploy.sh

chore(CI): bump a konflux build

---

build_deploy.sh

chore(CI): trigger a build via konflux

---

src/SmartComponents/CompliancePolicies/CompliancePolicies.cy.js
src/SmartComponents/CreatePolicy/CreatePolicy.test.js

fix(tests): Make cypress and jest tests work again

---

src/SmartComponents/ReportDownload/Components/ReportPDF.js

This fixes the business objective field in pdf report. 
To test:
1. From reports page, choose a report that has a business objective associated
2. Download the pdf report by the row action
3. Observe that the business objective is properly populated.

fix(RHINENG-11719): the business objective field in the report

---

build_deploy.sh
deployment_template.yaml

Adjust the default container in the deployment_template

---

.tekton/compliance-frontend-push.yaml

feat(CI): update konflux references

---

package-lock.json
package.json
src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/SystemsTable/SystemsTableRest.js
src/SmartComponents/SystemsTable/constants.js
src/SmartComponents/SystemsTable/hooks.js
src/SmartComponents/SystemsTable/hooks.test.js
src/SmartComponents/SystemsTable/hooks/useFetchSystems.js
src/Utilities/helpers.js
src/Utilities/helpers.test.js
src/Utilities/hooks/api/useOperatingSystems.js
src/Utilities/hooks/useQuery/apiInstance.js
src/constants.js

This migrates the Policy systems table to Rest API. Due to API shortcomings, ssgVersion column has been hidden. Also, all the disabled functionalities in SystemsTable component applies to this page as well. They are selection, tag filter.

feat(RHIENG-10400): migrate policy systems table to REST

---

src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js

fix(RHINENG-12789): Add missing profile descriptions when APIv2 enabled

---

src/PresentationalComponents/ComplianceScore/ComplianceScore.js

1. Icon color fixed
2. Removed dead code

fix(RHINENG-13743): Fix Icon color for compliant systems

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/EditPolicySystems.js

Implements https://issues.redhat.com/browse/RHINENG-12790.
This makes the EditPolicySystems and the systems select step in
the Create policy wizard support REST API requests.
Based on https://github.com/RedHatInsights/compliance-frontend/pull/2201.

feat(CreatePolicy > EditPolicySystems): Support REST API requests

---

package-lock.json
package.json
src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/SystemsTable/SystemsTableRest.js
src/SmartComponents/SystemsTable/SystemsTableRest.test.js
src/SmartComponents/SystemsTable/hooks.js
src/SmartComponents/SystemsTable/hooks.test.js
src/SmartComponents/SystemsTable/hooks/useFetchSystems.js
src/SmartComponents/SystemsTable/hooks/useFetchSystems.test.js
src/Utilities/hooks/api/useReports.js
src/Utilities/hooks/useAPIV2FeatureFlag.js

Fixes the tag filter on Compliance systems page.
To test:
1. navigate to Compliance systems page
2. play with the tag filter

fix(RHINENG-13403): apply tag filtering into REST

---

src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/ReportDownload/hooks/apiQueryHooks.js
src/Utilities/hooks/api/useReportTestResults.js
src/Utilities/hooks/useSupportedProfiles/useSupportedProfiles.js

fix(ApiClient): use params correct order

---

src/App.scss

Seems this [old commit ](https://github.com/RedHatInsights/compliance-frontend/commit/4170cf835f89bcbb133026b0c388ea6e76492956#diff-77a5c737b1177a8d6aeae73f7103cb353d22cbb8a944a65dad4fcf3bea142e1eR106) affected chip spacing. Did css for tags more specific and removed 1 css definition so tags looks nice now (vertically aligned too)
so 2 things have been fixed here: 
1. Chip spacing
2. Tags alignment
3. Pagination spacing ( now it has correct spacing as other apps have )
Before:
After:

fix(RHINENG-13784): Fix filter chip spacing

---

src/SmartComponents/ReportDownload/Components/ExportPDFForm.js

fix(RHINENG-13788): Fix PDF user notes behavior

---

src/SmartComponents/PolicyDetails/PolicyDetails.js
src/Utilities/hooks/api/useUpdateTailoring.js

fix(PolicyDetails): Fix undefined data prop

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
src/SmartComponents/SystemsTable/hooks.js
src/SmartComponents/SystemsTable/hooks/useLoadedItems.js

Fixes https://issues.redhat.com/browse/RHINENG-13404.

fix(RHINENG-13404): Fix preselected not working with useSystemBulkSelect

---

.tekton/compliance-frontend-pull-request.yaml
.tekton/compliance-frontend-push.yaml

feat(konflux): add new mandatory RPM signature scan task to tekton

---

src/SmartComponents/CompliancePolicies/CompliancePolicies.js

No jira.
This fixes the policies list page that had infinite re-render loop.
Go to the available policies list (/scappolicies). Check that the page does only one request to fetch policies and doesn't re-render it again unnecessarily.

fix(CompliancePolicies): Fix the policies page constant re-render

---

src/SmartComponents/Reports/Reports.js

fix(Reports): Add default filter back for Reports

---

src/SmartComponents/CreatePolicy/EditPolicySystems.js

Make filtering by OS work on Policy Wizard Systems step for v2
Also fix sorting by name for v2

fix(RHINENG-14111): Implement filtering by OS wizard systems

---

src/Frameworks/AsyncTableTools/hooks/usePagination/usePagination.js
src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.js
src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.test.js
src/Frameworks/AsyncTableTools/hooks/useTableState/useTableState.js

fix(compileState): Make applyObservers work with any number of observers

---

src/SmartComponents/ComplianceSystems/ComplianceSystems.js
src/SmartComponents/CreatePolicy/EditPolicySystems.js
src/SmartComponents/EditPolicy/EditPolicySystemsTab.js
src/SmartComponents/PolicyDetails/PolicySystemsTab.js
src/SmartComponents/SystemsTable/Columns.js

fix(RHINENG-14247): Use correct api sort by parameter on Systems

---

src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/useSelectionManager.js
src/PresentationalComponents/RulesTable/RulesTableRest.js
src/PresentationalComponents/Tailorings/Tailorings.js
src/PresentationalComponents/Tailorings/components/TailoringTab.js

Fixes the selection that uses AsyncTableTools and useBulkSelect hook. The issue was related to how the default selection is managed and also how to elevate selection changes from the useBulkSelect to the consumer component using handleSelect prop.

fix(RulesTable): selection is fixed

---

.tekton/compliance-frontend-pull-request.yaml
.tekton/compliance-frontend-push.yaml

feat(Konflux): Update template

---

src/PresentationalComponents/ReportDetailsDescription/ReportDetailsDescription.js

https://issues.redhat.com/browse/RHINENG-14291

fix(rhineng-14291): fix source for view policy button id

---

deployment_template.yaml

revert(konflux): use non-konflux image for deployment

---

src/SmartComponents/PolicyDetails/hooks/useSaveValueOverrides.js

fix(RHINENG-14373): make patching value work

---

src/PresentationalComponents/RulesTable/RulesTableRest.js
src/SmartComponents/SystemDetails/RuleResults.js

[RHINENG-14417](https://issues.redhat.com/browse/RHINENG-14417)
System detail page should show only failed rules by default. 

feat(RHINENG-14417): system detail default filter

---

src/PresentationalComponents/ComplianceTable/ComplianceTable.js
src/PresentationalComponents/ComplianceTable/ComplianceTable.test.js
src/PresentationalComponents/PoliciesTable/PoliciesTable.test.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js
src/constants.js

feat(RHINENG-14339): Unite asynctables & v2 FF

---

src/PresentationalComponents/Tailorings/Tailorings.js
src/PresentationalComponents/Tailorings/components/TabHeader.js
src/PresentationalComponents/Tailorings/hooks/useSecurityGuideData.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/useProfileRuleIds.js
src/SmartComponents/PolicyRules/PolicyRules.js
src/SmartComponents/PolicyRules/PolicyRulesHeader.js
src/Utilities/hooks/api/usePolicyRulesList.js
src/Utilities/hooks/api/useProfile.js

This PR is going to connect our modals with Default rules page via "View policy rules" link

feat(RHINENG-13052): Default rules page follow up

---

src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/useProfileRuleIds.js
src/SmartComponents/EditPolicy/EditPolicyRulesTabRest.js

Fixes https://issues.redhat.com/browse/RHINENG-11721.

fix(EditPolicy): Fix selection for multiple security guides scenario

---

src/SmartComponents/EditPolicy/hooks.js

fix(EditPolicy): Close the modal when the edit policy succeeds

---

src/PresentationalComponents/Tailorings/NoTailorings.js
src/PresentationalComponents/Tailorings/Tailorings.js

1. Create a Policy using REST APIv2 (don't use UI as it forces you to associate hosts)
2. As policy has been created via RESTv2, it has 0 hosts -> no tailorings under policy
3. Navigate to Policy details Rules tab
4. Observe special view
**How it works now:**
https://github.com/user-attachments/assets/9bc13be1-6834-46b5-b89d-e1839a96d3af

feat(RHINENG-14521): make page work when no tailoring

---

src/PresentationalComponents/Tailorings/Tailorings.js

fix(CreatePolWizard): Fix tailorings view

---

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js
src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.test.js
src/SmartComponents/CompliancePolicies/CompliancePoliciesRest.js
src/SmartComponents/Reports/Reports.js
src/SmartComponents/Reports/Reports.test.js
src/Utilities/hooks/useReportsCount.js

1. Added EmptyState to Reports page when v2 is used
2. Fixed EmptyState API calls ( before the fix, if you use v2 only - EmtpyState component will still call GQL API to get policies). Now it will use API depending on feature flag
3. Added test coverage for 1. and 2.

fix(RHINENG-14672): Reports empty state

---

src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js

fix(Tailorings): Add missing OUIA ID

---

src/SmartComponents/ReportDetails/ReportDetails.js

feat(ReportDetails): Add OUIA IDs to tabs

---

src/SmartComponents/ReportDetails/ReportDetails.js

[RHINENG-15165](https://issues.redhat.com/browse/RHINENG-15165)
In Compliance > Reports > Report detail > Never reported table sorting by name should work

fix(RHINENG-15165): sorting by name in Never reported table

---

cypress/support/commands.js
src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useTableSort/helpers.js
src/Frameworks/AsyncTableTools/hooks/useTableSort/useTableSort.js
src/PresentationalComponents/ComplianceTable/ComplianceTable.js
src/SmartComponents/CompliancePolicies/CompliancePolicies.cy.js

[RHINENG-10460](https://issues.redhat.com/browse/RHINENG-10460)
Sorting was offset by one or two columns on some tables (rule tables or tables with bulk select/expansion).
How to test:
Verify that the currently sorted column is displayed correctly and the endpoints are called with the proper sort value.
Check for all AsyncTableTools table (exclude system tables)
Old tests are commented out and some additional work is needed for the API V2 tests to work.

fix(RHINENG-10460): column sorting

---

src/PresentationalComponents/RulesTable/RulesTableRest.js
src/SmartComponents/SystemDetails/RuleResults.js

How to test:
1. Navigate to system details that has report
2. Expand any rule
3. Observe expanded rule shows data instead of loading skeleton

fix(RHINENG-15212): Make rule expand work SystemDetails

---

renovate.json

This should help us to get Konflux PRs automerged when hash is only updated

feat(RHINENG-15251): Enable automerge Konflux digest update

---

.github/workflows/main.yml
fec.config.js

Updates flow to always inject debugID, and update the workflow file to remove overriding of release in sentry, and map against debug IDs properly

fix(sentry): Update sentrys workflow and always inject debugIDs

---

.github/CODEOWNERS

chore(repo): Remove codeowners for Konflux automerge

---

.github/workflows/docs.yml
README.md

chore: Add JSDoc action to generate and publish docs to GH Pages

---

.tekton/compliance-frontend-pull-request.yaml
.tekton/compliance-frontend-push.yaml

fix(Konflux): Bump task-buildah to fix pipeline issue

---

renovate.json

feat(KonfluxCI): Test schedule

---

renovate.json

feat(KonfluxCI): Restructure & refactor renovate config

---

deployment_template.yaml

Some time ago we did a revert and started using images created in app-interface jenkins. Now we are getting back to Konflux. Revert PR https://github.com/RedHatInsights/compliance-frontend/pull/2269

feat(Konflux): Use Konflux image for deployments

---

renovate.json

feat(Konflux): Use default platform schedule

---

src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
src/Frameworks/AsyncTableTools/hooks/useRadioSelect/index.js
src/Frameworks/AsyncTableTools/hooks/useRadioSelect/useRadioSelect.js
src/Frameworks/AsyncTableTools/hooks/useTableView/views/rowsBuilder.js
src/PresentationalComponents/RulesTable/RulesTableRest.js
src/SmartComponents/CreatePolicy/Components/PolicyTypeDetailsRow.js
src/SmartComponents/CreatePolicy/Components/PolicyTypeTable.js
src/SmartComponents/CreatePolicy/CreatePolicy.test.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyBase.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js
src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.test.js

feat(RHINENG-13541): Use AsyncTable for PolicyTypesTable

---

.gitmodules
.tekton/compliance-frontend-pull-request.yaml
.tekton/compliance-frontend-push.yaml

[RHINENG-16150](https://issues.redhat.com/browse/RHINENG-16150)

chore(build): use shared Dockerfile

---

src/SmartComponents/SystemsTable/hooks.js

This PR implements fetching system details properly when systems are selected in the Edit Policy Systems tab.
1) Open the Edit Policy modal for a policy
2) Navigate to the Systems tab
3) Filter systems by specific OS versions (make sure to exceed the "perPage")
4) Use the bulk select dropdown and "Select All (x)"
5) Verify that the selection count is increased properly

fix(SystemsTable): RHINENG-14946 - Properly fetch systems on selection

---

src/PresentationalComponents/PoliciesTable/hooks/useActionResolvers.js

fix(PoliciesTable): Use proper property

---

src/Frameworks/AsyncTableTools/components/TableStateProvider/TableStateProvider.js
src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.js
src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.test.js
src/Frameworks/AsyncTableTools/hooks/useSelectionManager/useSelectionManager.test.js
src/Frameworks/AsyncTableTools/hooks/useTableState/helpers/compileState.js
src/Frameworks/AsyncTableTools/hooks/useTableState/hooks/useCallbacks.js
src/Frameworks/AsyncTableTools/hooks/useTableState/hooks/useCallbacksCallback.js
src/Frameworks/AsyncTableTools/hooks/useTableState/hooks/useContextOrInternalStateAndRefs.js
src/Frameworks/AsyncTableTools/hooks/useTableState/hooks/useStateCallbacks.js
src/Frameworks/AsyncTableTools/hooks/useTableState/useTableState.js
src/PresentationalComponents/ResetRules/ResetRules.js
src/PresentationalComponents/RulesTable/RulesTable.js
src/PresentationalComponents/Tailorings/Tailorings.js
src/PresentationalComponents/Tailorings/components/TabHeader.js
src/PresentationalComponents/Tailorings/components/TailoringTab.js
src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRules.js
src/SmartComponents/EditPolicy/EditPolicyRulesTab.js

[RHINENG-14408](https://issues.redhat.com/browse/RHINENG-14408)
On the 4th step, you should see the reset button, play with the selection and resetting should work
In the rules tab, the reset button should not be visible
Here the reset rules button should work as well

feat(RHINENG-14408): create policy wizard reset rules

---

src/PresentationalComponents/RemediationCell/RemediationCell.js
src/PresentationalComponents/RulesTable/Columns.js

https://issues.redhat.com/browse/RHINENG-16658 
This removes the ansible logo and changes the column of Remediation to Remediation type. 
This column can be found in systems details page

feat(RHINENG:16786): Change Rem column to Remediation Type/Remove ansible logo

---

src/SmartComponents/SystemsTable/hooks.js
src/Utilities/hooks/useComplianceQuery/useComplianceQuery.js

fix(SystemsTable): Only call loading if defined

---

README.md

Doc change to re-trigger konflux build/push image correctly on master

fix(CI): Build konflux image on master

---

src/SmartComponents/SystemsTable/SystemsTable.js

fix(SystemsTable): Show workspaces filter

---

src/SmartComponents/SystemsTable/Cells.js

fix(RHINENG-13844): Show read more on more than 2 policies

---

src/SmartComponents/CreatePolicy/CreatePolicy.js

Another follow-up to #2487 to change the check to check if there are policies of any kind.

fix(CreatePolicy): RHINENG-15324 - Only allow no hosts if really no policies

---

src/SmartComponents/SystemsTable/hooks/useSystemsFilterConfig.js

fix(SystemsTable): RHINENG-19698 - Use proper activeFilters

---

src/Frameworks/AsyncTableTools/hooks/useTableView/views/treeChopper.test.js
src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js
src/PresentationalComponents/ErrorPage/ErrorPage.js
src/PresentationalComponents/ReportsTable/ReportsTable.js
src/PresentationalComponents/SystemsCountWarning/SystemsCountWarning.js
src/PresentationalComponents/TabSwitcher/TabSwitcher.js
src/SmartComponents/CreatePolicy/CreatePolicy.js
src/SmartComponents/DeletePolicy/DeletePolicy.test.js
src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.js
src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.test.js
src/SmartComponents/SystemDetails/RuleResults.js
src/SmartComponents/SystemDetails/RuleResults.test.js
src/SmartComponents/SystemDetails/SystemPoliciesAndRules.js
src/SmartComponents/SystemsTable/hooks/useSystemsQueries/useSystemsQueries.test.js

This PR addresses several warnings thrown when running tests.

chore: Cleanup and update tests
