package-lock.json, package.json, src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js, src/SmartComponents/InventoryDetails/InventoryDetails.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/SystemDetails/SystemDetails.js, src/store/Reducers/SystemStore.js
If the inventory is rendered twice without reloading the page, the
Reducer is adding the columns to be shown more than once (e.g:
compliance score is added once again). At that point there are more
columns than there are are values to fill.
=> Fixes crash re-rendering inventory

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js, src/store/Reducers/SystemStore.js
The newest inventory stores hosts only on 'entities.rows', instead of
'entities.entities'. We should adapt the Remediations button to that,
and also pass a 'compliance:' prefix to every rule.
=> Update Remediations to new Inventory format

package-lock.json, package.json, src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js, src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/SystemsTable/SystemsTable.js
This commit disables the button in the places where we can potentially
request N fixes for M hosts, which is something not supported by the
Remediations modal yet. It also enables the button only when you check a
few rules in the rules page.
=> Disable Ansible button when not available

src/SmartComponents/DownloadTableButton/DownloadTableButton.js
Before this, it was using the old method from the inventory
'entities.entities' to get all available entities. It's now adapted
to use .rows
=> Filter selected entities for export to CSV button properly

src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js, src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/SystemDetails/SystemDetails.js
IMO if a user is denied access to a given resource for RBAC reasons, we should be returning 403 rather than 401, as discussed [here](http://www.dirv.me/blog/2011/07/18/understanding-403-forbidden/index.html).
=> Fixes RHICOMPL-34: Redirect to login on 401's

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/SetThresholdDropdown/SetThresholdDropdown.js, src/SmartComponents/SetThresholdDropdown/UpdateProfileThreshold.js
Demo:
If you try to input a number above 100 or below 0, the field blocks you from doing so and shows the error, instructing you to write a number between 0 and 100. 
The page is fully reloaded after changing the threshold, I tried doing this without a page reload and it's feasible but it's a lot more of code that has to nullify the cached donut charts and compliance values everywhere. I suppose this would be something that would not be normally changed.  
cc @katierik
=> Allow to set compliance threshold on a per-profile basis

src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js
If we want to use `TextVariant.blockquote` or `<div>`, we cannot put it inside an `<EmptyStateBody>`, as it generates the following warning because [it's essentially a `<p>` tag](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateBody.js#L7):
```
Warning: validateDOMNesting(...): <blockquote> cannot appear as a descendant of <p>.
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```
This does not change how the empty state page looks. It merely replaces the `<p>` with a `<span>`
=> Remove invalid DOM nesting inside a <p>

src/SmartComponents/DownloadTableButton/DownloadTableButton.js
I added this as a premature start to i18n, but it generates a warning in the JS console:
```
Warning: Received `true` for a non-boolean attribute `translate`.
```
=> Remove translate prop to reduce warnings

src/SmartComponents/ImageStreamsWizard/ImageStreamEmptyState.js
Same as https://github.com/RedHatInsights/compliance-frontend/pull/115
If we want to use `<div>`, we cannot put it inside an `<EmptyStateBody>`, as it generates the following warning because [it's essentially a `<p>` tag](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/src/components/EmptyState/EmptyStateBody.js#L7):
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```
This does not change how the empty state page looks. It merely replaces the `<p>` with a `<span>`
=> Update imagestreams empty state with valid DOM

src/store/Reducers/SystemStore.js
On the systems page, the "Compliant" icon was not showing anymore as the component tries to pull it from Facts, but the Facts only contain ComplianceScore since  https://github.com/RedHatInsights/compliance-frontend/commit/a4b16a5df2c673167229ecc5003af5d3a89e3ed2
=> Add Compliant to facts in redux store

src/SmartComponents/DownloadTableButton/DownloadTableButton.js
Before:
After:
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-140
=> Kebab dropdown isPlain

package-lock.json, package.json, src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js
This seems to allow pagination to work well using the new FEC version, it fetches 50 items by default as expected by that table. Updating patternfly and react-patternfly to the FEC breaks some things like breadcrumbs and tabs, so we're holding off those for now.
=> Adapt pagination to newest FEC

package-lock.json, package.json, src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
This should be completed with a similar PR in insights-frontend-components. This button is only used in the SystemsTable, but the `insights-frontend-components` one is used in the rules table.
=> Adapt to ssg: remediations API format

package-lock.json, src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/store/Reducers/SystemStore.js
When fetching all systems we have to get amount of systems in DB by getting host count in all profiles. Laer we have to fetch current page from graphql and once that is done call host fetch to get inventory info. Once inventory fetches these data we have to map our specific information to it as well.
* Call graphql with `allProfiles` query and take `total_host_count`. Once that is fullfilled pass number of systems to Systems table as total
* Fetch `name`, `profile_names` and `compliant` values for each page in systems
* Pass callback to systems to reducer so we can access previously fetched systems (from compliance DB)
=> Fix all systems pagination to show all systems instead of limited amount

src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/SystemsTable/SystemsTable.js
This allows us to easily fetch systems on a per_page basis on the
ProfileDetails page, following the same logic as we follow in the
Systems page
=> Move fetching profileDetails systems to systemsTable component

package-lock.json, package.json
If you go to the System Details view, the rules won't load as they are coming from FEC and versions of FEC before this one don't have the fix to work with the API on FF<= 60
=> Update FEC to show rules in FF <= 60

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
Before this change, to display the remediations modal we had
to fetch all remediations available per system. Now we request
all remediations using only one request.
=> Request for all host remediations at once

src/SmartComponents/SystemsComplianceFilter/SystemsComplianceFilter.js
Without the filter prop, the behavior in the gif is the current one: the filters are cleared after clicking outside of the filter and hiding the dropdown. This PR fixes that so filters persist after a click.
=> RHICOMPL-189 - Do not clear filter after clicking outside

src/App.scss, src/SmartComponents/CompliancePoliciesCards/CompliancePoliciesCards.js
The reason why the TextInput was grey is that disabled text inputs are grey by default, the color comes from the system, not from Patternfly. If we set the `isReadOnly` option, the text input to copy becomes grey instead of white.
=> RHICOMPL-145 - Commands to copy should have white background

src/SmartComponents/ComplianceSystemsTable/ComplianceSystemsTable.js
Currently pagination is broken because the system count is not done appropriately due to a capitalization error after the GraphQL refactor. It works OK with this change.
=> RHICOMPL-245 - Fix pagination in systems list

src/store/Reducers/SystemStore.js
If a host has no info to compute its compliance, we are currently showing `NaN` and :heavy_check_mark:  - which is wrong. This should be a very rare and unexpected case, but still I would rather show this than the current misleading :heavy_check_mark:
=> Show N/A if compliance cannot be computed

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
Without turning the profile into lowercase, the C2S profile does not
work. Remediations expects the profile to be lowercase so it returns a
400 when we check whether there is an available remediation or not
=> Support C2S remediations

src/App.scss, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/PolicyDetails/PolicyDetails.js
I wanted to use the newer version of the charts in https://www.patternfly.org/v4/documentation/react/charts/chartdonututilization/ - but in the end it's a bit difficult because the `VictoryContainer` in which the charts are rendered has some props already baked in by Patternfly.
Quick demo (>10MB, cannot upload to GitHub directly): 
https://gfycat.com/unconsciousanydikkops
=> RHICOMPL-208 - Policy detail header responsiveness

src/App.scss, src/SmartComponents/EditPolicy/BusinessObjectiveField.js, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/ProfileThresholdField.js, src/SmartComponents/EditPolicy/UpdateProfile.js
@katierik - thoughts about this? The text fields font-weight do not exactly match what I see on Marvelapp, to do so I would have to override default Patternfly styles, so I wasn't sure whether we should or not. 
The form field labels are in *bold* in Patternfly 4 (https://www.patternfly.org/v4/documentation/react/components/form/) 
And the titles are not in bold - https://www.patternfly.org/v4/documentation/react/components/title/
=> RHICOMPL-269 - Allow to select 'None' business objective

src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js, src/SmartComponents/EditPolicy/BusinessObjectiveField.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap, src/Utilities/TextHelper.js, src/store/Reducers/SystemStore.js
This adds a helper and wraps all percentages displayed to make sure they are displayed consistantly throughout the UI.
It also sneaks in a minor fix: adding a dot to 'e.g'
=> RHICOMPL-272 - Make sure all percentages displayed are rounded

src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
Fix for a minor issue with truncate rendering a div within a p element if it's not set to inline, which makes the DOM invalid and show an error in the console.
The error is also shown when running tests (locally and CI):
```console.error node_modules/react-dom/cjs/react-dom.development.js:558
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
in div (created by StackItem)
in StackItem (created by Truncate)
in div (created by Stack)
in Stack (created by Truncate)
in Truncate (created by PolicyDetailsQuery)
in p (created by Text)
in Text (created by PolicyDetailsQuery)
in div (created by TextContent)
in TextContent (created by PolicyDetailsQuery)
in div (created by GridItem)
in GridItem (created by PolicyDetailsQuery)
in div (created by Grid)
in Grid (created by …
```
=> Set inline for Truncate

package-lock.json, package.json, src/Charts.scss, src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/CompliancePolicyCard/CompliancePolicyCard.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
"Systems meet compliance threshold" doesn't need to wrap
Tooltips on charts should be the black ones
- I needed to update Patternfly-charts to the latest version, which actually allows us to remove a lot of code. 
- Removed a semicolon in the loading state
cc @katierik
=> RHICOMPL-384 - Papercuts on Policy list

src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
Here's a system with remediations available:
And here's another system *with rules failing* but NO remediations available, the button should remain disabled like this:
=> RHICOMPL-401 - Enable remediations button only if remediation available

src/SmartComponents/CompliancePolicies/CompliancePolicies.js
Simple workaround for all of the N/A profiles. In addition to that, if https://github.com/RedHatInsights/compliance-backend/pull/257 we will need to merge something like this.
=> Display only profiles with at least 1 host

src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap, src/SmartComponents/SystemDetails/SystemDetails.js, src/Utilities/Breadcrumbs.js
This replaces the `Breadcrumbs` component from `frontend-components` with the Patternfly 4 component. As the Patternfly component had no equivilant to `onNavigate`, it is using `onClick` instead and required a minor fix.
Visibly nothing changes, they are identical.
=> Update Breadcrumbs to use patternfly component

src/Utilities/Breadcrumbs.js, src/constants.js
When navigating via breadcrumbs on either `PolicyDetails` or `SystemsDetails` the paths would not be found by the router and fall back to the policies list, which breaks navigating to the systems list from a system details page. On policy details this would not be obvious as the wrong path would still be directing the user to the policy list.
This removes the UI root path from paths of Breadcrumbs and allow matching the correct routes in the router.
=> RHICOMPL-423 - Remove compliance ui root from breadcrumb onNavigate

src/SmartComponents/EditPolicy/BusinessObjectiveField.js, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/UpdateProfile.js, src/SmartComponents/EditPolicy/UpdateProfileButton.js, src/SmartComponents/EditPolicy/UpdateProfileButton.test.js, src/SmartComponents/EditPolicy/__snapshots__/UpdateProfileButton.test.js.snap
This simplifies the `BusinessObjectiveField` and makes more use of [react-select](https://react-select.com/props) features and fixes the issues with setting initial options.
**tl;dr:**
* A `loadOptions` function is passed to `Select` instead of handling options in `BusinessObjectiveField`
* `BusinessObjectiveField` is now disconnected from redux-form and `dispatch` passed
* `handleCreate` and `handleChange` are simplified
* `handleChange` dispatches the redux-form change
* `UpdateProfileButton` has now a very verbose `handleBusinessObjective`
**What to test:** (Checklist for manual and jest tests)
=> Simplify BusinessObjectiveField and fix behaviour

package-lock.json, package.json, src/PresentationalComponents/CompliancePolicyCard/__snapshots__/CompliancePolicyCard.test.js.snap, src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/CompliancePolicies/CompliancePolicies.test.js, src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap, src/SmartComponents/ComplianceRemediationButton/ComplianceRemediationButton.js, src/SmartComponents/ComplianceSystems/ComplianceSystems.test.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap, src/SmartComponents/DownloadTableButton/DownloadTableButton.js, src/SmartComponents/DownloadTableButton/DownloadTableButton.test.js, src/SmartComponents/DownloadTableButton/__snapshots__/DownloadTableButton.test.js.snap, src/SmartComponents/EditPolicy/BusinessObjectiveField.js, src/SmartComponents/EditPolicy/BusinessObjectiveField.test.js, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicy.test.js, src/SmartComponents/EditPolicy/ProfileThresholdField.js, src/SmartComponents/EditPolicy/ProfileThresholdField.test.js, src/SmartComponents/EditPolicy/__snapshots__/BusinessObjectiveField.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/ProfileThresholdField.test.js.snap, src/SmartComponents/InventoryDetails/InventoryDetails.test.js, src/SmartComponents/InventoryDetails/__snapshots__/InventoryDetails.test.js.snap, src/SmartComponents/SystemDetails/SystemDetails.js, src/SmartComponents/SystemDetails/SystemDetails.test.js, src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap, src/SmartComponents/index.js, src/Utilities/Breadcrumbs.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
* Update react-router-com to support hooks
* Add tests for:
* CompliancePolicies
* DownloadTableButton
* BusinessObjectiveField
* EditPolicy
* ProfileThresholdField
* SystemDetails
* InventoryDetails
* Rewrites the SystemsDetails component to use hooks
* + minor fixes and updates
This brings us to about 66% coverage, removing the ComplianceRemidiationsButton and replacing it with the frontend-component version will bring us to about 75% code coverage.
The remaining 25% of uncovered code are mostly minor functions, but a branch with tests covering those is in progress.
=> Increase testcoverage and refactor #3

src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
Before this PR, a `parseInt` was rounding the compliance threshold value, not allowing the compliance threshold to be set to a float.
=> RHICOMPL-449 - Fix floating point thresholds

src/SmartComponents/PoliciesTable/PoliciesTable.js, src/SmartComponents/SystemsTable/SystemsTable.js
Without moving back to page 1, the table fails to show the results that should be on the 1st page for searches with results that only cover 1 page.
=> RHICOMPL-394 - Move to page 1 after searching systems

src/PresentationalComponents/ReduxFormWrappers/ReduxFormWrappers.test.js, src/PresentationalComponents/ReduxFormWrappers/__snapshots__/ReduxFormWrappers.test.js.snap, src/SmartComponents/EditPolicy/UpdateProfileButton.test.js, src/SmartComponents/SystemDetails/SystemDetails.js, src/SmartComponents/SystemDetails/SystemDetails.test.js, src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap
Just a clean up of the `SystemDetails` component after fixing the issues we had with `withRouter`.
It now uses the `useParams` hook to access get the `inventoryId` and tests are a bit cleaner.
There were also two required props missing in the tests for the Checkbox component (that we don't seem to actaully use) and the UpdateProfileButton.
=> Cleanup systemdetails

src/PresentationalComponents/LoadingPoliciesTable/LoadingPoliciesTable.js, src/PresentationalComponents/LoadingPoliciesTable/__snapshots__/LoadingPoliciesTable.test.js.snap, src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/PoliciesTable/PoliciesTable.js, src/SmartComponents/PoliciesTable/PoliciesTable.test.js, src/SmartComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap, src/SmartComponents/PoliciesTable/fixtures.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
⚠️ **Requires** https://github.com/RedHatInsights/compliance-backend/pull/313
This adds the operating system to the policies table as well as the header in the policy details:
=> Add operating system to Policies table and details

src/PresentationalComponents/ComplianceScore/ComplianceScore.js
Eliminates: 
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `BodyRow`. See https://fb.me/react-warning-keys for more information.
in CompliantIcon
in BodyRow (created by BaseBody)
in tbody (created by BodyWrapper)
in BodyWrapper (created by BaseBody)
in BaseBody (created by Context.Consumer)
in Body (created by ContextBody)
in ContextBody (created by Context.Consumer)
in TableBody
```
=> Set key for compliance icon

src/App.scss, src/PresentationalComponents/ComplianceTabs/ComplianceTabs.js, src/PresentationalComponents/ReportTabs/ReportTabs.js, src/PresentationalComponents/ReportTabs/ReportTabs.test.js, src/PresentationalComponents/ReportTabs/__snapshots__/ReportTabs.test.js.snap, src/PresentationalComponents/index.js, src/Routes.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/Reports/Reports.js, src/SmartComponents/Reports/Reports.test.js, src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap, src/SmartComponents/ReportsSystems/ReportsSystems.js, src/SmartComponents/ReportsSystems/ReportsSystems.test.js, src/SmartComponents/ReportsSystems/__snapshots__/ReportsSystems.test.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
The "By systems" tab is now the old systems table, which only contains hosts with compliance policies assigned:  
And the /systems page is now the whole inventory with the actions to assign the policies:
=>  RHICOMPL-469 - Compliance Reports should have a By Systems tab 

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js
Notice the prop passed in here https://github.com/RedHatInsights/compliance-frontend/pull/393/files#diff-8d895559dea653c589c26d45256675efR317
This change should just be a refactoring to clear up any confusion between the two props.
=> Seperate allSystems from showAllSystems

src/SmartComponents/DeletePolicy/DeletePolicy.js, src/SmartComponents/DeletePolicy/DeletePolicy.test.js, src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
Adds a checkbox to optionally remove reports for a given policy.
Accompanying backend PR: https://github.com/RedHatInsights/compliance-backend/pull/326
=> Add checkbox to optionally remove all test results aka. reports

src/App.scss, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
This PR contains updates to the responsiveness of the page, to at least make it impossible for buttons to collapse upon each other when shrinking the page (which happened before this change). Besides that, it also updates the Dropdown to a Button to Edit Policies as indicated on the mocks.
=> Edit Policy button responsiveness

src/PresentationalComponents/TabSwitcher/TabSwitcher.js, src/PresentationalComponents/TabSwitcher/TabSwitcher.test.js, src/PresentationalComponents/TabSwitcher/__snapshots__/TabSwitcher.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/PolicyDetails/PolicyDetails.js
This adds a small `TabSwitcher` component to select a specific component to render via a `tabId`. 
The `Tab` component is purely decorational, the switcher component only checks for a `tabID` prop and not for any specifc component type.
=> Add TabSwitcher for PolicyDetails component

src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/PolicySystemsTab.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
With the changes to tabs it is not guaranteed that there is a `SystemsTable`.
Trying to just  guard the `systemFetch` and `forceUpdate` calls with an `if (systemsTable.current.getWrappedInstance()) ...` turned out to be unreliable and cause different unexpected behavior on each tab.
This removes the `Ref` and allows `SystemsTable` to trigger a call to `systemFetch` on it's own when the compliance threshold prop changes, which seems to be the only case where we want(ed) to trigger a refresh from the outside.
=> Use prop instead of ref to trigger systemFetch

src/store/Reducers/SystemStore.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
Relative dates should have the full datetime displayed in a tooltip. 
Using DateFormat provides that.
=> Use DateFormat component to get dates with tooltips

src/PresentationalComponents/ComplianceScore/ComplianceScore.js, src/PresentationalComponents/ComplianceScore/ComplianceScore.test.js, src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
Before, the systems table displayed the *global* compliance, *global* failed rules count, and *global* last scanned, even when you visit the ReportDetails page, or the PolicyDetails page. 
Now, on the "Reports" "By systems" page, we show the global values, but on every specific "ReportDetails" or "PolicyDetails" page, we only see the values related to that profile.
=> RHICOMPL-389 - Show rules/lastScan/compliant per profile on systems table

src/Routes.js, src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/PolicyDetails/PolicySystemsTab.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportsSystems/ReportsSystems.js, src/SmartComponents/ReportsSystems/__snapshots__/ReportsSystems.test.js.snap, src/store/Reducers/SystemStore.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
This accomplishes a few things:
- Links are fixed, before, you could not reach the system details page from policy details or report details, only from the list of all systems.
- Our routes are now cleaner - system details is *exclusively* reached through /systems/:inventoryId. Good riddance to the old long URLs with both the policy ID and the system ID. 
- 'Name' was renamed to 'System name' and 'Profiles' to 'Policies' wherever needed as we discussed during the UXD review this week.
=> RHICOMPL-500 - Simplify routes and point all systems to /systems/:inventoryId

src/SmartComponents/CreatePolicy/CreatePolicy.test.js, src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js, src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js
Hopefully the title is self-explanatory - this reduces the list of possible benchmarks to the latest SSG versions
=> Only return the latest SSG version to create a new policy

src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/Reports/Reports.js
The Reports page is not updating properly when you do stuff such as
removing a policy, or clicking back and forth between the vertical
navigation elements. Instead, we can use cache-and-network which returns
the cache elements first - and makes a network call in the backend,
which is only used to populate the data if it's different to what was in
the cache.
=> Update cache-settings for Reports page

src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap
According to UX the Wizard should use the default sizing and not stretch full width and height.
=> Do not expand wizard to full width

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
Before, we were passing literally all hosts, regardless of selections to the button (see the JIRA card)
=> RHICOMPL-568 - Pass only selected hosts to Remediations

src/SmartComponents/SystemsTable/SystemsTable.js
Deleting a filter broke on the SystemsTable, this issue snuck in. 
The chips come as an array for the callback, but we only need the the first. 
This is the same as already in `PoliciesTable`[1].
[1] https://github.com/RedHatInsights/compliance-frontend/blob/master/src/SmartComponents/PoliciesTable/PoliciesTable.js#L136
=> Fix filter chip deletion on SystemsTable

src/SmartComponents/ReportDetails/ReportDetails.js
In the Report Details page, currently loading the description fails as it tries to populate the description of the OS with the SSG version, which is not queried.
=> Fetch benchmark for Report details description

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js
This improves the performance on the Systems table (the one in beta with all systems) and the same table in the CreatePolicy wizard. It doesn't make sense to pull the rules, especially when that is an expensive operation, as they are useless in this context without the Remediation button. The table is slow when the Remediation button is used but I'm working on fixing that as well (likely on the backend).
=> RHICOMPL-586 - Do not load rules if there's no remediation button

src/PresentationalComponents/ReportCard/PolicyPopover.js, src/PresentationalComponents/ReportCard/ReportCard.js, src/PresentationalComponents/ReportCard/ReportCard.test.js, src/PresentationalComponents/ReportCard/__snapshots__/ReportCard.test.js.snap, src/SmartComponents/Reports/Reports.js, src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap
This commit changes the Report card to:
- display SSG on a separate line
- show the policy info on the popover
- link to the policy ID on view policy if availabble
=> Changes to report card to display SSG from policy

src/store/Reducers/SystemStore.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
Just a minor change we could implement if the hostname is not found in the inventory. Currently the system details page is resilient enough to make it pretty clear that the system is not in the inventory, but it doesn't break anything.
This fixes all of the "empty names" around the app if a host is missing in the inventory. I'd prioritize https://github.com/RedHatInsights/compliance-backend/pull/384 over this, but it's nice in dev environments (or if you had imported a prod dump to test the data).
=> Name is displayed even if host is not in the inventory

src/PresentationalComponents/ReportCard/ReportCard.js, src/PresentationalComponents/ReportCard/__snapshots__/ReportCard.test.js.snap
This allows us to keep the popover in the ReportCard always visible so that even with the truncated text, the user can just click on it. It is very frustrating otherwise to aim for it and have it show up on the 2nd line.
=> RHICOMPL-521 - Keep popover in ReportCard always visible

src/SmartComponents/ReportsSystems/ReportsSystems.js, src/SmartComponents/ReportsSystems/__snapshots__/ReportsSystems.test.js.snap
This doesn't make the table sortable as I'm not sure how can we do this with the SystemsTable and the inventory component, but it fixes the mismatch in title names with the mocks.
=> RHICOMPL-524 - Match Reports by system table names in mocks

src/SmartComponents/CreatePolicy/EditPolicyRules.js
The EditPolicyRules file is querying some extra info for the selected
rules. However, we only use the Ref ID to check which rules are
selected, and this info is used from the Benchmark Rules GQL call.
=> Remove extra fields from EditPolicyRules

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
With results:
Without results:
Note: The option are disabled, but the dropdown-button remains the same.
=> RHICOMPL-578 - Disable exporting when no items

src/SmartComponents/PoliciesTable/PoliciesTable.js, src/SmartComponents/PoliciesTable/PoliciesTable.test.js, src/SmartComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap
When filtering looking up the policy with per page, index, etc. returns the wrong policy to delete.
This adds the policy id to the rowdata to later use it to find the correct policy to delete.
=> RHICOMPL-606 - Add policy id to rowdata and use for deletion

src/SmartComponents/ReportsSystems/ReportsSystems.js, src/SmartComponents/ReportsSystems/__snapshots__/ReportsSystems.test.js.snap
The SystemsTable onb the "By Systems" page under Reports still shows a compliance score and should also have the filters for it.
=> RHICOMPL-603 - Restore compliant filters on Reports by System

src/SmartComponents/DeletePolicy/DeletePolicy.js, src/SmartComponents/DeletePolicy/__snapshots__/DeletePolicy.test.js.snap
As per RHICOMPL-590, shouldn't be on a new line, but right after the sentence.
=> RHICOMPL-590 - "This cannot..." should not be on a new line

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
This will prevent Inventory filters to persist throughout navigating to other pages.
=> RHICOMPL-597 - Clear inventory filters when loading systems

src/App.scss, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap, src/SmartComponents/Reports/Reports.js, src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap, src/SmartComponents/ReportsSystems/ReportsSystems.js, src/SmartComponents/ReportsSystems/__snapshots__/ReportsSystems.test.js.snap
This should fix the problem we have with different top borders in pages with tabs and without tabs. The end result is what you can see in the gif.
=> Fix tabs-top-border

src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/Reports/Reports.js, src/SmartComponents/SystemDetails/SystemDetails.js
This is meant to prevent https://github.com/apollographql/apollo-client/issues/2510
=> Add ID to fields to avoid apollo-gql error

src/Utilities/ruleHelpers.js
On the SCAP policy details view, systems table - the table is endlessly
loading because it's tries to get the rules passed (the reducer does
this automatically) - but the rules passed just can't be computed based
on the GQL query we make there - since there's no remediation button, we
don't fetch that info.
=> Fix endless loading SystemsTable

src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap, src/SmartComponents/index.js
This fixes the "clunky" loading of SCAP Policies.
Before:
After:
And also the empty state spacing to the top:
=> RHICOMPL-561 - Set loading and error to undefined on data

src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/EditPolicySystems.test.js, src/SmartComponents/PoliciesTable/PoliciesTable.test.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/SystemsTable.test.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap, src/constants.js, src/store/Reducers/SystemStore.js
This puts systems into the inventory store, that is updated with fetching systems.
It is also ensured that systems are fetched and updated prior to `fetchInventory` and is called when filters or paginating changes.
To ensure the table is up to date even when items stay the same there is now an `UPDATE_ROWS` action that will get dispatched and recalculate the rows without triggering a inventory refresh.
It also removes debouncing certain calls, which could lead to states being out of sync. 
The primary objective is to fix the policy creation step to assign systems, but since the `SystemsTable` is used in other places here's a list where to click through:
**On each use of the SystemsTable test:**
* Filter
* by Name
* [Known bug] Subsequent name filter, without clearing filters, won't work
* …
=> RHICOMPL-638 - Fix SystemsTable loading behaviour

src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/PolicyDetails/PolicySystemsTab.js
These sorting buttons are not expected to work without x-join integration, if anyone clicks on them it breaks the table, so I'm disabling them for now.
=> RHICOMPL-647 - Disable sorting on systems table

src/SmartComponents/SystemsTable/SystemsTable.js
Before, we were not getting the attribute from GQL at all, therefore the "(External)" note in the Policies column could not show. It looks like this now:
=> RHICOMPL-618 - Get 'external' attr on SystemsTable GQL

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js, src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.test.js, src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap
This adds a warning to the policy creation wizard when no systems are assigned:
@katierik Could you confirm the text colour? In the mocks it is darker, but I'm unable to find a matching colour.
=> RHICOMPL-604 - Add warning when no systems assigned

src/SmartComponents/SystemsTable/SystemsTable.js
Trying to clear selected entities when there are none will prevent
the table from loading properly.
=> Only try to clear selected when there are some

src/App.scss, src/PresentationalComponents/SystemsCountWarning/SystemsCountWarning.js, src/PresentationalComponents/SystemsCountWarning/SystemsCountWarning.test.js, src/PresentationalComponents/SystemsCountWarning/__snapshots__/SystemsCountWarning.test.js.snap, src/PresentationalComponents/WarningText/WarningText.js, src/PresentationalComponents/WarningText/WarningText.test.js, src/PresentationalComponents/WarningText/__snapshots__/WarningText.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js, src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap, src/SmartComponents/PoliciesTable/PoliciesTable.js, src/SmartComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
Corrects the colour of the warning text in the wizard:
Adds a wardning to the policies table:
And adds a warning to the systems table in the policy details (Difference to mock approved by PM, see ticket):
=> RHICOMPL-604 - Add more warnings when no systems assigned

src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
Currently onWizardFinish runs automatically when the systems have been
assigned to the policy. This function is used mainly to reload the table
of SCAP policies.
Instead, we should only run it when the button is clicked - this allows
us to NOT automatically reload the page when the wizard finishes and we
have just created our **first** policy or a Policy through the Reports
page empty state.
=> RHICOMPL-556 - Run onWizardFinish only when button is clicked

src/PresentationalComponents/ProfileTypeSelect/ProfileTypeSelect.js, src/PresentationalComponents/ProfileTypeSelect/__snapshots__/ProfileTypeSelect.test.js.snap, src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js, src/SmartComponents/CreatePolicy/EditPolicyRules.js, src/SmartComponents/CreatePolicy/EditPolicyRules.test.js, src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap, src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyRules.test.js.snap
This updates the "Rules" step in the policy creation wizard to further match the mockups.
**Test-protocol:**
1. Open the Policy page and the "Create Policy" wizard
2. Fill out steps 1&2 and continue to the "Rules" step.
3. Select or deselect rules
- The rules count should update
- A "Restore to default selection" link should appear
- Clicking should update the selected rules to the default policy rules.
4. Continue to the "Systems" step and return to Rules
* The rules should still match the previously selected ones
5. Return to the first step and change the policy type
6. Go forward to the "Rules" step
* Description and default rules should match the newly selected policy type
7. Continue forward and finish the wizard to create a policy with the selected rules.
=> RHICOMPL-552 - Update rules step in policy wizard

src/SmartComponents/AssignPoliciesModal/AssignPoliciesModal.js
Without this, if:
- you create a policy and then immediately go to the systems table
without a hard refresh, the policy will not show up on the list
- you go from systems -> scap policies, delete a policy -> back to
systems, the policy will still show up as assignable and this will
cause an error if you even attempt it
=> RHICOMPL-729 - Use cache-and-network policy for AssignPoliciesModal

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
Currently, the wizard requests for all visible policies, and compares the intersection of that with the benchmark to remove them - since "all visible policies" include "canonical policies", then no policies are visible. We should get the intersection with "user created policies".
=> Request only internal policies on Wizard

src/SmartComponents/BusinessObjectiveField/BusinessObjectiveField.js, src/SmartComponents/BusinessObjectiveField/BusinessObjectiveField.test.js, src/SmartComponents/BusinessObjectiveField/__snapshots__/BusinessObjectiveField.test.js.snap, src/SmartComponents/CreatePolicy/EditPolicyDetails.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap, src/SmartComponents/ProfileThresholdField/ProfileThresholdField.js, src/SmartComponents/ProfileThresholdField/ProfileThresholdField.test.js, src/SmartComponents/ProfileThresholdField/__snapshots__/ProfileThresholdField.test.js.snap
This essentially moves the headers and descriptions to the tooltips, as the mocks indicate.
:warning: This also changes the Edit Policy menu. I am currently working on a PR to allow re-editing directly on the wizard as in the mocks, so the whole "Edit Policy" modal would go away.
=> RHICOMPL-534 - Update policy details to match mocks

src/SmartComponents/SystemsTable/SystemsTable.js, src/store/Reducers/SystemStore.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
This takes the OS from compliance's DB and puts it as a subtitle under
the Host name as the mocks indicate.
=> RHICOMPL-574 - Add OS to systems table when available

src/SmartComponents/InventoryDetails/InventoryDetails.js, src/SmartComponents/SystemsTable/SystemsTable.js
We are working on inventory refactoring, since we'd like to fully use hooks and such we have to use App's react dependency. With this being used react-redux needs to be passed from application as well. If you are cautious about the size of your bundle I can pick only the functions really required by inventory.
=> Pass react redux to inventory loader as well

.env, .env.example, .eslintignore, .gitignore, Dockerfile, README.md, config/dev.webpack.config.js, config/spandx.config.js, docker-compose.yml, entrypoint.sh
This adds a Docker image and docker compose setup to eventually only have to use `docker-compose build` & `docker-compose up` to get the frontend and insights-proxy up and running for development.
This is based on the setup used for https://github.com/RedHatInsights/notifications-frontend/.
=> Add docker compose setup for development

.env.example, docker-compose.yml
Chrome uses the same image with npm installed as the frontend; we just run `npm ci` to clear out the node_modules and install chrome's.
=> Add config for local chrome

config/spandx.config.js, package-lock.json, package.json
@bastilian Over a satellite connection, 2 seconds is too short to accommodate the latency (~1200ms round trip). If the ESIs time out, then `window.insights` is undefined, like we've seen in my environment.
=> Increase ESI socket timeout to 5 seconds

src/PresentationalComponents/NoSystemsTableBody/NoSystemsTableBody.js, src/PresentationalComponents/NoSystemsTableBody/NoSystemsTableBody.test.js, src/PresentationalComponents/NoSystemsTableBody/__snapshots__/NoSystemsTableBody.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap, src/store/Reducers/SystemStore.js
This updates the warning for policies with no systems on the systems tab in the details according to the mockups:
**Note:** The mockups mention another way to add systems, which is not yet available. Once that changes the copy in this table will be updated as well.
=> RHICOMPL-604 - Update "no systems" warning on systems tab

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
This fixes the issue with the no systems warning showing up on other pages then the policy details systems tab.
=> RHICOMPL-604 - Only show warning for no systems on details page

config/base.webpack.config.js, config/base.webpack.plugins.js
In development the hashing introduces a noticeable lag when it rebuilds.
This will only enable it in production environments.
=> [RHICOMPL-831] Enable filename hashing only on production envs

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/ComplianceSystems/ComplianceSystems.test.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap, src/SmartComponents/SystemsTable/SystemsTable.js, src/constants.js
This enables filters on the Systems page for policy:
and operating systems:
=> RHICOMPL-667 - Enable policy filter on systems page

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/SystemsTable/SystemsTable.js
Editing policies can now be done via the policy edit modal and the "Edit policies" can be removed from the systems view.
=> [RHICOMPL-691] - Remove "Edit policies" action from Systems Page

src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js
There were issues with how the conditions got interpreted with `&&`.
With version numbers like `8.0` it would show just `0`.
This fixes these issues and OS information is correctly shown.
=> [RHICOMPL-574] Fix issues with versions containing 0

src/SmartComponents/EditPolicy/EditPolicy.js
When deselecting systems the reducer will set `selectedEntities` to `undefined` when there are no more systems selected.
The `hosts` property for the `updatedPolicy` should still be updated, but set to an empty array.
Best to test:
1. Create a policy in the wizard assigning only one host
2. Open the Edit Policy modal and remove the host.
Before this change when only one host is assigned it wouldn't allow to unassign this host.
=> [RHICOMPL-742] Always update state for selected entities

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap
When we fixed issues with selecting systems for exporting, we changed `selectedEntities` from containing only IDs to hold the system nodes and did not adjust the selecting of systems for the Remediations button.
How to test:
1) Make sure to have a report with systems that have failed rules, which have remediations available
2) Got a the report details to verify this behaviour:
Before this the behaviour was broken and the "Remediations" button would stay disabled.
Note: To test this with no remediations imported, the `rulesHelpers.js` can be changed to mock this and test the button still:
```
export const systemsWithRuleObjectsFailed = (systems) => (
systems.map(system => (
{
ruleObjectsFailed: systemRulesFailed(system)
.map((r) => ({ ...r, remediationAvailable: [true, …
```
=> [RHICOMPL-784] Provide Remediations button with proper system nodes

src/SmartComponents/PolicyDetails/PolicySystemsTab.js
RHICOMPL-906 actually instructs to remove the Kebab menu from the policy details completely.
=> [RHICOMPL-906] Remove actions from Policy Details completely

src/SmartComponents/SystemDetails/SystemDetails.js, src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap
Note, that the `useLocation().query` from React Router no longer works.
=> [RHICOMPL-732] Default to failed rules on systems detail page

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/SystemsTable/SystemsTable.js
In order to show proper RBAC state in systems table we need to pass `fullView` prop to inventory component. This applies only to systems page as it's the only place where inventory table is just one component on screen. Without this prop the `unAuthorized` component would be in table, which is not correct based on our mocks.
[1] https://github.com/RedHatInsights/frontend-components/blob/master/packages/inventory/doc/inventory.md#using-rbac-with-inventory
=> [RHICOMPL-974] Mark systems table as full view

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/SystemsTable/SystemsTable.js
This adds a dismiss-able Info message to the Systems page:
=> [RHICOMPL-977] Add info about what systems are shown

src/PresentationalComponents/NoResultsTable/NoResultsTable.js, src/PresentationalComponents/NoResultsTable/NoResultsTable.test.js, src/PresentationalComponents/NoResultsTable/__snapshots__/NoResultsTable.test.js.snap, src/PresentationalComponents/PolicyPopover/PolicyPopover.js, src/PresentationalComponents/PolicyPopover/PolicyPopover.test.js, src/PresentationalComponents/PolicyPopover/__snapshots__/PolicyPopover.test.js.snap, src/PresentationalComponents/ReportCard/ReportCard.js, src/PresentationalComponents/ReportCardGrid/ReportCardGrid.js, src/PresentationalComponents/ReportsEmptyState/ReportsEmptyState.js, src/PresentationalComponents/ReportsEmptyState/ReportsEmptyState.test.js, src/PresentationalComponents/ReportsEmptyState/__snapshots__/ReportsEmptyState.test.js.snap, src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/Cells.test.js, src/PresentationalComponents/ReportsTable/Filters.js, src/PresentationalComponents/ReportsTable/Filters.test.js, src/PresentationalComponents/ReportsTable/ReportsTable.js, src/PresentationalComponents/ReportsTable/ReportsTable.test.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap, src/PresentationalComponents/ReportsTable/__snapshots__/Filters.test.js.snap, src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/Reports/Reports.js, src/SmartComponents/Reports/Reports.test.js, src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap, src/Utilities/hooks/useFeature.js, src/Utilities/hooks/useFilterConfig.js, src/Utilities/hooks/useTableSort.js, src/__fixtures__/policies.js, src/constants.js
This implements a table view for reports:
It can be enabled via https://prod.foo.redhat.com:1337/insights/compliance/reports?reportsTableView=enable and disabled by using `disable` instead.
=> [RHICOMPL-680] Implement reports as a table view

src/SmartComponents/CreatePolicy/EditPolicyRules.js
Resources requested from GraphQL should have an ID to avoid issues with "caching" when re-requesting data.
The issue can be reproduced (without this fix) by opening the "Create policy" wizard twice.
The rules step will throw an error, with this fix the error does not appear and the rules step works as expected.
=> fix(RHICOMPL-730): Request IDs for resources over GraphQL

babel.config.js, src/SmartComponents/CreatePolicy/EditPolicyRules.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyRules.test.js.snap, src/SmartComponents/PolicyDetails/PolicyRulesTab.js
Just to be consistent and use the same icon as we do/will in `inventory-compliance`
=> refactor: Update Ansible icons to use patternfly version

src/SmartComponents/CreatePolicy/EditPolicyRules.js
The Rule step in the wizard was still failing for opening it a second time.
Giving an ID to benchmarks has solved the issue for RHEL + Policy Type where it would raise an error before this change.
Please see Jira for these cases and how to reproduce the issue.
=> fix(RHICOMPL-730): Add id for benchmark object as well

src/PresentationalComponents/PoliciesTable/PoliciesTable.js, src/SmartComponents/CompliancePolicies/__snapshots__/CompliancePolicies.test.js.snap
https://github.com/RedHatInsights/compliance-frontend/pull/779 Remove the withRouter decorator, which causes the actionResolver functions not to work properly.
=> fix(RHICOMPL-1023): Add withRouter back to make actions work again

package-lock.json, package.json, src/SmartComponents/CreatePolicy/EditPolicyRules.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyRules.test.js.snap, src/SmartComponents/PolicyDetails/PolicyRulesTab.js
This uses the helper function to get column definitions for the rules table introduced with https://github.com/RedHatInsights/frontend-components/pull/765 and will also fixes the issues with html in the tooltip, by avoiding it.
=> fix(RHICOMPL-880): Use selectRulesTableColumns to not redefine columns

src/PresentationalComponents/PolicyPopover/PolicyPopover.js, src/PresentationalComponents/PolicyPopover/__snapshots__/PolicyPopover.test.js.snap, src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap
Custom policy name should be shown primarily on the Reports table, and the canonical policy name shown underneath.
The same should be shown on the Policy Popover.
=> fix(RHICOMPL-1014): Show custom policy name primarily on Reports table and Popover

src/SmartComponents/SystemsTable/SystemsTable.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
This changes the systems view in the UI to determine if a policy is
external by looking at the profile's policy attribute rather than the
external attribute.
=> fix(RHICOMPL-1052): external profiles means no policy

src/SmartComponents/SystemsTable/SystemsTable.js
querying GQL `policy_id`, which also accepts profile id of policy that
the system is assigned to.
Requires backend changes RedHatInsights/compliance-backend#629
=> fix(RHICOMPL-1069): SystemsTable to show systems for a policy

src/PresentationalComponents/ReportsTable/Filters.js, src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap
Follow up to https://github.com/RedHatInsights/frontend-components/pull/761
=> fix(RHICOMPL-1005): Correct filter name on reports table

src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js, src/SmartComponents/CompliancePolicies/CompliancePolicies.js, src/SmartComponents/PolicyDetails/PolicyDetails.js
A new attribute, policyType, is now exposed on a profile. This updates
the policy details page to use it.
Requires https://github.com/RedHatInsights/compliance-backend/pull/642
=> [RHICOMPL-959] Use policyType field in policy details

src/SmartComponents/Reports/Reports.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js
The reports page should group profiles by policy.
It queries internal profiles (act as a policy to a user) that have a
policy test result, and, it queries external profiles (not part of any
policy) that have a test result
Policy systems are aggregated from all policy profiles, by
leveraging filtering of system by a policy on GraphQL.
**Requires backend RedHatInsights/compliance-backend#647**
Please note, that the policy deduplication on Systems page will be done in separate PR.
=> [RHICOMPL-1027] Group reports by policy and aggregate systems

src/PresentationalComponents/GreySmallText/GreySmallText.js, src/PresentationalComponents/GreySmallText/GreySmallText.test.js, src/PresentationalComponents/GreySmallText/__snapshots__/GreySmallText.test.js.snap, src/PresentationalComponents/PoliciesTable/PoliciesTable.js, src/PresentationalComponents/PoliciesTable/PoliciesTable.test.js, src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap, src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/Cells.test.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/CompliancePolicies/CompliancePolicies.js
The policies table should show user-defined policy name and policy type.
Please note, that the policy name is still buggy because of caching (RHICOMPL-1077).
=> fix(RHICOMPL-1104): policies table to show policy type policy name

src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap, src/Utilities/hooks/useFeature.js, src/constants.js
This enables the the `ReportsTable` to be the default view for the Reports page.
=> feat(reports): RHICOMPL-1117 - Enable table view by default

src/SmartComponents/CompliancePolicies/CompliancePolicies.js
Essential identifier seemed to be missing.
Here is the error:
```
Error writing result to store for query:
Store error: the application attempted to write an object with no provided id
but the store already contains an id of Profile:UUID for this object.
The selectionSet that was trying to be written is: ...
```
=> fix(CompliancePolicies): RHICOMPL-1128 Apollo error on refetch

src/App.scss, src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy.test.js, src/SmartComponents/CreatePolicy/__snapshots__/FinishedCreatePolicy.test.js.snap, src/__fixtures__/benchmarks_rules.js
Adds reasons list on create policy wizard in case there is an error.
Set width of messages and reasons container ensures that the text will
wrap at the with of the progress bar.
=> feat(FinishedCreatePolicy): RHICOMPL-1147 show errors

src/SmartComponents/SystemsTable/SystemsTable.js, src/__fixtures__/systems.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
**Requires backend RedHatInsights/compliance-backend#670**
Fixes duplicate policy names on the "Policies" table column by using fetched policy names from backend.
External policies are temporary, taken from the list of profiles.
=> fix(SystemsTable): RHICOMPL-1096 show unique policy names in the column 

src/SmartComponents/SystemsTable/SystemsTable.js, src/__fixtures__/systems.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
**Requires backend RedHatInsights/compliance-backend#670**
Fixes showing only reported SSG versions in the table by pulling testResultProfiles out of backend, instead of combined
`profiles` field (assigned and test result profiles).
=> fix(SystemsTable): RHICOMPL-1137 show reported SSG version(s)

src/SmartComponents/Reports/Reports.js
With the next deployment, reports are no longer parsed. Warn the user
that this is the case and that external reports will eventually be
removed.
=> feat(reports): RHICOMPL-1179 Update external support message

src/PresentationalComponents/ComplianceScore/ComplianceScore.js, src/PresentationalComponents/ComplianceScore/ComplianceScore.test.js, src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap, src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/Cells.test.js, src/PresentationalComponents/ReportsTable/ReportsTable.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap, src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap, src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js, src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.test.js, src/PresentationalComponents/UnsupportedSSGVersion/__snapshots__/UnsupportedSSGVersion.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/PolicyDetails/PolicySystemsTab.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/ReportDetails.test.js, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap, src/SmartComponents/Reports/Reports.js, src/SmartComponents/SystemsTable/Cells.js, src/SmartComponents/SystemsTable/SystemsTable.js, src/__fixtures__/systems.js, src/store/Reducers/SystemStore.js, src/store/Reducers/__snapshots__/SystemStore.test.js.snap
Copied from https://github.com/RedHatInsights/compliance-frontend/pull/829/files, rebased against master.
Backend requirement: https://github.com/RedHatInsights/compliance-backend/pull/672
RHICOMPL-690
RHICOMPL-682
RHICOMPL-685
RHICOMPL-683
RHICOMPL-1007
Reports:
Report details:
Policy details -> Systems:
Tooltips on warning icons:
=> feat: Implement unsupported SSG version warning

src/Utilities/__snapshots__/ruleHelpers.test.js.snap, src/Utilities/ruleHelpers.js, src/Utilities/ruleHelpers.test.js
The remediation button on Report detail page was not working due to
incorrect read from the system's data.  Instead of `profiles` the
rules passed to the remediation button should be collected from
`testResultProfiles`.
=> fix(Reports): RHICOMPL-1189 remediation button

src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
So, the patternfly donut chart doesn't behave as expected (as shown in the patternfly demo/docs site). This hacks it to look as expected with 0 compliant hosts. The solution matches what we've done in the dashboard as well (copied from Advisor). I'm only fixing it here now because the dashboard folks wanted it fixed there before merging the supportability work.
Before:
After:
=> fix(donut): RHICOMPL-1197 Empty donuts are gray

src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/Cells.test.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap
The external policy should show unsupported beneath the operating system
label only if there are any unsupported hosts results reporting against
the policy.
Note for screenshots below, SSG version 0.1.43 is supported on RHEL 7.7
Before:
After:
=> fix(ReportsTable): RHICOMPL-1206 Properly indicate unsupported

src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
Unsupported text next to the warning icon should be
--pf-global--warning-color--200 to match the mocks
Reports:
Policies: (no changes)
Systems: (see [frontend-components PR](https://github.com/RedHatInsights/frontend-components/pull/847))
=> fix(unsupported text): RHICOMPL-1207 Darker yellow

src/SmartComponents/PolicyDetails/PolicySystemsTab.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/SystemsTable/Cells.js
Before a system has uploaded any reports, the SSG version returned from
the API is a blank string. The SSGVersion component should render
'Not available' in that case.
=> fix(SSGVersion): RHICOMPL-1233 Handle unknown SSGs

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js, src/__fixtures__/benchmarks_rules.js
The "In Used" label, placed on profiles that already exist, would work
policy-wide.  This prevents error from the backend and adds to UX.
It compares benchmark's ref_ids that are tigthly coupled with OS major
version.
=> fix(CreateSCAPPolicy): RHICOMPL-1161 policy-wide profile In Use label

Dockerfile, docker-compose.yml, entrypoint.sh
This replaces the Fedora image with the RHEL 8 UBI image as the base for docker.
(Shamelessly stolen from https://github.com/RedHatInsights/sources-ui)
=> chore(docker): Use RedHat UBI image

src/SmartComponents/Reports/Reports.js
This message is meant to ship at the same time we remove any remaining
external policies from Compliance. It will be removed in mid-Feb with
RHICOMPL-1298.
=> feat(Reports): RHICOMPL-1230 Update external policy message

src/SmartComponents/SystemsTable/InventoryTable.js
When using the default filter it can happen that `or` and `and` get not evaluated as expected, grouping the filters will fix that.
=> fix(InventoryTable): RHICOMPL-1396 - Combine filters properly

src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js, src/SmartComponents/CreatePolicy/EditPolicyDetails.js, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js, src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.test.js, src/SmartComponents/CreatePolicy/validate.js, src/SmartComponents/CreatePolicy/validate.test.js, src/__fixtures__/benchmarks_rules.js
Uses new `osMajorVersion` state in the wizard form to keep track of the OS major version for Systems to be filtered on. The `InventoryTable` gets passed the query to trigger the use of the filter. This would be refactored to `getEntities` later.
Requires backend: https://github.com/RedHatInsights/compliance-backend/pull/742
=> feat(CreatePolicy): RHICOMPL-701 filter systems by OS major version 

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/ComplianceSystems/ComplianceSystems.test.js, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/PolicyDetails.test.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/ReportDetails.test.js, src/SmartComponents/SystemsTable/InventoryTable.js, src/store/Reducers/SystemStore.js
This change ensures the redux state stays set as intended. This includes
the rendered columns and rows as well as whether the table is loaded or
not.
It is **very important** to realize that the redux actions in our
SystemStore have (basically) no guarantee of any execution order. One
exception is the *_PENDING and *_FULFILLED actions, which always happen in
that order but still may have other actions happen in between.
This adds a GET_SYSTEMS_PENDING action to allow compliance to reset
columns and rows in addition to system information when our API
request begins. This is necessary to ensure old state is not persisted
into a new table, such as when viewing policy systems and then
immediately editing policy systems without refreshing.
Additionally, there was a bug in EditPolicy, which …
=> fix(InventoryTable): RHICOMPL-1442 redux states

src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js
It seems the url for this page changed slightly without us being notified. The link is defined in frontend components also, so I've opted to export it there. This PR required https://github.com/RedHatInsights/frontend-components/pull/992.
=> fix(supported popover): RHICOMPL-1461 update docs link

.env.example, config/devserver.config.js, entrypoint.sh
This corrects the binding behaviour of webpack dev server when it is running within a container.
=> chore(container): Correct webpack binding in container

src/SmartComponents/PolicyDetails/PolicySystemsTab.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap
The export feature in the systems tab under a specific policy crashes on a wrong field key for the SSG version field. I'm not sure if I'm doing the fix correctly and/or how should I test this, except of verifying it in the UI.
This is a typical case of the meme which I was not able to find as a picture:
*- Why ˙!=˙*
*- Because ˙==˙ crashed*
=> fix(PolicySystems): RHICOMPL-1519 changed ssg version field key

src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/EditPolicyRules.js, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/Utilities/helpers.js, src/Utilities/helpers.test.js, src/store/Reducers/SystemStore.js, src/store/Reducers/SystemStore.test.js
Gathers OS minor versions of selected systems within the PolicyCreate wizard using `countOsMinorVersions` reducer. The result is sorted naturally.
Adds a PoC within the Rules step in the wizard to see the result (requires `?multiversionTabs=enable`). This PoC would likely be fully replaced/reverted with implementation of the tabs for each OS version. One step at a time...
PoC ("Tailoring for ...")
=> feat(CreatePolicy): RHICOMPL-1521 gather selected OS minor versions

src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
The Policies column has been replaced with the OS version which has been extracted from beneath the display name.
Just for the sake of consistency, should this column also be displayed for the non-wizard when editing a policy?
=> feat(CreatePolicy): RHICOMPL-1546 display OS version for systems

src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/CreatePolicy.test.js, src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap, src/SmartComponents/CreatePolicy/validate.js
Added a validation that prevents the wizard to continue from the systems step if no systems are selected. 
Is the snapshot sufficient for testing here, or should I add something else and if yes, where and what?
Should this validation also happen when editing a policy?
=> feat(CreatePolicy): RHICOMPL-1548 validate >0 systems selection

package-lock.json, package.json, src/PresentationalComponents/TabbedRules/__snapshots__/TabbedRules.test.js.snap, src/SmartComponents/CreatePolicy/EditPolicyRules.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyRules.test.js.snap
Use the remediationAvailableFilter in the rules table within the policy
wizard. We may use this filter elsewhere in the future, anywhere that we
display remediation availability, but for now, this only adds the filter
to the wizard's rules table.
Requires https://github.com/RedHatInsights/frontend-components/pull/1039
=> feat(CreatePolicy): RHICOMPL-1549 Use remediationAvailableFilter

src/SmartComponents/CreatePolicy/EditPolicyDetails.js, src/SmartComponents/CreatePolicy/EditPolicyDetails.test.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicyDetails.test.js.snap
When a user selects a different Policy type and/or RHEL major version,
the name and description of a policy is reset based on the values from
the selected policy type.
=> fix(CreatePolicy): RHICOMPL-484 new name and description on reselect 

src/SmartComponents/CreatePolicy/CreatePolicy.js
This happens when the wizard first loads:
```
Warning: Failed prop type: Invalid prop `complianceThreshold` of type `number` supplied to `CreatePolicy`, expected `string`.
```
=> fix(CreatePolicy): default prop threshold should be a string

src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/SystemsTable/InventoryTable.js, src/SmartComponents/SystemsTable/InventoryTable.test.js, src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
Added optional `emptyStateComponent` and `titleComponent` attributes to the `InventoryTable` component that are invoked from the `SystemInventory` in the create policy wizard. The goal is to show an informative message if there are no systems available with the selected OS major version and provide a button to go back two steps to reselect the OS major.
=> feat(CreatePolicy): RHICOMPL-1547 implemented empty state for systems

src/PresentationalComponents/PoliciesTable/__snapshots__/PoliciesTable.test.js.snap, src/PresentationalComponents/ReportCardGrid/__snapshots__/ResportsCardGrid.test.js.snap, src/PresentationalComponents/ReportDetailsDescription/__snapshots__/ReportDetailsDescription.test.js.snap, src/PresentationalComponents/ReportsTable/__snapshots__/Filters.test.js.snap, src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap, src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/__snapshots__/FinishedCreatePolicy.test.js.snap, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicy.test.js, src/SmartComponents/EditPolicy/usePolicy.js, src/SmartComponents/EditPolicy/usePolicyUpdate.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap, src/Utilities/graphql/mutations.js, src/__fixtures__/policies.js
Policy creation, editing, and viewing should work as expected, including: Policy fields (name, threshold, etc.) business objective, system assignment, and rule assignment.
Resolved issues:
And some that still exist that we should fix, perhaps in a new PR so break up the work:
- error handling for all API calls; we might handle errors in another PR. It's not so trivial since usePolicyUpdate was not written to consider error handling for all API calls (only policy creation mutation)
- not handled: when the profile doesn't exist in the requested benchmark (i.e. 0.1.45 and CIS). This scenario results in a 'missing' tab for those versions where the profile isn't available. We'll need to handle this somehow, probably with COMP-E-178 (filter hosts by policy type).
I've tried to split this work …
=> feat: usePolicyUpdate -> usePolicy for create or edit

src/SmartComponents/CreatePolicy/EditPolicyDetails.js
Name and Description were not editable unless the other fields were
edited first.  The useEffect was called on each Name/Desc. field value
change resetting it to original profile value(s).
=> fix(PolicyCreate): RHICOMPL-484 editing Name and Description

src/PresentationalComponents/SupportedSSGVersionsLink/SupportedSSGVersionsLink.js, src/PresentationalComponents/SupportedSSGVersionsLink/SupportedSSGVersionsLink.test.js, src/PresentationalComponents/SupportedSSGVersionsLink/__snapshots__/SupportedSSGVersionsLink.test.js.snap, src/PresentationalComponents/TabbedRules/OsVersionText.js, src/PresentationalComponents/TabbedRules/ProfileTabContent.js, src/PresentationalComponents/UnsupportedSSGVersion/UnsupportedSSGVersion.js, src/PresentationalComponents/index.js
Refactors the Supported SSGs link to a separate component.
Adds the popover next to the SSG version within the rules tab content.
Adds the external icon icon.
Updates the popover wording to match the behavior.
=> feat(Rules): RHICOMPL-1551 add SSG popover to tab content f483843 

src/SmartComponents/PolicyDetails/EditRulesButtonToolbarItem.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/PolicyDetails.test.js, src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js, src/SmartComponents/PolicyDetails/PolicyRulesTab.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyDetails.test.js.snap
Show canonical rule set if the policy was not yet tailored by each of
the OS minor version out of the assigned systems.
Unifies GraphQL query with some slight redundancy, and drops the
useFeature hook.
Show an Alert for OS-untailored policies.
=> fix(PolicyDetails): RHICOMPL-1627 untailored policy by OS version

.eslintrc.yml, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.test.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
Builds on https://github.com/RedHatInsights/compliance-frontend/pull/1104
When selecting systems in the edit policy modal, alert users to new OS
minor versions and their new associated rule sets for tailoring.
=> feat(EditPolicy): RHICOMPL-1356 Alert user to new rule sets

src/SmartComponents/CreatePolicy/CreatePolicy.js
Added an additional condition to the `canJumpTo` attribute in each wizard step after the systems. This way if the user goes back and deselects all systems, there will be no way to go forward in the wizard and create a policy without systems.
=> fix(PolicyCreate): RHICOMPL-1636 no wizard jumps if no systems selected

src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
Reproducer:
1. Create a policy with with a type (refId) that isn't available in some available OS minor versions. (example: NIST)
2. Select 7.9 systems as well as lower versions that do not have that type (NIST)
3. Finish and create.
4. Open edit modal and select Rules tab.
=> fix(EditPolicy): RHICOMPL-1683 crash on missing canonical profile

src/SmartComponents/EditPolicy/EditPolicyRulesTab.js, src/Utilities/hooks/api/useCollection.js
* fixes showing spinner in the edit modal early, especially if the policy does not have tabs configured yet
* with added `skip` option to `useCollection`
* fixes `useCollection` to reset to default on effects variable change, which fixes showing spinner right after user selects a system from a new OS minor group
* fixes showing spinner only if the new data are being still being loaded (old were shown right under the spinner)
Note, I haven't experienced any issues with the Create Policy Wizard regarding a missing loading state.
=> fix(EditPolicy): RHICOMPL-1651 rules loading states 

src/SmartComponents/EditPolicy/EditPolicyRulesTab.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.test.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicyRulesTab.test.js.snap
This empty state occurs when there are no tabs on the policy due to
having no systems.
Also adds a very rudimentary test for this tab component, which was missing.
=> feat(EditPolicyRulesTab): RHICOMPL-1684 empty state

src/SmartComponents/SystemsTable/InventoryTable.js
The empty component passed in should only be used when it is not filtered by a user filter.
=> fix(InventoryTable): RHICOMPL-1682 - Only show empty state when not filtered

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js, src/SmartComponents/CreatePolicy/__snapshots__/ReviewCreatedPolicy.test.js.snap
~I checked the fonts and line heights, and the review step already matches those exact values in the mocks, so I don't think there's anything to change there.~ I found an extra margin-top, which is the default for the h3 it was attached to, but the mock doesn't show this, so I've forced it to 0.
=> fix(ReviewCreatedPolicy): Show N system(s) during review

src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap, src/SmartComponents/SystemsTable/hooks.js, src/constants.js
Before this the filter would appear (miss-configured) on Systems page.
=> fix(InventoryTable): RHICOMPL-1476 - Only return OS filter when enabled

src/SmartComponents/EditPolicy/EditPolicyDetailsTab.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicyDetailsTab.test.js.snap
The `Form` component from PF applies a grid on its direct child `FormGroup` components, but it doesn't when the children are for example under a tab. So I am abusing the `pf-c-form` class on a wrapping `<div>` in order to have the same look&feel.
**Before:**
**After:**
=> fix(EditPolicyDetails): RHICOMPL-1692 apply the form grid on fields

src/SmartComponents/CreatePolicy/FinishedCreatePolicy.js
The `EmtpyStateWithErrors` component crashes if there are no errors after saving the form. By adding a fallback to return `null` the problem should go away.
=> fix(PolicyCreate): RHICOMPL-1722 return null when no errors

src/SmartComponents/CreatePolicy/EditPolicyProfilesRules.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
This affects the create policy wizard and the edit policy modal.
This changes the benchmarks query used to build tabs based on which SSG
versions are supported on which OS versions from a REST query to using
GraphQL. I've seen this REST request take 1-2 seconds to complete, but
in GraphQL with only the attributes we need, it takes something like
35ms.
~I'm seeing the following error on the create policy wizard: `Uncaught Error: EmtpyStateWithErrors(...):` I investigated a bit but so far haven't figured out what the issue is.~ Fixed with unrelated PR. The edit policy modal should work as expected.
Requires https://github.com/RedHatInsights/compliance-backend/pull/809
=> feat(TabbedRules): RHICOMPL-1719 use GraphQL instead of REST

src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js, src/SmartComponents/CreatePolicy/CreateSCAPPolicy.test.js, src/SmartComponents/CreatePolicy/__snapshots__/CreateSCAPPolicy.test.js.snap
This replaces the Button used in the WIzard for the OS selection with the Tile component:
https://user-images.githubusercontent.com/7757/115801423-07451580-a3dd-11eb-9895-f6404b565fd2.mp4
=> fix(CreatePolicy): RHICOMPL-1020 - Use Tile component instead of Button

src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicyForm.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap
The updatedPolicy has been set more than once in EditPolicyForm whithin
three different useEffect callbacks.  Because the effects did not have it
as a dependency (for triggering reasons) they do not get the updated
content from the previous useEffect.  Since these useEffects can fire
all at the same time, one would not get the update from the other.  This
fixes this by splitting it to three separate state variables.
=> fix(EditPolicy): RHICOMPL-1742 save button disabled on empty systems (split)

src/SmartComponents/EditPolicy/EditPolicyForm.js
Before, when updating the selected systems (not even adding or removing new
OS tabs), the rule selections were reset to the original policy's rule
selections. This change keeps the rule selection reset only when the
modal is first loaded (`useEffect(..., [policy])`).
I'm not sure when this `updateSelectedRuleRefIds` function was added to the useEffect for policy updates, so it's possible this re-introduces a different bug I'm not aware of.
=> fix(EditPolicy): RHICOMPL-1755 Keep rule selections when systems change

src/SmartComponents/EditPolicy/EditPolicyForm.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.test.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.test.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
The new rules alert should only show when new tabs appear. This PR fixes
an issue where the alert appeared for new systems, despite not having
a valid policy type due to the OS version. This solution highlights the
performance issue with the rules tab requesting all benchmark rules.
This request is required to determine if the newly added system OS
versions have this policy type, so the alert is quite sluggish, on the
order of 1-2 seconds, to update when new systems are selected. I'm
hopeful we'll optimize the rules tab queries, which will also fix this
sluggish alert.
I've reported this API sluggishness as RHICOMPL-1706.
=> fix(EditPolicySystemsTab): RHICOMPL-1697 new rules alert

src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/__snapshots__/CreatePolicy.test.js.snap, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
Remove all specific pixel values and rely on isLarge in the modal.
Additionally, set the modal position to 'top' to tie it to the top
of the screen so the tabs don't change absolute position on the
screen as the user switches tabs.
I'll address the remaining changes on RHICOMPL-1701 in a different PR.
=> fix: RHICOMPL-1701 Adjust wizard and modal sizes

src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicy.test.js.snap
This fixes the button placement on screens smaller than 768px. The issue
will still be present on screens smaller than about 550px, but that should be
much less common.
Even at 564px screen height:
=> fix(EditPolicy): RHICOMPL-1701 Reduce minHeight to 350px

src/PresentationalComponents/RulesTable/RulesTable.js, src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js, src/SmartComponents/PolicyDetails/PolicyRulesTab.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicyMultiversionRules.test.js.snap
When moving to the new `RulesTable` the "Edit rules" button on the Policy details page got lost.
This fixes the issue and uses the `dedicatedAction` of the `PrimaryToolbar`.
=> fix(PolicyDetails): RHICOMPL-1900 - Use dedicatedAction for Edit rules button

src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap, src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap, src/SmartComponents/SystemsTable/Columns.js
Using `fitcontent` would cause columns to unneccesaarily shrink and lead to undesired column widths especially with the last column:
Using `nowrap` instead still mitigates column headers to not truncate, but does not cause odd column widths:
=> fix(SystemsTable): RHICOMPL-1799 - Use nowrap instead of fitcontent

src/PresentationalComponents/TabbedRules/ProfileTabContent.js, src/SmartComponents/CreatePolicy/CreateSCAPPolicy.js
Similar to https://github.com/RedHatInsights/compliance-frontend/pull/1264, this removes the style prop to fix the alignment of the icon.
Before:
After:
=> fix(CreatePolicy): RHICOMPL-1815 - Remove style props to fix aligment

src/Utilities/__snapshots__/helpers.test.js.snap, src/Utilities/helpers.js, src/Utilities/helpers.test.js
Sorting the `orderArray` instead of the array with items, apparently didn't work. 
I'm unsure why it doesn't work anymore or why it worked before. 🤷 
=> fix(TableTools): RHICOMPL-942 - Sort items not orderArray

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/RulesTable/RulesTable.test.js, src/PresentationalComponents/RulesTable/__snapshots__/RulesTable.test.js.snap
The `RulesTable` is not passing on custom options for the table properly, which caused the options being overwritten via the `rulesTableProps` when a custom `options` prop is passed in.
=> fix{RulesTable): Pass on custom table options

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/SystemsTable/hooks.js, src/constants.js
This enables the OS minor version filter for the `ComplianceSystems` component  and enables the group selection option (to be) introduced for the group filter[0].
https://user-images.githubusercontent.com/7757/118270604-93b89480-b4c0-11eb-81d9-18985cca2d61.mp4
⚠️ For the group selection to work the `frontend-components` package needs to be linked in `LOCAL_CHROME`, not compliance-frontend.
[0] https://github.com/RedHatInsights/frontend-components/pull/1112
=> feat(Systems):  RHICOMPL-1716 - Enable OS minor version filter for policy OS versions

src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap, src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap, src/SmartComponents/SystemsTable/Cells.js, src/SmartComponents/SystemsTable/Columns.js, src/SmartComponents/SystemsTable/Columns.test.js, src/SmartComponents/SystemsTable/InventoryTable.js, src/SmartComponents/SystemsTable/__snapshots__/Columns.test.js.snap, src/SmartComponents/SystemsTable/__snapshots__/hooks.test.js.snap, src/SmartComponents/SystemsTable/constants.js, src/SmartComponents/SystemsTable/hooks.js, src/SmartComponents/SystemsTable/hooks.test.js, src/store/Reducers/SystemStore.js
This adds sorting to the SystemsTable. For now only for the name and operating system column, and only in the Wizard, but we can gradually add more columns when we implement the backend part for them.
https://user-images.githubusercontent.com/7757/122219630-e9150680-ceaf-11eb-9e7a-703117929705.mp4
=> feat(SystemsTable): RHICOMPL-1657 - Pass filters and orderBy to API

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/EditPolicy/EditPolicySystemsTab.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap, src/SmartComponents/PolicyDetails/PolicySystemsTab.js, src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap, src/SmartComponents/SystemsTable/Columns.js, src/SmartComponents/SystemsTable/InventoryTable.js, src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap, src/SmartComponents/SystemsTable/constants.js, src/SmartComponents/SystemsTable/hooks.js, src/constants.js, src/store/Reducers/SystemStore.js
This adds the capability to filter systems by tags. This is dependent on https://github.com/RedHatInsights/compliance-backend/pull/927 for the filtering to be actually effective. 
Can be enabled via: https://qa.foo.redhat.com:1337/insights/compliance/systems?tags=enable
=> feat(SystemsTable): Enable tags and tag filtering

src/PresentationalComponents/LoadingPoliciesTable/LoadingPoliciesTable.js, src/PresentationalComponents/LoadingPoliciesTable/__snapshots__/LoadingPoliciesTable.test.js.snap, src/PresentationalComponents/PoliciesTable/Columns.js, src/PresentationalComponents/PoliciesTable/PoliciesTable.js, src/PresentationalComponents/ReportsTable/Columns.js, src/PresentationalComponents/ReportsTable/ReportsTable.js
In other environments it appears that columns are loaded out of order. Object.values should iterate over property values as they appear, so a more likely culprit might be webpack here. 
Providing the columns in a fixed array to define their order should avoid the input to Object.values being random.
=> fix: RHICOMPL-1473 - Provide columns in fixed array

Dockerfile, README.md, docker-compose.yml
This removes the insights-proxy from our docker-compose devel setup
Related/tested with https://github.com/RedHatInsights/compliance-frontend/pull/1315
=> devel: useProxy in webpack with docker-compose

config/dev.webpack.config.js
This should work the same way it used to with insights-proxy. We support
all the local APIs specified in the .env.example. Test it out with the backend docker-compose!
=> devel: Proxy local APIs with webpack proxy

src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/SystemDetails/ComplianceDetail.js
Disabling the cache should in the best case solve the issue of outdated data or at least allow us to rule it out as a culprit if it does not solve the issue. The only side effect to this is that it will query the API and disregard any values in the (apollo) cache.
=> fix(GraphQL): RHICOMPL-2142 - Set no-cache as fetchPolicy

src/SmartComponents/EditPolicy/EditPolicySystemsTab.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.test.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
Always show assigned hosts in the edit policy -> systems modal, even if
hosts are upgraded to a new major version. This allows users to remove
hosts that no longer belong in their policy. We could handle this better
in the future.
=> fix(EditPolicy): RHICOMPL-2190 Always show assigned hosts

src/SmartComponents/SystemDetails/ComplianceDetail.js, src/SmartComponents/SystemDetails/NoPoliciesState.js, src/SmartComponents/SystemDetails/NoPoliciesState.test.js, src/SmartComponents/SystemDetails/NoReportsState.js, src/SmartComponents/SystemDetails/NoReportsState.test.js, src/SmartComponents/SystemDetails/__snapshots__/NoPoliciesState.test.js.snap, src/SmartComponents/SystemDetails/__snapshots__/NoReportsState.test.js.snap
Add the NoPoliciesState and NoReportsState empty state components to the SystemDetails page.
Replaces https://github.com/RedHatInsights/frontend-components/pull/1177
No policy:
Yes policy, no test results:
=> feat(SystemDetails): RHICOMPL-1449 NoPolicies, NoReports empty states

.env.example, config/dev.webpack.config.js, src/PresentationalComponents/SystemPolicyCards/SystemPolicyCards.test.js, src/PresentationalComponents/SystemPolicyCards/__snapshots__/SystemPolicyCards.test.js.snap
The local node module resolution should not be needed anymore and currently causes issues locally linking the `frontend-components` packages.
We initially added this because of the react/react-dom issues resolving for our inventory-compliance package, this should not be needed anymore since we are not using that package anymore and these issues have been resolved in general.
This still leaves it in, but doesn't enable it by default.
=> fix(devtools): Disable local node_module resolution

config/dev.webpack.config.js, config/prod.webpack.config.js
jira: https://issues.redhat.com/browse/RHCLOUD-16201
The inventory compliance was not loaded because the module was not exposed in prod webpack config.
Also, the RootApp in dev env was pointing to an incorrect js file. This is probably why there were two app instances in dev env.
=> Fix federated modules entries.

src/SmartComponents/SystemsTable/InventoryTable.js, src/SmartComponents/SystemsTable/InventoryTable.test.js, src/SmartComponents/SystemsTable/__mocks__/InventoryTableMock.js, src/SmartComponents/SystemsTable/__mocks__/useFetchSystemsMockBuilder.js, src/SmartComponents/SystemsTable/__snapshots__/InventoryTable.test.js.snap
This prevents issues when tags are enabled and a user filters with them, the "Create Policy" wizard and "Edit Policy" modal would show the empty state instead of the systems table, and block any further selection of systems.
=> fix(SystemsTable): RHICOMPL-2206 - Prevent EmptyState issues when tag filtering

src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap
Also removes the complaint in tests/console like:
```
console.warn
One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
at Progress.render (node_modules/@patternfly/react-core/src/components/Progress/Progress.tsx:111:15)
at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:17485:31)
at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:17435:24)
at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19073:16)
at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23940:14)
at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
at renderRootSync …
```
=> fix(ReportsTable): Give compliant systems progress an aria-label

src/Utilities/hooks/useTableTools/helper.js, src/Utilities/hooks/useTableTools/useTableTools.js
This fixes an issue where filters won't be applied to the export.
*How to test?*
1. Visit any page that contains a rules table
2. Export a CSV/JSON and verify all rules are included
3. Apply filters
4. Export CSV/JSON and verify that only the filtered result is exported
=> fix(TableTools): RHICOMPL-2432 - Apply filter and sorting to export

src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js
Adds a disabled fallback button to avoid a spinner when async loading the real button component.
*Before:*
https://user-images.githubusercontent.com/7757/140032112-0f1094ea-3e9a-4029-9eac-11895ce7e91b.mp4
*After:*
https://user-images.githubusercontent.com/7757/140032162-c9fc4ef3-a705-4b5a-a0ff-d7ddf24e9c20.mp4
*How to test?*
1. Visit a systems details page
2. Observe the loading behaviour, especially of the button
=> fix(RemediationButton): Add loading fallback to avoid spinner

src/Utilities/hooks/useTableTools/useTableSort.js, src/Utilities/hooks/useTableTools/useTableSort.test.js, src/Utilities/hooks/useTableTools/useTableTools.js
When no items are present there should be no sorting set on the table:
**Before:**
https://user-images.githubusercontent.com/7757/140058734-3f2816b0-2580-4ab9-af73-6b6947124fa0.mp4
**After:**
https://user-images.githubusercontent.com/7757/140058486-1b51e848-e105-4f01-b004-ae4099920af7.mp4
1. Visit any systems details page with rules
2. Apply a filter that would yield no results and verify no sorting is set.
=> fix(TableTools): RHICOMPL-1778 - Set no sortBy when there are no items

src/App.scss, src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/constants.js, src/SmartComponents/SystemsTable/hooks.js
This changes the OS filter on systems tables to only show OS version that are present in the set of systems, instead of all possible versions.
1. Visit any page with a SystemsTable
2. Check the OS filter and verify only OS version are shown that have systems in the table
=> feat(SystemsTable): RHICOMPL-1808 - Use osVersions meta field for OS filter

src/PresentationalComponents/RulesTable/Columns.js, src/Utilities/hooks/useTableTools/useTableTools.js
On tables that use the bulk select and selected filter, items would not be exported if there were selected items and the filter activated.
=> fix(TableTools): RHICOMPL-2438 - Pass selected items to export if any

src/PresentationalComponents/TabSwitcher/TabSwitcher.js, src/PresentationalComponents/TabSwitcher/TabSwitcher.test.js, src/PresentationalComponents/TabSwitcher/__snapshots__/TabSwitcher.test.js.snap
This properly implements a fallback to a default tab if the active one does not exist, for example when an unknown anchor is set.
1. Go to any page, for example the policy details or edit policy
2. Verify tabs still work
3. Manually change the anchor/hash in the URL to something random/unknown
4. Verify that the default/first tab is shown
=> feat(TabSwitcher): RHICOMPL-1777 - Implement and use default fallback tabs

src/PresentationalComponents/ReportsTable/Columns.js, src/PresentationalComponents/ReportsTable/ReportsTable.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/constants.js
Remove the feature flag used for the report PDF download.
1. Open the report details page and/or the reports overview
2. Verify the "Download PDF" button is present (with and without the feature manually enabled  by adding `?pdfReport=enabled` or `?pdfReport=disabled`)
=> chore(Reports): RHICOMPL-2410 - Remove PDF feature flag

src/App.scss, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap, src/Utilities/hooks/useTableTools/Components/__snapshots__/TableToolsTable.test.js.snap, src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterConfigBuilder.js, src/Utilities/hooks/useTableTools/__snapshots__/useFilterConfig.test.js.snap, src/constants.js
When there are no systems assigned to a policy the results for the operating system versions are empty.
Before the dropdown would appear without items:
This adds an item similar to what is in the tags filter with no tags available:
1. Create and/or edit a policy to have no systems
2. Vist the systems tab on the policy details
3. Select the OS filter and verify
=> feat(SystemsTable): RHICOMPL-2446 - Implement empty state for OS filter

src/Utilities/hooks/useTableTools/FilterConfigBuilder/ChipBuilder.js, src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterConfigBuilder.js, src/Utilities/hooks/useTableTools/useFilterConfig.js
OS filter supports selectable groups. Currently this is broken because the conditional filter went trough some changes, this PR fixes such issue, bye sending the change event to parent component everytime and by mapping the selected values correctly.
* This feature will be fully supported once https://github.com/RedHatInsights/frontend-components/pull/1310 is merged. However since the conditional filter is part of inventory it's not required to wait for 1310 to be merged. We can freely merge this one and once FEC PR is merged and inventory updated it will start working as it should.
=> Update filters to support selectable groups

package-lock.json, src/PresentationalComponents/ComplianceThresholdHelperText/ComplianceThresholdHelperText.js, src/PresentationalComponents/ComplianceThresholdHelperText/ComplianceThresholdHelperText.test.js, src/PresentationalComponents/ComplianceThresholdHelperText/__snapshots__/ComplianceThresholdHelperText.test.js.snap, src/PresentationalComponents/ProfileThresholdField/ProfileThresholdField.js, src/PresentationalComponents/ProfileThresholdField/__snapshots__/ProfileThresholdField.test.js.snap, src/PresentationalComponents/index.js, src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/validate.js, src/SmartComponents/EditPolicy/EditPolicyDetailsTab.js, src/SmartComponents/EditPolicy/EditPolicyForm.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicyDetailsTab.test.js.snap
I had to modify how useValidateThreshold hook works, because i could not think of any other solution to how to differentiate between the two error states that can happen
=> fix(EditPolicy): RHICOMPL-741 restrict entering of long floats

src/SmartComponents/ReportDownload/hooks/useQueryExportData.js
With this filter hosts for the export are properly returned. Before this it could occur that the PDF report fails when a report has only a few hosts and there are (at least +100) hosts before these hosts in the database.
=> fix(ReportDownload): RHICOMPL-2455 - Pass filter for test results

src/PresentationalComponents/RulesTable/RulesTable.js, src/PresentationalComponents/TabbedRules/ProfileTabContent.js
https://github.com/RedHatInsights/compliance-frontend/commit/f1a64fb40df7a6aa7c3c34e6ecec052ed21c6373#diff-f3088209a94cef4be43a8666799ccd2cb4b52fed78c2d58f4e078d310bdba6a7 Introduced the profile as a prefix for the identifier to address selection issues in reports with multiple policies, but it introduced issues with preselecting items in the table, which would render the rules tables in the wizard and the edit policy empty.
=> fix(RulesTable): RHICOMPL-2479 - Adapt rule selection to include profile

.env.defaults, README.md, config/dev.webpack.config.js
With this the `npm run start:proxy` and `npm run start:proxy:beta` should work out of the box.
=> fix(devtools): RHIF-6 - Make example .env defaults file

src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/EditPolicySystems.test.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.test.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap
This updates the queries for the systems in the Create Policy wizard and the Edit Policy modal to also include the specific minor versions of the selected/edited policy in addition just the major OS version.
1. Open the Create policy wizard 
2. Select a policy and advance to the "Systems" step
3. Verify on the Systems step that only systems specific to the supported OS minor versions are shown.
4. Finish the Wizard
5. Open the "Edit Policy" modal for the policy created
6. Switch to the "Systems" tab
7. Verify that only systems for the specific OS version of that policy are shown.
=> feat(Policies): RHICOMPL-2116 - Limit systems by minor version too

src/SmartComponents/ReportDetails/Components/ReportedSystemRow.js
- Sign in with an account that has reports.
- Select a report that has at least one system that never reported.
Before, this row would have left and right borders that are the same color as the
background. With this fix, the left and right borders should be the same
color as the top and bottom borders of the row.
=> fix(ReportedSystemRow): RHICOMPL-2745 Add dark boarders

src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap, src/SmartComponents/PolicyDetails/__snapshots__/PolicySystemsTab.test.js.snap, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap, src/SmartComponents/SystemsTable/constants.js, src/SmartComponents/SystemsTable/hooks.js
**Note:** Before merging, please test in Chrome as well as FireFox to verify the date works in both as there are difference in support of date formats. \o/
=> fix(SystemsTable): RHICOMPL-2306 - Use updated instead of lastScanned

src/SmartComponents/ReportDownload/constants.js, src/SmartComponents/SystemsTable/hooks.js
When not passing the insights_id to the `LastSeen` component it will mistakenly show a "Not connected" icon. This will fix the issue and only show the icon if there is indeed no insights_id for a system.
=> fix(SystemsTable): RHICOMPL-2306 - Still include insightsId/_id for connected info

src/Routes.js, src/Utilities/__snapshots__/Router.test.js.snap
Downloading a PDF should, like other export formats only require read permissions.
=> fix(ReportPDF): RHICOMPL-2943 - Only require report:read permission

src/SmartComponents/ReportDownload/constants.js
Added a rulesFailed to the GraphQL request. That was the last part missing, everything else works fine.
Now PDF report contains the rules failed number.
(Don't look at the N/A - this patch is not merged yet)
=> fix(ReportPDF): Added a query parameter for the rulesFailed

src/PresentationalComponents/ComplianceScore/ComplianceScore.test.js, src/PresentationalComponents/ComplianceScore/__snapshots__/ComplianceScore.test.js.snap, src/Utilities/TextHelper.js
It was requested to show the "number%" instead of N/A even in cases when there is a 0 compliance score.
This function was utilized both by table and Donut Chart.
=> fix(ReportsTable):fixed the n/a in the table

src/PresentationalComponents/TabbedRules/TabbedRules.js, src/SmartComponents/EditPolicy/EditPolicyForm.js, src/SmartComponents/EditPolicy/EditPolicyForm.test.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.js, src/SmartComponents/EditPolicy/EditPolicySystemsTab.js, src/SmartComponents/EditPolicy/__snapshots__/EditPolicyForm.test.js.snap, src/SmartComponents/EditPolicy/__snapshots__/EditPolicySystemsTab.test.js.snap, src/SmartComponents/EditPolicy/components/NewRulesAlert.js, src/SmartComponents/EditPolicy/constants.js, src/SmartComponents/EditPolicy/hooks/index.js
This corrects the behaviour of the alert about new rules at the bottom of the "Systems" tab.
it now correctly identifies if there is a new set of rules to configure if a systems with a minor version is selected that had not yet been covered by a rule set.
*How to test:*
1. Find a profile with multiple supported RHEL minor versions
2. Select systems only of one minor version and create the policy
3. Edit the policy.
4. The modal on the Systems tab should not show the alert when first loaded.
5. Select systems of a different minor version
6. The Alert should appear and allow to switch to the "Rules" tab via the link
7. (When removing all systems of a specific minor version, the alert should disappear again)
8. After saving and reopening there should again not be any alert on the Systems tab …
=> fix(EditPolicy): RHICOMPL-1783 - Correct behaviour of alert for new rules

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/__snapshots__/SystemsTable.test.js.snap, src/SmartComponents/SystemsTable/constants.js, src/SmartComponents/SystemsTable/hooks.js
Resolves: [RHICOMPL-3304](https://issues.redhat.com/browse/RHICOMPL-3304)
As we are working on making tags filter consistent, using the shared filter is required. This PR removes the implementation of a custom tag filter and adopts the shared filter from the InventoryTable component.
=> fix(InventoryTable): RHICOMPL-3304 use shared tags filter instead of custom one

src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.js
Found a bug that was breaking the save function. 
PLUS
A small improvement
I added a logic that removes unsaved changes if the user closes inline edit by pressing on the "pencil" icon-button.
=> fix(editPolicyInline): fixing a bug with inline edits

config/fedMods.js, src/Modules/ComplianceDetails.js, src/SmartComponents/SystemDetails/ComplianceDetail.js, src/SmartComponents/SystemDetails/NoPoliciesState.js, src/SmartComponents/SystemDetails/SystemDetails.js, src/SmartComponents/SystemDetails/__snapshots__/NoPoliciesState.test.js.snap, src/SmartComponents/SystemDetails/__snapshots__/SystemDetails.test.js.snap, src/Utilities/Router.js
This fixes the issue when viewing the Compliance tab in the Inventory application of a host without any compliance data.
To test:
1) Go to the Inventory applications
2) Choose a host without any compliance 
3) Open the "Compliance" tab
Without this change the page will fail with an error that the react router context can not be found.
This introduces a memory router to address the issue and allow `Link` components and other hooks dependent on react-router work in the federated module and can link back to the appropriate page within Compliance. 
=> fix(ComplianceDetails): Allow routing to root app from fed module

src/App.js, src/PresentationalComponents/LinkWithPermission/LinkWithPermission.test.js, src/PresentationalComponents/WithPermission/WithPermission.js, src/PresentationalComponents/WithPermission/WithPermission.test.js, src/Utilities/hooks/useRoutePermissions.js
Fixes this error raised in Sentry by defaulting to an empty array if no route or required permissions are found: 
It also switches to the RBAC hook with context to get rid of this error, that occurs, because the old RBAC hook is trying to update a state.
=> fix(useRoutePermissions): RHICOMPL-3465 - Default to an empty array if no route is found

src/Utilities/ruleHelpers.js
The ruleIdentifier and ruleReferences fields are no longer double-JSON-encoded since https://github.com/RedHatInsights/compliance-backend/pull/1523, so we can drop the `JSON.parse` from the frontend part.
=> fix(Rules): RHICOMPL-3434 consume identifier/references as objects

src/Utilities/hooks/useFeature.js
This is a small change to the `useFeature` hook to allow enabling and disabling it's log output via a feature flag.
By default, as it is undefined it will always be disabled, but can be enabled by appending a parameter to any url on compliance like `/insights/compliance/reports?debugFeatures=enable`.
=> feat(useFeature): Add feature flag for debugging flags

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js, src/PresentationalComponents/ComplianceEmptyState/__snapshots__/ComplianceEmptyState.test.js.snap, src/PresentationalComponents/ErrorPage/ErrorPage.js, src/PresentationalComponents/ErrorPage/__snapshots__/ErrorPage.test.js.snap, src/SmartComponents/Reports/Reports.js, src/SmartComponents/Reports/__snapshots__/Reports.test.js.snap
I found and fixed a couple of places in compliance where error/empty states had bad or inconsistent layout.
1. On all pages, broken error state layout, and on the reports page, the header is not rendered: ![image](https://user-images.githubusercontent.com/31385370/210824060-6357c00d-8569-4931-b882-4de7bf02142a.png)
3. On the reports page, the empty state is centered with Bullseye which is not consistent with all other platform empty states (centered on top, but no vertically), the header has `h1` which is not correct (from the accessibility perspective), and also there is unnecessary extra `<br />` between the header and content: ![image](https://user-images.githubusercontent.com/31385370/210824277-782b533f-e097-41fb-bf9c-edad6ed701f2.png)
1. …
=> Fix several empty state layout bugs and inconsistencies

package-lock.json, package.json
There's an error of invalid hook calls with new PDF version. This is caused by charts using hooks and we need to have two versions of React because of async rendering of charts. There's a warning about incorrect import of theme colors, @RedHatInsights/platform-experience will take the initiative and duplicate the code from PF in frontend components PDF package since PF no longer supports these functions.
=> fix: Update pdf package to latest version

src/PresentationalComponents/InUseProfileLabel/InUseProfileLabel.js, src/SmartComponents/CreatePolicy/Components/PolicyTypeTable.js
2 things were changed here:
1) Moved 'In Use' label to the left side
2) Added a new tooltip explaining 'In Use' label
**Before:**
**After:**
=> fix(PolicyTypeTable): RHICOMPL-3413 - Move 'In Use' before policy type

src/PresentationalComponents/RulesTable/RuleDetailsRow.js, src/PresentationalComponents/RulesTable/__snapshots__/RuleDetailsRow.test.js.snap, src/SmartComponents/PolicyDetails/PolicyDetails.js
1) References and identifiers are shown now on both pages (System details and Policy details->Rules).
2) Fixed spacing between elements
**Before:**
**After:**
Also closing https://issues.redhat.com/browse/RHICOMPL-3165 here
=> fix(RulesTable): RHICOMPL-3530 - Show Identifiers and Refs for rules

src/SmartComponents/SystemsTable/SystemsTable.js
We depend on first request made for systems table and the first one is about OS versions. Request response doesn't have tags so view can't have proper empty state.  
If we have both checks for undefined and 0 value, we cover both cases - 
1) systems step view is loaded for the first time (first request is getSystems where we request os_versions and tags have undefined value) 
2) We use filter on this page and our request retrieves systems so we have tags value
**BEFORE:**
**AFTER:**
=> fix(EmptyStateView): RHICOMPL-3539 - Show no system enabled again

src/App.scss, src/Charts.scss, src/PresentationalComponents/ReportsTable/Cells.js, src/PresentationalComponents/ReportsTable/ReportsTable.js, src/PresentationalComponents/ReportsTable/__snapshots__/Cells.test.js.snap, src/PresentationalComponents/ReportsTable/__snapshots__/ReportsTable.test.js.snap, src/SmartComponents/ReportDetails/Components/ReportChart.js, src/SmartComponents/ReportDetails/Components/__snapshots__/ReportChart.test.js.snap, src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap
This PR replaces the bar chart on the reports table with the donut chart. It also fixes the counts which were previously incorrect.
The "total number of systems" considered in the main reports view do not take into account neither the reported or unsupported systems in the X of Y systems.
Though, the bar chart displayed on each of the report entries does take them into account (displaying the unsupported systems in yellow, and the never-reported systems in gray)
Steps to Reproduce:
have one unsupported system reporting
have 2 more additional systems associated to the reported policy Check reports page
=> fix: Unsupported systems not in system count

src/Utilities/hooks/useTableTools/useBulkSelect.js
See Jira card comments for steps on navigating to default rules table. `/insights/compliance/scappolicies/{POLICY_ID}/default_ruleset`
Description of problem
Default rules table crashes if you type non existing rule name
How reproducible
Always
Steps to Reproduce:
Navigate to Default rules table page
Search for 'foo'
Expected results
No crashes
=> fix(RHICOMPL-3535): Default rules table crash on filter

src/PresentationalComponents/ComplianceRemediationButton/constants.js, src/PresentationalComponents/TabbedRules/ProfileTabContent.js, src/SmartComponents/CreatePolicy/constants.js, src/SmartComponents/EditPolicy/constants.js, src/SmartComponents/PolicyRules/PolicyRules.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/ReportDetailsWithNotReportedSystems.js, src/SmartComponents/ReportDownload/constants.js, src/SmartComponents/Reports/Reports.js, src/SmartComponents/SystemDetails/ComplianceDetail.js, src/SmartComponents/SystemDetails/SystemDetails.js, src/SmartComponents/SystemsTable/constants.js, src/Utilities/helpers.js, src/Utilities/hooks/usePolicyQuery/constants.js
There are 4-5 unique query names that make our GQL metrics useless as we cannot see which query is slow. I am now prefixing the query names with some unique few letter combination describing in which class are they being used. This way if a query is slow, we can look it up in the codebase.
=> feat(metrics): RHICOMPL-3502 make query names unique

.codeclimate.yml
The cypress tests currently affect the Maintainability score on Code Climate negatively.
We should exclude them like other test files.
See https://codeclimate.com/github/RedHatInsights/compliance-frontend/src/SmartComponents/CompliancePolicies/CompliancePolicies.cy.js/source#issue-3bf6d23b3b7ded49362dd50d603846b4
=> fix(code-climate): Exclude cypress tests as well

src/PresentationalComponents/LinkButton/LinkButton.js
[RHICOMPL-3518](https://issues.redhat.com/browse/RHICOMPL-3518)
The issue mentioned in the ticket has been partially fixed by the router upgrade, but new issue has appeared when you click the button, you're not redirected to Compliance. This PR fixes this.
I've replaced `useNavigate` with `useInsightsNavigate` and set the app to compliance. This shouldn't affect any functionality other than when you click the link from Inventory, you're redirected to compliance + the provided link.
1. Open Inventory and select a system
2. Go to the Compliance tab
3. You should see something like this
4. Click `Create new policy` and make sure you're redirected to /compliance/scappolicies/new and a modal is opened.
=> fix(RHICOMPL-3518): Fix create policy button on Inventory

src/SmartComponents/SystemsTable/hooks.js
Fixes https://issues.redhat.com/browse/ESSNTL-3718.
Fixes improper group_name filter construction in gq filter.
Have a group which name has spaces (like "Test group"). Add some compliance systems to it, and make sure you are able to filter by this group on /compliance/systems.
=> fix(ESSNTL-3718): Wrap group names in brackets

src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.js
[RHICOMPL-3936](https://issues.redhat.com/browse/RHICOMPL-3936)
Previously there was no permission check for editing of the policy details
Now if you don't have `compliance:policy:write` you don't see the pen.
| Before              | After               |
| ---------------------- | ---------------------- |
| ![image](https://github.com/RedHatInsights/compliance-frontend/assets/20592948/0b384098-0ad9-453e-8737-23d29029703d)|![image](https://github.com/RedHatInsights/compliance-frontend/assets/20592948/adb6c7f1-73b2-4c7e-99b1-209828ee4002)|
Test with and without the `compliance:policy:write` permission
=> fix(RHICOMPL-3936): Disable inline policy editing for Compliance viewer

src/SmartComponents/SystemsTable/hooks.js
This fixes an issue where the selection is lost due to passing improper filters when fetching systems.
1. Open a SCAP policy with already assigned systems to edit
2. Open the "Systems" tab and search for a (specific) host.
3. Select the host (while the filter is active)
4. The host should have been added to the selection (including previously selected hosts)
=> fix(SystemsTable): RHINENG-2222 - Filter correctly when fetching selection

src/SmartComponents/SystemsTable/SystemsTable.js, src/SmartComponents/SystemsTable/SystemsTable.test.js, src/SmartComponents/SystemsTable/__snapshots__/hooks.test.js.snap, src/SmartComponents/SystemsTable/hooks.js, src/SmartComponents/SystemsTable/hooks.test.js, src/SmartComponents/SystemsTable/hooks/useFetchSystems.js, src/SmartComponents/SystemsTable/hooks/useFetchSystems.test.js
This fixes the issues of the SystemsTable loosing the proper default filter when resetting filters, while still fixing the issue with selecting a system while filtering.
1) Open the systems page note the number of all systems.
2) Filter systems
3) Reset the filter
4) Verify that the count of systems is the same again as initially noted.
=> fix(SystemsTable): RHINENG-2222 - Fix variable handling when fetching

src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/__snapshots__/EditPolicySystems.test.js.snap, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/ReportDetails/__snapshots__/ReportDetails.test.js.snap, src/SmartComponents/SystemsTable/hooks.js
Implements https://issues.redhat.com/browse/RHINENG-1840.
Recognise group column sort parameter (when available). This updates the systems table on the following views:
- /systems
- /reports/%id
- /scappolicies/new
The Inventory change is not yet merged to ensure that the tenant apps support sorting first and avoid breaking change.
1. Pull this Inventory PR locally https://github.com/RedHatInsights/insights-inventory-frontend/pull/2070.
2. Run Compliance with this PR `npm run start -- --port=8004`
3. Run Inventory with `LOCAL_APPS=compliance:8004~http npm run start:proxy`
4. Navigate to the updated views (in stage-stable environment) and make sure you can sort by system groups.
=> feat(RHINENG-1840): Support sort by group column (#679)

config/dev.webpack.config.js
This restores the possibility of having API routes for applications as well.
**How to test:***
Start the proxy with `LOCAL_APIS` like:
```sh
$ LOCAL_APIS=compliance:3000,inventory:8081,ingress:8080 npm run start:proxy
```
Verify that routes are proxied for the apps mentioned in the env variable.
=> fix(webpack): Append routes to config

src/Routes.js, src/SmartComponents/ComplianceSystems/ComplianceSystems.js, src/SmartComponents/ComplianceSystems/__snapshots__/ComplianceSystems.test.js.snap
This PR addresses the title change, "remove the 'Compliance' prefix in 'Systems' page."
Associated Jira ticket: [#RHINENG-5544](https://issues.redhat.com/browse/RHINENG-5544)
Checklist: 
Check the presented title in Systems page is shown without the "Compliance" prefix.
Systems Page:
Systems Page:
=> feat(RHINENG-5544): System title - Remove prefix

package-lock.json
https://issues.redhat.com/browse/RHINENG-6137
> @adobe/css-tools versions 4.3.1 and earlier are affected by an Improper Input Validation vulnerability that could result in a denial of service while attempting to parse CSS.
=> chore(RHINENG-6137): Fix CVE in css-tools

src/PresentationalComponents/RulesTable/RulesTable.js
Just found out that it works when you navigate on systems page, but if you clear filter and set some other filter - Rule state filter is automatically set to show Failed rules (even if I didn't touch it). Was able to catch it by automation.
=> fix(RHINENG-2764): Follow up fix

src/SmartComponents/SystemsTable/Cells.test.js, src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterConfigBuilder.js, src/Utilities/hooks/useTableTools/FilterConfigBuilder/__snapshots__/FilterConfigBuilder.test.js.snap, src/Utilities/hooks/useTableTools/__snapshots__/useFilterConfig.test.js.snap
Seems after migration, behavior of components changed. `defaultValueForFilter` was always return us empty string if filter type was text but at the end we got state `undefined` as:
```
< a = ''
< a ? a : undefined
> undefined
```
after PF change it stopped working and seems we need to send an empty string as value for text filters.
It works with the current fix:
[Screencast from 2024-05-28 14-04-49.webm](https://github.com/RedHatInsights/compliance-frontend/assets/33912805/7ee7c5d2-7d96-4c43-b6dd-52ec142b8733)
=> fix(RHINENG-10329): Fix input value clear for filter type text

src/Routes.js
Fixes https://issues.redhat.com/browse/RHINENG-5929.
This changes the zero state logic and makes Compliance request only RHEL systems. If there are only CentOS systems available for account, the zero state must be displayed in this case as well.
=> fix(RHINENG-5929): Look only for RHEL systems for ZeroState

src/SmartComponents/EditPolicy/EditPolicy.js
- SCAP Policies
- Edit Rules
- clicking through various tabs,
- clicking the “cancel” link or the “x”
and
- SCAP Policies
- clicking kebab on a policy
- clicking "Edit policy"
- clicking through various tabs
- clicking the "cancel" link or the "x"
Notice how it goes back to the previous tab, functioning like a "back" button rather than a "cancel" or  "close"
Closing the modal in both instances should take you to the policy details page for that policy
=> fix(RHINENG-10871): edit rules close should close modal

src/Utilities/hooks/api/useReport.js, src/Utilities/hooks/useQuery/useQuery.js, src/Utilities/hooks/useQuery/useQuery.test.js
After all we need the refs, because otherwise, the `refetch` function changes every render and this code could be stuck in a loop:
```js
useEffect(() => {
refetch();
}, [location, refetch]);
```
Included a test that verifies the reference is still the same.
=> fix(useQuery): object for options, refetch memoized

src/SmartComponents/CreatePolicy/ReviewCreatedPolicy.js
https://issues.redhat.com/browse/RHINENG-2136
To test:
1. Open the wizard to create a new SCAP policy
2. Go to the Review step
3. Observe the spacing between the rows
- space below policy name (C2S for Red Hat Enterprise Linux 6) should be the same as spacing between (Policy type and Compliance threshold) and (Compliance threshold and Systems)
- space above policy name (C2S for Red Hat Enterprise Linux 6) should be the larger than spacing below the policy name
=> fix(RHINENG-2136): Fix spacing in Create policy wizard review step

src/Routes.js, src/SmartComponents/EditPolicy/EditPolicy.test.js, src/SmartComponents/EditPolicy/hooks.js, src/SmartComponents/EditPolicy/hooks.test.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/SmartComponents/PolicyDetails/PolicyDetails.test.js, src/Utilities/dataSerialiser.js, src/Utilities/hooks/usePolicyQuery/usePolicyQuery2.js
[RHINENG-10398](https://issues.redhat.com/browse/RHINENG-10398)
Divided work from [this PR](https://github.com/RedHatInsights/compliance-frontend/pull/2091)
Includes code for the policy detail tab and inline editing.
Policy rules tab and systems tab are expected to not function properly.
This PR keeps compatibility between both of the APIs. We use the `compliance-api-v2` feature flag to switch between the APIs. You can switch it in unleash or manually set the values to `true` or `false`. Search for `apiV2Enabled`, it exists in two places.
1. To test the API V2 version, you need to manually fetch the policies, since the old IDs don't match on the list page.
2. Put this in the console on the compliance page:
`fetch("/api/compliance/v2/policies/").then(res => res.json()).then(data => …
=> feat(APIV2): Policy detail page (detail tab)

src/SmartComponents/DeletePolicy/DeletePolicy.js, src/SmartComponents/DeletePolicy/DeletePolicy.test.js, src/SmartComponents/DeletePolicy/constants.js, src/Utilities/hooks/useQuery/apiInstance.js
[RHINENG-11723](https://issues.redhat.com/browse/RHINENG-11723)
Policy deletion using both APIs. Both should work.
How to test:
1. Test the V2 version
2. Enable the `compliance-api-v2` feature flag or manually hardcode `apiV2Enabled` to true in `CompliancePolicies` and `DeletePolicy`
3. Test the policy gets deleted and table is updated
4. Repeat for GraphQL version
=> feat(APIV2): Delete Policy modal

.codeclimate.yml, .gitignore, .travis.yml, coverage.sh, package-lock.json, package.json
This changes the `coverage.sh` script to also run the test suite (jest + cypress) to gather coverage and combines into a html report under `./coverage`. The three reports are also uploaded to `codecov` with separate flags, which will allow us to compare the reports also on `Codecov`.
It also cleans up includes/excludes for both coverage reports to be aligned and not include unnecessary files.
Babel and other dependencies needed to be updated to have everything working correctly, for some reason.
1) Run `./coverage.sh`
2) Open the HTML reports in `coverage`, `coverage-cypress` & `coverage-jest`
3) Verify that the report makes sense and the percentages "add up" in the combined report.
=> chore(tests): Improve coverage reporting

src/SmartComponents/SystemsTable/hooks.test.js, src/Utilities/hooks/useQuery/useComplianceQuery.test.js, src/Utilities/hooks/useQuery/useQuery.js, src/Utilities/hooks/useQuery/useQuery.test.js
Previously a new API request was made exactly on the moment of a filter change.  E.g. a text filter would make a request on each keystroke.
Now the fetching function is debounced to 200ms.
Updated the tests accordingly since we need to wait some time for the debounce to resolve.
=> feat(useQuery): add debounce

src/SmartComponents/PolicyDetails/PolicySystemsTab.js
This puts an empty state when customers filtering existing systems in Policy systems tab.
To test:
1. Navigate to Policy detail page
2. open systems tab
3. search for non-existing system
4. observe that an empty state exists
=> fix: empty state for PolicySystems tab

src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyGraphQL.js
Fixes https://issues.redhat.com/browse/RHINENG-12789.
After the last commits, we have accidentally removed the In use label which identifies the policy types that are already in use. Such policy types must be disabled when creating a new policy since the GraphQL doesn't support duplicates.
=> fix(CreateSCAPPolicyGraphQL): Return the "In use" label

src/SmartComponents/PolicyDetails/PolicySystemsTab.js
This PR fixes 2 issues:
1. Getting `defaultFilter` back as it's needed for graphql to show systems correctly on PolicyDetails Systems tab when APIv2 FF is disabled (without this filter we show all Compliance systems, not only systems that are assigned to policy)
2. Checking `policy.totalHostCount` if it's 0 to show correct empty state as when we are using APIv2, we don't have policy.hosts.length info ( You can simply verify it by having APIv2 FF turned on and navigate to PolicyDetails Systems page and check that you can see empty state table when Policy has no systems assigned. See screenshot below )
=> fix(RHINENG-10400): Policy details systems minor fixes

package-lock.json, src/SmartComponents/SystemsTable/SystemsTableGraphQL.js, src/SmartComponents/SystemsTable/SystemsTableRest.js, src/SmartComponents/SystemsTable/hooks.js, src/SmartComponents/SystemsTable/hooks/useLoadedItems.js, src/SmartComponents/SystemsTable/hooks/useLoadedItems.test.js, src/Utilities/unionBy.js, src/Utilities/unionBy.test.js
Fixes https://issues.redhat.com/browse/RHINENG-13404.
This enables selection in the Systems table when the REST API feature flag is set on. This also revisits useSystemBulkSelect and makes it cache the items fetched in the table. This way the table does the required minimum number of requests to REST API GET /systems when paginating or selecting all items.
Go to /systems, /reports/:id pages or open the /scappolicies/new (Create policy, the systems step) wizard and check that the selection works properly. The table shouldn't do unnecessary requests to GET /systems if the data is already loaded.
For example, if you have more than one page of systems and you select all via bulk select, unselecting and selecting back shouldn't trigger any new requests nor render a spinner.
No change in the …
=> fix(SystemsTable): Enable selection and refactor useSystemBulkSelect

src/PresentationalComponents/ComplianceEmptyState/ComplianceEmptyState.js, src/SmartComponents/SystemDetails/NoReportsState.js
PR fixes 2 things related to empty state:
1. Icon size - since Compliance had different icon size for some empty states I had to set it directly using `style` as it's not PF5 default size
2. Fixed spacing between empty state bodies
Before:
After:
=> fix(RHINENG-9785): Fix empty state icon size & spacing

src/SmartComponents/PolicyDetails/PolicyMultiversionRules.js
Our automation caught a bug when EditRules button disappeared from policy details Rules tab. This PR returns it back
=> fix(RHINENG-10399): Get edit rules button back

src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.js, src/SmartComponents/CreatePolicy/CreateSCAPPolicy/CreateSCAPPolicyRest.test.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.test.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyBase.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyGraphQL.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyGraphQL.test.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyRest.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyRest.test.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/index.js, src/Utilities/hooks/api/useAssignRules.js, src/Utilities/hooks/api/useAssignSystems.js, src/Utilities/hooks/api/useCreatePolicy.js
Implements https://issues.redhat.com/browse/RHINENG-12792.
This decouples the FinishedCreatePolicy component into REST/GraphQL components depending on the feature flag set on/off respectively. `updatePolicy` for the REST component performs several steps to create a new policy: creates a policy using selected profile, assigns systems, fetches newly created tailorings and assigns rules to every tailoring.
Go to the policies page and open a modal by clicking Create new policy. Choose any major OS, select a profile. Follow the systems and rules selections steps (these ones are not changed anyhow with this PR). In the final step, check that the overview contains correct OS selected, the number of systems and other details. Submit the creation and verify that the policy is successfully created. …
=> feat(RHINENG-12792): Migrate the Review (final) wizard step

src/SmartComponents/SystemPolicyCards/SystemPolicyCards.js
There is the case when you have your system assigned to multiple policies but it's not reported against each policy - we will still try to show a card (you can see an GridItem - we show there an empty component). This is happening because we have multiple reports returned but some of them have 0 test results ( as system is never reported)
To repro:
- Go to Compliance -> Systems
- Find a system with multiple policies but at least one policy with 0   test results (data.meta.total === 0)
Before, the GridItem would render, but with no card.
Now, the GridItem has been moved into the child component and will only display the GridItem if the meta.total > 0.
=> fix(RHINENG-14334): System detail shows empty GridItem

src/Frameworks/AsyncTableTools/__fixtures__/columns.js, src/Frameworks/AsyncTableTools/__fixtures__/filters.js, src/Frameworks/AsyncTableTools/__fixtures__/items.js, src/Frameworks/AsyncTableTools/__fixtures__/tableTree.js, src/Frameworks/AsyncTableTools/components/AsyncTableToolsTable/AsyncTableToolsTable.test.js, src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.test.js, src/Frameworks/AsyncTableTools/hooks/useColumnManager/helper.js, src/Frameworks/AsyncTableTools/hooks/useColumnManager/useColumnManager.js, src/Frameworks/AsyncTableTools/hooks/useColumnManager/useColumnManager.test.js, src/Frameworks/AsyncTableTools/hooks/useFilterConfig/filterChipHelpers.test.js, src/Frameworks/AsyncTableTools/hooks/useFilterConfig/useFilterConfig.test.js, src/Frameworks/AsyncTableTools/hooks/useItems/useItems.test.js, src/Frameworks/AsyncTableTools/hooks/useTableSort/useTableSort.test.js, src/Frameworks/AsyncTableTools/hooks/useTableView/useTableView.test.js, src/Frameworks/AsyncTableTools/hooks/useTableView/views/treeChopper.test.js, src/Frameworks/AsyncTableTools/utils/withExport/helpers.test.js, src/Frameworks/AsyncTableTools/utils/withExport/withExport.test.js, src/PresentationalComponents/ReportsTable/Columns.js, src/Utilities/hooks/useTableTools/__fixtures__/columns.js, src/Utilities/hooks/useTableTools/__snapshots__/useTableSort.test.js.snap, src/Utilities/hooks/useTableTools/useColumnManager.js
[RHINENG-14286](https://issues.redhat.com/browse/RHINENG-14286)
On the migrated Reports page in column manager, there is an additional field (its the download button)
This PR removes it. The key stuff is in `useColumnManager.js` in `AsyncTableTools`.
Since there can be a difference in tests and the download button works **differently** there. I've copied fixtures to `AsyncTableTools` and all the tests use these ones instead the `TableTools` fixtures. Open for discussion, but it breaks the tabletools tests.
It's covered by tests.
1. Enable API V2 and Async Tables in local storage
Set `insights:compliance:apiv2` to `true`
Set `insights:compliance:asynctables` to `true`
2. Go to reports page
3. Check the column manager that the additional column isn't there
4. Verify the download button is …
=> fix(useColumnManager): hide unmanageable columns from column manager

src/SmartComponents/CreatePolicy/EditPolicySystems.js
We need to have this additional filter that will prevent already assigned systems (to same policy) appear in system list. This is something new as with APIv2 we introduce ability to create duplicated policies. We don't want 1 system being assigned to 2-N same policies
=> fix(RHINENG-14376): filter systems correctly on Wizard

src/Frameworks/AsyncTableTools/__fixtures__/filters.js, src/SmartComponents/SystemsTable/SystemsTableRest.test.js, src/SmartComponents/SystemsTable/constants.js, src/constants.js
if searching systems by name with the space - page fails because we are sending filter without quotes and backend thinks it's 2 parameters. 
=> fix(RHINENG-14374): Put filter name in double quotes

src/PresentationalComponents/TabbedRules/OsVersionText.js, src/PresentationalComponents/Tailorings/Tailorings.js
This one fixes rules tab ordering and treats `0` minor version correctly.
Before if you had minor version`0` you would see this:
=> fix(RHINENG-14371): fix tabs ordering and 0 value

src/SmartComponents/SystemDetails/useTestResults.js
No jira.
How to test: navigate to any system details page and make sure it loads properly (previously with this bug the page was showing infinite loading spinner because test results requests failed with 422).
=> fix: Fix another params order issue un useReportTestResults

src/PresentationalComponents/RulesTable/components/InlineValueEdit.js, src/PresentationalComponents/RulesTable/components/RuleValueEdit.js, src/PresentationalComponents/RulesTable/helpers.js, src/SmartComponents/PolicyRules/PolicyRules.js
Rules Table was unable to open more than 2-4 rows without crashing. This just adds little checks and prevents the table from crashing. 
To test:
navigate to any rules table, rows view and open up multiple.
Rules table in policy details 
Rules table in default_ruleset reached from creatPolicy->rules step-> default rules link
=> fix(rulesTable): Allow rules table to open multiple rule

src/SmartComponents/SystemDetails/SystemDetails.js, src/SmartComponents/SystemsTable/SystemsTableRest.js, src/SmartComponents/SystemsTable/hooks.js, src/SmartComponents/SystemsTable/hooks/useLoadedItems.js, src/SmartComponents/SystemsTable/hooks/useLoadedItems.test.js, src/Utilities/hooks/api/useSystem.js
Fixes https://issues.redhat.com/browse/RHINENG-14588.
This addresses one of the bugs found in the edit policy modal, the systems tab. The problem was that the selection remembered only the items preselected on the first page.
=> fix(RHINENG-14588): Fix the selection handling in edit systems

src/SmartComponents/ReportDownload/Components/ReportPDF.js, src/constants.js
PDF download was failing because of incorrect type mapping for business objective. 
How to reproduce issue:
1. Have a reported policy
2. Set business objective for policy
3. Navigate to reports page and try to download PDF report using GQL API (use stage/prod stable where we don't have v2 enabled)
4. Observe that backend requests are made and notifications about suceeded download appear but no download happens
With this fix it works again. Checked with REST v2 & GQL
=> fix(RHINENG-14132): PDF download GQL when BO is set

src/Frameworks/AsyncTableTools/__fixtures__/filters.js, src/PresentationalComponents/ReportsTable/Filters.js, src/PresentationalComponents/RulesTable/Filters.js, src/SmartComponents/ReportDetails/ReportDetails.js, src/SmartComponents/SystemsTable/SystemsTableRest.js, src/SmartComponents/SystemsTable/constants.js, src/SmartComponents/SystemsTable/hooks.test.js, src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterBuilder.js, src/Utilities/hooks/useTableTools/FilterConfigBuilder/FilterBuilder.test.js, src/Utilities/hooks/useTableTools/FilterConfigBuilder/__snapshots__/FilterBuilder.test.js.snap, src/constants.js
This PR does couple things:
1. Set 'Name' filter as default for system table (before you could see different filters)
2. Wraps checkbox filter items in brackets when filter is selected. For example, `filter=display_name ~ "fdsf" AND (policies = ... OR policies=....)` so filter order doesn't affect sorting and it applied correctly
3. `os_version` filtering is used. So instead of sending request with `filter=(os_major_version=7 AND os_minor_version=8) OR (os_major_version=7 AND os_minor_version=9)` we will send `filter=os_version ^ (7.8 7.9)`
4. Fixed os_version filtering on Report details page for Not reported systems tab
=> fix(RHINENG-14513): Fix filter behavior

src/PresentationalComponents/InlineEdit/InlineEdit.js, src/PresentationalComponents/RulesTable/RulesTableRest.js, src/PresentationalComponents/Tailorings/components/TailoringTab.js, src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRules.js, src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyBase.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyRest.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicyRest.test.js
Fixes https://issues.redhat.com/browse/RHINENG-14527.
This fixes the create policy wizard: when overriding at least one rule values, the wizard should call PATCH request additionally to update the value overrides.
Try to create a policy and find the rules which has some value to override. Set any value and follow up to the finish step. When submitting the policy creation, make sure the policy creation is complete. Follow to the policy details page and verify that the rules has all the value overrides you set in the wizard.
=> fix(RHINENG-14527): Enable value editing when creating a SCAP policy

.github/workflows/main.yml
This adds a sentry hook, to work more as a button. A manual job with an input, being the commit hash, that will upload source maps with that specific build
=> Create workflow for sentry sourceMaps

src/PresentationalComponents/RulesTable/RulesTableRest.js, src/PresentationalComponents/RulesTable/helpers.js
**Haven't created JIRA for this one as it's super small fix**
If you navigate to policy details Rules tab and expand rule that has some value firstly - page will throw an error as values are not loaded yet. Fix will prevent error and expanded rule will wait for API response
Before:
```
TypeError: Cannot read properties of undefined (reading 'refId')
at 193.ecdabd904c06366681c1.js:142:18386
at Array.find (<anonymous>)
at 193.ecdabd904c06366681c1.js:142:18375
at Array.some (<anonymous>)
at m (193.ecdabd904c06366681c1.js:142:18349)
at 193.ecdabd904c06366681c1.js:142:7125
at rl (chrome-root.d6ec82adcca2f232.js:2:230321)
at _s (chrome-root.d6ec82adcca2f232.js:2:250451)
at chrome-root.d6ec82adcca2f232.js:2:249193
at Es (chrome-root.d6ec82adcca2f232.js:2:249258)
``` …
=> fix(RulesTable): prevent error on rule expand

src/Frameworks/AsyncTableTools/utils/withExport/withExport.js, src/PresentationalComponents/Tailorings/components/TailoringTab.js, src/Utilities/hooks/useFetchTotalBatched.js
This fixes the export for the Rules step in the "Create Policy" wizard.
1) Open the "Create Policy" wizard and advance to the Rules step
2) Try exporting the rules as JSON or CSV
3) Verify the export has been downloaded and the items inside equal the rules in the table
4) Test exporting with and without filters applied
=> fix(Tailorings): RHINENG-14520 - Fix export for wizard

src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js, src/Frameworks/AsyncTableTools/hooks/useBulkSelect/__snapshots__/useBulkSelect.test.js.snap, src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.js, src/Frameworks/AsyncTableTools/hooks/useTableView/helpers.js, src/Frameworks/AsyncTableTools/hooks/useTableView/views/index.js, src/Frameworks/AsyncTableTools/hooks/useTableView/views/treeChopper.js, src/PresentationalComponents/RulesTable/RulesTableRest.js, src/PresentationalComponents/Tailorings/components/TailoringTab.js, src/PresentationalComponents/Tailorings/helpers.js, src/PresentationalComponents/Tailorings/helpers.test.js, src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js
This enables the group selection for the rules table.
1.a) Open the "Create Policy" wizard and advance to the "Rules" step
1.b) Open the Edit Policy on the rules tab
2) Select and deselect a group and/or a rule and verify the selected items are correctly updated
3) Test the same with and without filters set
=> feat(Tailorings): Implement group selection

src/SmartComponents/SystemDetails/EmptyState.js, src/SmartComponents/SystemDetails/EmptyState.test.js
Can't use OR when 0 value can be returned as 0 || undefined will return us undefined and as the result empty state is not shown correctly. Also covered this case by test
=> fix(RHINENG-14893): Fix bug with OR and improve tests

src/PresentationalComponents/RulesTable/RulesTableRest.js, src/PresentationalComponents/RulesTable/components/RuleValueEdit.js, src/PresentationalComponents/Tailorings/Tailorings.js, src/PresentationalComponents/Tailorings/components/TailoringTab.js, src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRulesRest.js
There is an issue when altering the value of a rule, where 1, it does not save, and 2, when updating one and opening another, the first gets reset.
To reproduce: 
- Navigate to Create policy wizard
- Go to Rules step
- Find any rule that has value (search for "password" or "ssh" and most of these rules have values)
- Expand rule and patch value
- Expand rule that goes after patched one
- **Old Behavior** Observe that value of patched rule has been changed to default one (we still store patched values and will apply them, so bug is only visual)
- **New Behavior** Observe that the value is saved. Note that when alter rules, many times the valueCheckIds for the rules are the same, so alter one may alter all the following rules.
Observe everywhere that the value is correct for the rule.
The …
=> fix(RHINENG-15120): Fix rule patching in policies

src/SmartComponents/EditPolicy/EditPolicyFormRest.js
I was looking into Sentry issues and found out that it's possible that when system is selected on Edit policy modal - minor version is `undefined` and as result we get non-working rules tab. I also found minor issue with count labels.
To test:
1. Have Policy with minor version X assigned (let's say RHEL8 policy with system 8.6)
2. Go to edit policy modal and open systems tab
3. Search system by name with minor version Y (let's say you have system test.foo 8.4)
4. Select system
5. Open Rules tab and observe that there are 2 tabs: 8.6 & 8.4 and labels are set correctly
Before:
we see error in console `TypeError: Cannot read properties of undefined (reading 'id')` and v2 request is sent with undefined minor version:
`/api/compliance/v2/security_guides?limit=1&ids_only=true&sort_by=version:des …
=> fix(RHINENG-15635): Set system minVer correctly on search&select

.github/workflows/main.yml, fec.config.js
This also removes the issue where the plugin is initialized locally and sends up debugIDs for local env on every build
**Workflow Behavior:**
**Locally (without variables):**
The Sentry plugin won't build as SENTRY_AUTH_TOKEN is not defined.
**GitHub push to master (automatic trigger):**
The plugin won't include the authToken because commit_hash is not provided in push events.
**Manually triggered with commit_hash:**
The plugin includes the authToken and tracks the build with Sentry.
=> fix(sentry): Update sentry flow

src/Frameworks/AsyncTableTools/hooks/useAsyncTableTools/useAsyncTableTools.js
Respect radio select when sorting by columns
How to test:
1. Navigate to create policy wizard
2. Select any OS major version
3. Check Policy types table if it's sorted by policy name by default and sorting works as expected
=> fix(RHINENG-13541): Make sorting work for Table with radioSelect

src/SmartComponents/PolicyRules/PolicyRules.js
While poking around, I found out that we don't have export on Default profile rules page. So I'm bringing it back here. + making rules list expand work by ignoring rule values (as it was before migration)
1. Open Edit policy modal rules tab
2. Use view default rules link to navigate to Default profile rules page
3. Try to export CSV/JSON
4. Click on list table
5. Try to expand rules
=> Add export defaul rules page

src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.test.js, src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicy.test.js, src/SmartComponents/EditPolicy/EditPolicyForm.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.js, src/SmartComponents/EditPolicy/hooks.js, src/SmartComponents/PolicyDetails/hooks/useSaveValueOverrides.js, src/Utilities/hooks/api/useUpdateTailoring.js
This PR fixes rule values update on EditPolicy modal.
**Before the fix:**
If you try to update value - page reloads and on second try page is going to crash
**After the fix:**
Value changes are respected and on Save button click PATCH request is sent for tailoring.
1. Have freshly created policy with 1 assigned host with minor version X
2. Navigate to Edit policy rules tab
3. Find any rule that has value to edit (hint: search for "selinux" or "passord")
4. Use inline edit to update a value to something that you will remember (like classic "foo")
5. Do not save changes, open systems tab and add 1 more system but with minor version Y (different from first one)
6. Open rules tab back and observe 2 minor version tabs
7. Check if tab with X still has value that you set
8. Try …
=> fix(RHINENG-16323): Make value update work EditPolicy

src/SmartComponents/EditPolicy/EditPolicy.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.js
Follow up PR:
this one will take care of: 
1. saving value state on multiple profile selection. 
2. saving values correctly on multiple value edit for 1 profile/tailoring
How to test:
1. Have Pre-created policy with minor ver X
3. Open edit policy modal rules tab
4. Edit 2 values for X
5. Switch to systems tab and select minor ver Y
6.  Edit 2 values for Y
7. Switch to systems tab and select minor ver Q
8. Edit 2 values for Q
9. Check if values you edited for X, Y and Q are still there.
=> fix(RHINENG-16323): Respect value selection on multiple profile select

src/PresentationalComponents/RulesTable/RulesTableRest.js, src/PresentationalComponents/Tailorings/Tailorings.js, src/PresentationalComponents/Tailorings/components/TailoringTab.js, src/PresentationalComponents/Tailorings/helpers/skips.js, src/PresentationalComponents/Tailorings/helpers/skips.test.js, src/SmartComponents/EditPolicy/EditPolicyRulesTab.js, src/Utilities/hooks/api/useComplianceTableState.js
There are fixes for some issues I found after https://github.com/RedHatInsights/compliance-frontend/pull/2388 
1. List rules view stoped showing checkboxes to select/unselect rules because `total` has been removed
2. Replaced `paramsParam` with `paramsOption` to respect also filters (found out that `filter` is not respected on EditPolicy systems table
3. When I was checking value editing on Create policy wizard I found out that valueOverrides are saved but UI still show default values so it's fixed now `...valueOverrides?.[osMinorVersion]`
4. Couple fixes for EditPolicy rules selection - Make `additionalRules` respect profiles and not only tailorings for showing tree correctly, make list rules show data on profiles if there are some selected (do not skip), use `setUpdatedPolicy` correctly …
=> fix(Tailorings): Follow up multiple fixes

src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRules.js
Fixes showing pre-selected rules for a newly selected profile
1. Navigate to create policy wizard
2. Go to Systems step
3. Select system os_minor_version X
4. Proceed to Rules view
5. Check if rules are pre-selected
6. Step back to Systems step
7. Select system with os_minor_version Y
8. Proceed to Rules step and check if both rules tabs have pre-selected rules
=> fix(CreatePolicyRules): Wait on preselected items for RulesTable

src/PresentationalComponents/PolicyDetailsDescription/PolicyDetailsDescription.js, src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.js, src/SmartComponents/EditPolicyDetails/EditPolicyDetailsInline.test.js, src/SmartComponents/PolicyDetails/PolicyDetails.js, src/Utilities/hooks/api/useComplianceQuery.js
1. Error when updating policy data (because refetch wasn't passed correctly)
2. No more re-render and api request when edit is cancelled
3. Styling fix for textArea (now edit description area is a bit bigger)
4. Test coverage
1. Navigate to policy Details tab
2. Try to update threshold, business obj & description ( see that it works )
3. Try to start editing and then cancel edit (no re-rendering happens, no api request made)
=> fix(RHINENG-16777): Fix policy inline edit

src/SmartComponents/SystemsTable/Cells.js, src/SmartComponents/SystemsTable/Cells.test.js
This changes the failed rules column on ReportDetails to show `0` instead of `N/A`. 
**Before:**
**After:** 
=> fix(SystemsTable): RHINENG-13831 - Don't show N/A for 0 failed rules

src/PresentationalComponents/ComplianceRemediationButton/ComplianceRemediationButton.js, src/PresentationalComponents/ComplianceRemediationButton/components/FallBackButton.js
https://issues.redhat.com/browse/RHINENG-16658
In accordance with the above ticket, this changes the text on the remediations button to say 'plan remediation' instead of 'remediate'
In compliance the button can be found in report details page
=> feat(RHIENG-16658): Change Remediate button label to Plan remediation

src/Frameworks/AsyncTableTools/hooks/useBulkSelect/useBulkSelect.js
PR fixes selection on System details page when we have 0 preselected items (`selectedIds` is undefined).
1. Navigate to System details page and ensure that single selection works
2. Check if bulk select works on System details too
=> fix(RHINENG-17367): Define bulkSelect selectedIds before accessing it

src/SmartComponents/SystemsTable/Cells.js
=> fix(RHINENG-13839): Tooltip content misalignment never reported

src/PresentationalComponents/Tailorings/Tailorings.js, src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRules.js, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/validate.js
This PR changes the behaviour of the "Create Policy" wizard to allow creating policies without initially assigning hosts and default to set up a policy with profiles for all available minor OS versions. 
https://github.com/user-attachments/assets/a73fa52a-062c-4f77-8e04-04b077d6e400
1) Open the "Create policy" wizard
2) Choose a policy and proceed to the "Systems" step
3) Do NOT select any hosts and verify that it is possible to advance to the "Rules" step
4) Verify the "Rules" step loads all minor OS version profiles correctly and shows know assigned hosts.
5) Move forward to the finishing steps and verify the policy was correctly created
=> feat(CreatePolicy): RHINENG-15324 - Allow policies without hosts

src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.test.js, src/Utilities/hooks/api/useCreateTailoring.js, src/Utilities/hooks/useComplianceQuery/index.js, src/Utilities/hooks/useComplianceQuery/useComplianceMutation.js
This is a followup to https://github.com/RedHatInsights/compliance-frontend/pull/2487
and adds explicitly creating the tailorings if no hosts were selected.
1) Follow the steps described in https://github.com/RedHatInsights/compliance-frontend/pull/2487
2) Open the policy and ensure that it does have tailorings on the "Rules" tab
=> fix(CreatePolicy): RHINENG-15324 - Explicitly create tailorings when no hosts

src/PresentationalComponents/ReportsTable/Cells.test.js, src/SmartComponents/ReportDetails/Components/ReportChart.test.js, src/SmartComponents/ReportDetails/Components/hooks/useDonutChart.js, src/__factories__/reports.js
Counting score has been fixed on backend side so we can directly use it from response instead of calculating it by ourself.
1. Have reported systems (you can use compliance script to upload it or just account that has some reported systems)
2. Navigate to Reports/Report details pages
3. Check if score inside donut chart shows correct value (compliant_systems / assigned_systems) * 100%
=> feat(RHINENG-14515): Use Report score value from backend resp

src/SmartComponents/CreatePolicy/CreatePolicy.js, src/SmartComponents/CreatePolicy/EditPolicyProfilesRules/EditPolicyProfilesRules.js, src/SmartComponents/CreatePolicy/EditPolicySystems.js, src/SmartComponents/CreatePolicy/FinishedCreatePolicy/FinishedCreatePolicy.js, src/SmartComponents/CreatePolicy/validate.js, src/SmartComponents/SystemsTable/hooks/useSystemsBulkSelect.js, src/store/Reducers/SystemStore.js
1. System selection on Wizard - if you select systems, Rules step will show tabs with selected only systems. If you have no systems selected - rules step shows all available rule tabs
2. Removes image builder feature flag since it's already exposed for all in prod
3. Fixes filter for systems table in wizard so now it respects minor versions
4. Fixes tailoring creation when you have 0 systems selected
5. Fixes rules selection on Create policy wizard
6. Fixes bulk select issue for systems table when 0 systems pre-selected
1. Navigate to create policy wizard and select any policy that has at least 2 minor version supported
2. Go to systems tab
3. Select minor version X and Y
4. Move next to Rules tab and try unselect/select some rules. Also check if tabs do show correct numbers (for N of …
=> fix(RHINENG-20542): Handle systems selection correctly
